### ISSUE TITLE
Allow addons to add new biomes to the Aether.

### ISSUE THREAD

**Issue by Foreck1** [Gilded-Games/The-Aether#10]
The current version of the mod uses the harcoded `BiomeProviderSingle`

The mod should ideally have configurable list of biomes so that other mods can hook onto the generation of the Aether dimension, thus, mods like BiomeTweaker could interact with it. This is, above all, a technical request for modpack makers who want to flesh out the dimension.

P.S. pretty sure this is not relevant for gilded games at this point, but I would be truly awesome if this feature could make it to 1.12 too.

**Comment by bconlon1** [comment]
Should probably move this to the The-Aether-Archived repo since that's the 1.12 one.

**Comment by Foreck1** [comment]
Well, although I'll do that too, this could still be advantageous moving forward. Let me know if this is relevant for versions above 1.16; if not and the methods are all different, then you can just close this issue

**Comment by bconlon1** [comment]
This could still be relevant so I will rename it to be more accurate to its relevancy. I imagine it'd likely have to be done differently in 1.16+ due to world gen changes but as I'm not one of the 1.16 devs I'm not sure of the specific differences.

**Comment by quek04** [comment]
Given the fact we're in 1.16 land, you could easily just add biomes to the Aether using a datapack!

**Comment by quek04** [comment]
You could overwrite the aether.json dimension file (which defines how the dimension generates and what biomes appear) and change the aether's biome provider. At least I think. I don't know entirely!
