### ISSUE TITLE
[Feature Request] Make Aether Portals use a block tag instead of Glowstone

### ISSUE THREAD

**Issue by reetamb** [Gilded-Games/The-Aether#100]
For compat and datapacking purposes

**Comment by reetamb** [comment]
There should be an item tag for portal ignition items as an extension to this

**Comment by bconlon1** [comment]
If I add the portal ignition tag I can probably remove the config for making skyroot buckets only work on portals since thats a modpack thing that modpackers can just use tags for instead.
