### ISSUE TITLE
Bug: Crouching while on a Moa can activate Parachutes automatically

### ISSUE THREAD

**Issue by OzPayn** [Gilded-Games/The-Aether#1007]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

44.1.17

### The Aether Version

0.3.1

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

Fly up high with a Moa with a Gold parachute in inventory
Start falling
Hold crouch to begin fast falling
Eventually (if high enough/fast enough) the parachute will deploy and kick you off your Moa
Usually because you're holding crouch you will also dismount the parachute and fall

### What You Expect To Happen

The Moa falls and the parachute does not activate

### What Actually Happened

The Moa falls and the parachute activates

### Additional Details

This is annoying

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Need an additional check here for whether the player is riding a vehicle: https://github.com/Gilded-Games/The-Aether/blob/f9724acd5b65e9042f8d4a23f82359b0f0c7a2a2/src/main/java/com/gildedgames/aether/capability/player/AetherPlayerCapability.java#L310
