### ISSUE TITLE
[Feature Request] Angelic Stone in a stonecutter should allow for the player to make Valkyrie Pillars

### ISSUE THREAD

**Issue by reetamb** [Gilded-Games/The-Aether#101]

**Comment by Ultrasquid9** [comment]
perhaps it could be made with gold ingots instead, to make them a renewable resource for builders. that way they could get large amounts quicker.

**Comment by reetamb** [comment]
It also would be nice to have ways of renewing the other types of dungeon stone, though how this would be handled is beyond me. Maybe recipes can be locked behind advancements or something?

**Comment by Ultrasquid9** [comment]
the recipes could be simply stonecutting holystone. I'm not sure if the recipes need to be advancement locked, they're just fancy tiles after all.
