### ISSUE TITLE
Bugged Swet Riding Boat

### ISSUE THREAD

**Issue by beeboiMinecraft** [Gilded-Games/The-Aether#1010]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

44.1.20

### The Aether Version

0.3.1

### Steps to Reproduce

1. Place a Boat
2. Make a swet ride the boat
3. Ride the swet when it is on the boat

### What You Expect To Happen

I thought I could be able to ride a boat while on swet

### What Actually Happened

Swet turned flat when on boat. Then when I was on the swet the swet got large

### Additional Details

https://user-images.githubusercontent.com/126361509/221382949-dcb7cfd1-7903-4775-a2bd-e06a0b9da949.png

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
This doesn't really break anything and is technically consistent with Slimes so I'm gonna close this and keep it as a quirk to their animations.
