### ISSUE TITLE
Bug: Cloud Staff Crashing

### ISSUE THREAD

**Issue by AtomicJuno** [Gilded-Games/The-Aether#1011]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Crash

### Forge Version

44.1.0

### The Aether Version

1.19.3 0.3.1

### Crash Report (if applicable)

https://gist.github.com/AtomicJuno/15ddc0add9c55e66455c0c9a53ecefcd

### Steps to Reproduce

Unknown method of reproducing; Please check the crash log

### What You Expect To Happen

Game plays as normal with cloud staff

### What Actually Happened

Game Crashed after a while; log mentions cloud staff

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Need to check for the array size here: https://github.com/Gilded-Games/The-Aether/blob/c18dd1fae80f390c002c987369334cea8bde1d6a/src/main/java/com/gildedgames/aether/item/combat/loot/CloudStaffItem.java#L83

I'm assuming, the array might be shorter than 2 sometimes if a minion has for some reason died or isn't in the list yet.
