### ISSUE TITLE
Bug: Skyroot buckets can be duped by milking cows

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1043]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

44.1.0

### The Aether Version

1.19.3-0.4.0

### Steps to Reproduce

1. Grab a few skyroot buckets (I needed at least 3 for it to work)
2. Spam-click on a cow.

### What You Expect To Happen

I expected to receive as many buckets of milk as I was holding in my hand.

### What Actually Happened

I received one more bucket than I was supposed to.

### Additional Details

I was not able to reproduce this bug on a singleplayer world, only ANTS.
Another player on the server was unable to reproduce this bug.
Attempting to perform the dupe using a body of water instead of milk did not work.
Iron buckets seemed to be duplicable at first, but the duped items vanished when interacted with in any way.

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
I will note for whoever is able to look into fixing this: I think there was a Forge bug involved with events here, that a workaround was made for on our end. Maybe the bug was fixed and the code is now causing issues, or the workaround doesn't work, or this is another Forge issue.
