### ISSUE TITLE
Bug: Valkyrie tool reach stacks when equipped in both hands

### ISSUE THREAD

**Issue by Burning-Cactus** [Gilded-Games/The-Aether#1047]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

44.1.5

### The Aether Version

0.4.0

### Steps to Reproduce

Equip a valkyrie tool in each hand. The range will increase for each one equipped.

### What You Expect To Happen

Only one valkyrie tool should apply.

### What Actually Happened

The valkyrie tool reach bonus is doubled.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Burning-Cactus** [comment]
In my opinion, valkyrie tools should not apply additional reach in the offhand. No other tool in Minecraft applies attributes in that slot, and it's impossible for us to balance around using extended reach with other tools.

**Comment by Cinex20** [comment]
Seems to only work when both hands are holding valk tools, holding one in offhand and using a different tool / empty hand does nothing. The extended reach also works with the lance, which is hilariously broken.

**Comment by bconlon1** [comment]
> In my opinion, valkyrie tools should not apply additional reach in the offhand. No other tool in Minecraft applies attributes in that slot, and it's impossible for us to balance around using extended reach with other tools.

Mentioned before in the todo list but it turns out stacks aren't able to be aware of other stacks when it comes to attribute generation at all so I also believe the only way to solve this probably would be removing their ability in the offhand.
