### ISSUE TITLE
Feature: Immersive Portals compatibility

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#105]
It'd be expected that aether portals would use the fancy rendering nether/end portals use when the mod is installed and that is enabled, but it still uses the conventional old portal style:

![2021-04-16_00 45 37](https://user-images.githubusercontent.com/52297970/114951894-2972ec80-9e4d-11eb-9c40-49d407b05c99.png)

**Comment by bconlon1** [comment]
Immersive portals doesn't seem to be actively supported on Forge anymore really so this is probably not gonna be happening unless they update.
