### ISSUE TITLE
Bug: Phoenix armor struggles against lava currents

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1064]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

44.1.0

### The Aether Version

1.19.3-0.4.0

### Steps to Reproduce

Seems to have a noticeable effect in Nether only.

1. Go to the Nether.
2. Dive into the lava ocean while wearing full phoenix armor.
3. Dig 2 blocks down when standing on the bottom.
4. Try to swim out.

Or

1. Go to the Nether.
2. Spill lava on a flat area.
3. Try to reach the source block while in phoenix armor.

### What You Expect To Happen

I expect to have good control of my character at all times while touching lava.

### What Actually Happened

My character is unable to swim out of a hole with the lava dragging it down and cannot push against horizontally flowing lava. Both actions are possible when a piece of armor is taken off.

### Additional Details

I was unable to reproduce this issue in the Overworld, the currents were never strong enough.
Neptune armor seems to have similar issues when in water (gets dragged down / pushed faster and gets pulled by magma block bubbles faster), but the impact is far less noticeable and does not create situations where taking it off is necessary.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by OzPayn** [comment]
Yep confirmed the issue, I'll look into it but no promises I'll be able to solve it lmao
