### ISSUE TITLE
Feature: Players should be able to hotswap gloves and pendants by right-clicking

### ISSUE THREAD

**Issue by Burning-Cactus** [Gilded-Games/The-Aether#1068]

**Comment by kodadacod** [comment]
As of Curios API 5.1.5.0 this is now possible. 
https://github.com/TheIllusiveC4/Curios/commit/22b38a0469e9b02521a87b091cf608d14d81472b 
https://legacy.curseforge.com/minecraft/mc-mods/curios/files/4493917
