### ISSUE TITLE
Feature: Aermail Episode II - Aether Rewrite

### ISSUE THREAD

**Issue by OzPayn** [Gilded-Games/The-Aether#1072]
Aermail video showcase for showcasing the Aether rewrite + various other bits and updates

- [x] script written
- [x] voice over
- [x] asset research
- [x] targeted footage filmed
- [x] b-roll filmed
- [x] artwork
- [x] editing
- [x] thumbnail
- [x] publishing

**Comment by bconlon1** [comment]
https://www.youtube.com/watch?v=Bj5gb8aGE7I
