### ISSUE TITLE
Bug: Aether foodstuffs give double the saturation they're supposed to

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1100]
### What Feature Types Apply to This Bug?

Entity, Item

### What Type of Bug Is This?

Design

### Forge Version

45.0.24

### The Aether Version

0.5.1

### Client Log

https://gist.github.com/kodadacod/d622f73d9a034b7e4ff715e6b9694c75

### Steps to Reproduce

Every time
1. Enchant a Blueberry
2. Eat the Enchanted Berry

### What You Expect To Happen

The Enchanted Berry would give 8.3 saturation points.

### What Actually Happened

The Enchanted berry instead gave 16.6 saturation points

### Additional Details

https://streamable.com/z7otgr

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kodadacod** [comment]
Upon further inspection this affects all Aether foodstuffs, not just golden berries.
https://streamable.com/zyxovw

**Comment by Cinex20** [comment]
It's not just enchanted berries, looks like every type of food gives double the intended saturation. From my testing, it looks like the issue lies in Forge itself, not Aether.

**Comment by Cinex20** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/9422
Confirmed to be a Forge issue. Nothing to do with Aether.
