### ISSUE TITLE
Bug: Incorrect Book of Lore entry for Valkyrie Lance

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1101]
### What Feature Types Apply to This Bug?

Block, Gui

### What Type of Bug Is This?

Design

### Forge Version

45.0.24

### The Aether Version

0.5.1

### Steps to Reproduce

Every time
1. Place a valkyrie lance in the Book of Lore

### What You Expect To Happen

The Book of Lore to say it is found in the Bronze dungeon

### What Actually Happened

The Book of Lore says that it is unique to the Silver Dungeon.

### Additional Details

![2023-03-26_08 12 27](https://user-images.githubusercontent.com/75467920/227790937-80f25f4c-b103-4ca9-b80f-f298c6fb98de.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Will need to look over all loot items for this especially depending if we readjust the loot tables again.

**Comment by OzPayn** [comment]
I will not be putting the Lance in the Silver Dungeon so I will look at fixing this issue tomorrow
