### ISSUE TITLE
Toggle Visibility is broken

### ISSUE THREAD

**Issue by sunsetbear** [Gilded-Games/The-Aether#1102]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.22

### The Aether Version

1.19.4-0.5.1

### Client Log

https://gist.github.com/sunsetbear/8909709aa879e9a5f3404175b8e05712

### Steps to Reproduce

Happens consistently.
-Open the Accessories Inventory
-Press a Toggle Visibility button. (That's it.)

### What You Expect To Happen

The visibility is toggled, and moving the cursor away from the button hides the "Toggle Visibility" dialog and allows other menu options to be used.

### What Actually Happened

No other part of the menu is usable, and the "Toggle Visibility" dialog does not go away until the menu is closed and re-opened.

### Additional Details

Hovering over the Toggle Visibility button does not highlight it or show the Toggle Visibility dialog, it only appears once clicked (and thus once the bug is active.)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
I haven't tested this yet but I have a suspicion this is probably a Curios bug if I understand what's going on here.

**Comment by bconlon1** [comment]
Reported here: https://github.com/TheIllusiveC4/Curios/issues/296
