### ISSUE TITLE
Reorient the Life Shard to match the Echo Shard's orientation

### ISSUE THREAD

**Issue by sunsetbear** [Gilded-Games/The-Aether#1104]
### What Feature Types Apply to This Request?

Art

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Rotate or flip the life shard's texture so it is oriented the same way as the echo shard.
![2023-03-26_18 27 54](https://user-images.githubusercontent.com/8252642/227808624-47659583-9ee7-454c-a37a-863b552cc02f.png)

### Why Should It Be in the Mod?

Artistically consistent with Vanilla.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Life Shards are consistent with Amethyst Shards in orientation; this is more of a vanilla annoyance when it comes to texture orientation inconsistencies.
