### ISSUE TITLE
Bug: Mounts cause desyncs sometimes

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1117]
### What Feature Types Apply to This Bug?

Entity

### Other Type

Desync

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.40 (server)
45.0.42 (my client)

### The Aether Version

1.19.4-0.6.1

### Steps to Reproduce

Only witnessed it once.
1. Get swallowed by a swet.
2. Kill it while it's still holding you **mid-air**.

### What You Expect To Happen

The swallowed players frees themselves and drops back to the ground.

### What Actually Happened

A desync happened. The swallowed player (Ceiheane), on their end, was freed and could play just fine. On my end, they ended up suspended in the air for a few minutes, stuck in the sitting animation. I could not see them moving around, but I could hear their steps. They were able to attack me and I was able to attack their "ghost", which did damage to them.

https://user-images.githubusercontent.com/112828225/230502749-d8336b95-63bf-4f5c-9746-8eb5f8e3165c.mp4

### Additional Details

The player reported having 191 ms of latency. They eventually returned to normal on my screen without relogging.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Seen with Moas as well.

**Comment by bconlon1** [comment]
Starting to think it may be caused by this hook we have, it's tied to a forge event that has been problematic with sidedness in the past iirc, we may have to look into implementing it some other way: https://github.com/The-Aether-Team/The-Aether/blob/b95e4287bcb93f094f5a51d1026ce25af13af8d5/src/main/java/com/aetherteam/aether/event/hooks/EntityHooks.java#L48.
