### ISSUE TITLE
Bug: Classic textures have random rotation

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1123]
### What Feature Types Apply to This Bug?

Art, Block, Config

### What Type of Bug Is This?

Design

### Forge Version

45.0.43

### The Aether Version

0.6.1

### Steps to Reproduce

Everytime
1. Enable the b1.7.3 textures or 1.2.5 textures
2. Look at a field of aether grass

### What You Expect To Happen

The legacy texture packs would not have random rotation on the grass.

### What Actually Happened

The legacy texture packs randomly rotate the top grass texture.

### Additional Details

1.19.4 w/ b1.7.3 textures
![b1 7 3](https://user-images.githubusercontent.com/75467920/230753472-9e8ac375-ecb3-416d-9d87-ceb87c9bf996.png)
1.19.4 w/ 1.2.5 textures
![r1 2 5](https://user-images.githubusercontent.com/75467920/230753580-7bc0d889-387e-4998-8c8b-45f74dbf7b32.png)

Original mod b1.7.3
![b1 7 3](https://user-images.githubusercontent.com/75467920/230753599-6972be10-560e-40e5-8d05-a5c71c97e24e.png)
Original mod 1.2.5
![1 2 5](https://user-images.githubusercontent.com/75467920/230753595-cac0a12d-bf98-4209-9922-fcc0826f386d.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kodadacod** [comment]
This affects Aether dirt, Quicksoil, and Enchanted aether grass as well. Classic-styled Aether dirt path should probably not have random rotation either.

**Comment by bconlon1** [comment]
Considering the lack of random rotation in modern vanilla grass textures it is probably not necessary to change this.
