### ISSUE TITLE
Feature Request: Right-clicking on tamed moas to toggle between follow and roam mode

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1127]
### What Feature Types Apply to This Request?

Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

This feature allows players to switch tamed moas from following them to using the default free roam ai without the use of a nature staff. Attached is a video from b1.7.3 of this feature. 
https://streamable.com/fnhcp8

### Why Should It Be in the Mod?

This feature was present in the original release of the mod for b1.7.3 so I feel it should be added to improve parity between versions.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Can you get a recording of this with a grown moa.
