### ISSUE TITLE
Bug: Dungeon structures need protection blocks properly reimplemented.

### ISSUE THREAD

**Issue by mkg20001** [Gilded-Games/The-Aether#113]
In twilight forest mod, some structures are protected - removing blocks results in them being placed back and some green sparkels

I think it makes sense to apply this to aether aswell, so only blocks that are meant to be broken in dungeons can be broken.

**Comment by Ultrasquid9** [comment]
this was in the original mod. it hasn't been re-implemented yet.

**Comment by bconlon1** [comment]
Bronze Dungeon:
- The entire dungeon is breakable (except trapped blocks), except for the boss room, which has locked unbreakable blocks.
- When the boss dies, the boss room becomes unlocked and breakable.

Silver Dungeon:
- Exterior blocks like the pillars and dungeon blocks that made up the pillar bases could be broken.
- All dungeon blocks making up the main building of the dungeon and roof are unbreakable. Although non-dungeon blocks in the boss room were breakable as they didn't have locked versions.
- Entire dungeon becomes breakable after the boss is defeated.

Gold Dungeon:
- Can't break any of the dungeon blocks.
- Entire dungeon becomes breakable after the boss is defeated.
