### ISSUE TITLE
Feature Request: Programmer Art-styled Skyroot Chest Boat texture

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1130]
### What Feature Types Apply to This Request?

Art

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

This would add a chest boat texture in the same style as programmer art. Attached is an example sprite and texture. 
![skyroot_chest_boat](https://user-images.githubusercontent.com/75467920/230822441-7f70c5cb-1315-4f79-a33d-abb428d7dd42.png)
![skyroot](https://user-images.githubusercontent.com/75467920/230825710-75fb371a-f2fd-4717-8cf3-02046482fc71.png)

### Why Should It Be in the Mod?

Adding this would improve the consistency of classic aether textures, making people who use classic textures have a better experience. This has also been done with various other blocks and items added in the port, so I feel this wouldn't be too out of scope.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by kodadacod** [comment]
I understand that this would be inconsistent with vanilla chest boats but I feel that is due to a neglect for programmer art rather than a purposeful design choice.

**Comment by sunsetbear** [comment]
Has this been reported to mojang as well? Hopefully they'll add it.

**Comment by kodadacod** [comment]
It has, but it's been closed as "Works as Intended" for various reasons; see here for more info https://bugs.mojang.com/browse/MC-169889.
