### ISSUE TITLE
Bug: Classic gui icons are incorrect

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1131]
### What Feature Types Apply to This Bug?

Art, Gui

### What Type of Bug Is This?

Design

### Forge Version

45.0.24

### The Aether Version

0.6.1

### Steps to Reproduce

Every time (it's art)
1. Enable b1.7.3 classic textures
2. Open the Aether inventory
3. Enable classic 1.2.5 textures
4. Open the Aether inventory again

### What You Expect To Happen

The b1.7.3 classic pack would use the proper gui icons from b1.7.3, and the 1.2.5 pack would do as such.

### What Actually Happened

Both classic packs use the gui icons from 1.19.

### Additional Details

![2023-04-09_21 16 04](https://user-images.githubusercontent.com/75467920/230832179-013e219a-21b5-4212-bbd2-b0e2cc7a2dc8.png)
![2023-04-09_21 17 03](https://user-images.githubusercontent.com/75467920/230832325-4bac565f-bb33-40af-b273-f8022d31284a.png)
![2023-04-10_09 53 35](https://user-images.githubusercontent.com/75467920/230961731-ab4d0377-5121-43f7-900d-870ec99e465b.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Aether originally only had different armor slot icons because beta Minecraft didn't have any yet. Now that Minecraft does have slot icons, we probably shouldn't mess with them (and the time when both of them existed during 1.2.5 didn't really look that good).
