### ISSUE TITLE
Bug: Mounts sometimes get abruptly stopped on blue aerclouds

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1133]
### What Feature Types Apply to This Bug?

Block, Entity

### What Type of Bug Is This?

None

### Forge Version

45.0.43

### The Aether Version

0.6.1

### Steps to Reproduce

Sometimes
1. Place down blue aercloud
2. Ride a mount (vanilla or modded) onto the blue aercloud 

### What You Expect To Happen

The mount would have no issue bouncing off the blue aercloud and would reach the maximum height every time.

### What Actually Happened

The mount sometimes had trouble bouncing off of the blue aercloud and reaching the full height of the bounce.

### Additional Details

This does not affect the player, only mounted mobs, and this affects both modded and vanilla mounts, not just modded ones.
https://streamable.com/41j38j

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Slime Block code may be helpful here to investigate

**Comment by Jonathing** [comment]
I've spent an hour trying to debug what the fuck is happening here. I haven't found the source, but I have a few pointers.

- The motion of the rider is unaffected.
- The motion of the mount does not abruptly change if the server TPS is low. It is clearly a calculation error.
- Overriding `updateEntityOnFall` has no affect.

**Comment by bconlon1** [comment]
Also mobs like horses take damage on blue aerclouds when they shouldnt
