### ISSUE TITLE
Bug: Gold dungeons don't generate with tall grass when enabled

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1134]
### What Feature Types Apply to This Bug?

Block, Config, World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.43

### The Aether Version

0.6.1

### Steps to Reproduce

Almost every time
1. Enable "Generate Aether tall grass" in common config file
2. Generate a new world
3. Find a Gold dungeon

### What You Expect To Happen

The gold dungeon would always generate with tall grass when enabled.

### What Actually Happened

The gold dungeon very rarely generates with tall grass, and even then only one small portion

### Additional Details

![2023-04-10_21 41 26](https://user-images.githubusercontent.com/75467920/231067261-f9657c0b-2e1a-423a-bc2a-b2b01aa052f6.png)
no tall grass at all
![2023-04-10_21 46 49](https://user-images.githubusercontent.com/75467920/231067701-7d3ffc40-1d5c-410f-b419-a9d81dc0e2f8.png)
odd patch of tall grass (this isn't consistent, seems to be a fluke)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kodadacod** [comment]
Related to this the aether surface populator seems to sometimes affect gold dungeons, generating skyroot trees and white & purple flower patches. This is probably why that patch of double tall grass generated as seen in the second attachment.
![2023-04-10_21 55 08](https://user-images.githubusercontent.com/75467920/231070827-c236fd62-7fcd-40a1-9e91-834888c81627.png)

**Comment by Burning-Cactus** [comment]
![2023-04-12_13 43 22](https://user-images.githubusercontent.com/23108473/231555807-86a6c568-0f79-4e63-94dc-a0d0eac4bc6d.png)
It's possible that this is a heightmap issue. This image was captured in 1.19.3 using debug utils.
