### ISSUE TITLE
Bug: Incorrect Aechor Plant group size

### ISSUE THREAD

**Issue by AtomicJuno** [Gilded-Games/The-Aether#1146]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Design

### Forge Version

45.0.43

### The Aether Version

0.6.1

### Steps to Reproduce

1. Search for an Aechor Plant
2. Note the fact they spawn in a single instance rather than a group

### What You Expect To Happen

They spawn in a patch/group similar to the older builds from b1.7-r1.2.5

### What Actually Happened

It spawned as a single instance.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
They seem to be set to spawn in groups but the random check for their spawning is causing them to often not spawn in groups.
