### ISSUE TITLE
doesnt generate worlds

### ISSUE THREAD

**Issue by aleabla0** [Gilded-Games/The-Aether#116]
i am using the aether reborn version for 1.16.5, and when i try to create a world it starts generating, but then it hardlocks. any help?

**Comment by Alexmasonseals** [comment]
aether reborn isn't created by our team.

please report this bug to their github

**Comment by reetamb** [comment]
https://github.com/devs-immortal/The-Aether/issues this is their github

**Comment by aleabla0** [comment]
OH.... sorry 😰😰. Thanks for the help
Il giorno lun 10 mag 2021 alle 17:53 reetamb ***@***.***> ha
scritto:

**Comment by quek04** [comment]
This isn't Aether Reborn.
