### ISSUE TITLE
Bug: Sentries do not attack attacker mobs back

### ISSUE THREAD

**Issue by AtomicJuno** [Gilded-Games/The-Aether#1167]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Design

### Forge Version

45.0.43

### The Aether Version

0.6.2

### Steps to Reproduce

1. Spawn a Sentry
2. If attacker mobs hit it, It will not pursue the attacker.

### What You Expect To Happen

Sentries attack back as hostile mobs do

### What Actually Happened

Sentries ignore the attacker

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Consistent with slime-like mob behavior.
