### ISSUE TITLE
Bug: Swets do not attack attacker mobs back

### ISSUE THREAD

**Issue by AtomicJuno** [Gilded-Games/The-Aether#1168]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Design

### Forge Version

45.0.43

### The Aether Version

0.6.2

### Steps to Reproduce

1. Spawn swet
2. Have attacker mob attack it, and note the Swet ignores it

### What You Expect To Happen

Swets attack back like hostile mobs

### What Actually Happened

Swets ignored the attacker mob.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Consistent with slime-like mob behavior.
