### ISSUE TITLE
Bug: Issue between quick load and servers

### ISSUE THREAD

**Issue by DampStone** [Gilded-Games/The-Aether#1170]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.43

### The Aether Version

1.19.4 ALPHA

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

The aether adds a "quick load” feature. It makes it so when you play your own private world, it loads super quickly yk?
But it breaks when using servers
The W button is the "toggle world" button
So it undoes any quick save stuff that interrupts your GUI and game. You can tell this is the problem if when you join, and are kicked out of the world, you go to your video settings (on the main menu) and you can see inside the server’s world, with things still working as normal. This means the main menu GUI is showing up despite the fact that you’re in loaded world
That's because the Aether mod is trying to make
OuickStart work for the server, which is likely confusing it’s to get around this, just hit that aether mod exclusive W button in the top right and it's fine
If that doesn’t work, then
1) open a new single player world
2) go to the main menu
3) press the T button (it starts quick load, it should have popped up)
4) go to the main menu again
5) press the W button
Now quick load is reset and you should be able to join a server

### What You Expect To Happen

The server would open normally

### What Actually Happened

Server do not open normally 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Jonathing** [comment]
Translation: The Quick Load button is attempting to load a server connection as a world. It is likely that this might happen if there are no single player saves on file.
