### ISSUE TITLE
Bug: Using /place to spawn a Silver Dungeon breaks chests

### ISSUE THREAD

**Issue by AtomicJuno** [Gilded-Games/The-Aether#1178]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.43

### The Aether Version

0.6.2

### Steps to Reproduce

1. use /place structure aether:silver_dungeon
2. check how many chests break open upon generation

### What You Expect To Happen

The chests remain intact

### What Actually Happened

Some chests are straight up missing, and some break open entirely 
![2023-04-22_10 43 14](https://user-images.githubusercontent.com/126373361/233801402-f900c5a7-b389-4787-8afc-9e58785470d4.png)
![2023-04-22_12 46 27](https://user-images.githubusercontent.com/126373361/233801409-0c8c215b-564f-4dfd-8970-b44b7fa57c4b.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
The chests sometimes appear to be replaced by air when /place is used, not sure why.
