### ISSUE TITLE
Gloves are under Player Sleeve Layer when in 1st person but are above the Player Sleeve Layer when in 3rd person.

### ISSUE THREAD

**Issue by BurningFlameU** [Gilded-Games/The-Aether#1179]
Shown With a Blank White Skin with 50% opacity Black Layer over the top:

  **1st Person:**
  ![image](https://user-images.githubusercontent.com/91836194/233806765-cd776860-fb6c-4d73-af76-646c990aa794.png)

  **3rd Person:**
  ![image](https://user-images.githubusercontent.com/91836194/233806779-0ea367e3-e583-4dd9-9383-479fc9bb678c.png)

  **Skin:**
  ![OpacitySkin](https://user-images.githubusercontent.com/91836194/233806726-f9cb2126-3567-45f1-aa81-c70f72cf792c.png)
  
  
  Edit: fixed images

**Comment by OzPayn** [comment]
I believe this is something you can change in the settings in the Aether inventory menu

**Comment by bconlon1** [comment]
Go to the Accessories Menu and the Customizations screen from the lower button on the left, there should be an option to toggle this.

**Comment by BurningFlameU** [comment]
Damn im just blind sry
I genuinely dont know how i didnt see it

**Comment by bconlon1** [comment]
No worries
