### ISSUE TITLE
I think moa wings are backwards

### ISSUE THREAD

**Issue by SteveJDM** [Gilded-Games/The-Aether#1184]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.46

### The Aether Version

aether-1.19.4-0.6.2-forge

### Steps to Reproduce

put a moa in the flying animation. 

### What You Expect To Happen

typically you would see the long flat part of wings on shoulders, similar to the Aether 2 moa model. 

### What Actually Happened

the wings appear to be backward when the moa is flapping them. there is an image in additional details of what it looks like

### Additional Details

![2023-04-22_23 58 38](https://user-images.githubusercontent.com/83166955/233820781-fb9feb61-6eac-4ccc-8f83-41fa9ac4831a.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
![2023-04-22_22 11 24](https://user-images.githubusercontent.com/67203206/233821021-3d623d64-94d6-427e-8961-b6e659e54d2c.png)
This is just how the wings are.
