### ISSUE TITLE
Bug: Banner patterns from other mods are incompatible with the testing build of the 1.19.4 Aether.

### ISSUE THREAD

**Issue by Protozoare** [Gilded-Games/The-Aether#1193]
### What Feature Types Apply to This Bug?

Block, Entity, Item

### What Type of Bug Is This?

Compatibility

### Forge Version

45.0.47

### The Aether Version

aether-1.19.4-0.6.2-forge

### Is This Bug a Conflict With Another Mod?

Any mod that adds new banner patterns, in this case, Alex's mobs

### Steps to Reproduce

This bug happens when trying to create a banner with the loom and any custom banner pattern from Alex's mobs.
How to reproduce:
1.Set up a 1.19.4 modpack with the Aether build stated here:aether-1.19.4-0.6.2-forge and Alex's mobs and the required dependencies. No other mods needed.
2.Next create a new world on creative. Pick any banner, a loom, a dye and a banner pattern that must be from Alex's mobs, because vanilla banner patterns work as intended, but any modded ones are not rendered on the loom, the inventory and the placed blocks. Open the loom and put the banner, dye, and pattern in the required slots. Observe how the banner pattern on the  newly crafted banner is not rendered, but still there in the blocks data.

![2023-04-23_23 47 28](https://user-images.githubusercontent.com/89633282/233865495-3c8db803-b2df-4675-860a-7afa660c8770.png)
![2023-04-23_23 47 37](https://user-images.githubusercontent.com/89633282/233865499-2e60a02b-96dc-4133-a1b0-ac8f3b8ff432.png)
![2023-04-23_23 47 48](https://user-images.githubusercontent.com/89633282/233865500-07cfb2e6-f535-4c06-984e-b51ed93aeee8.png)
![2023-04-23_23 47 18](https://user-images.githubusercontent.com/89633282/233865501-a69840db-7595-4340-8a44-97afaadcf4aa.png)

### What You Expect To Happen

The banner pattern from Alex's mobs mod would have been visible and working as intended.

### What Actually Happened

The banner pattern from the mod does not work as intended, and this only happens in combination with the Aether mod. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Can confirm this happens, but it's incredibly odd because we don't touch any banner code at all anywhere.
