### ISSUE TITLE
Aether Axes dont give "Wax Off" achievement

### ISSUE THREAD

**Issue by SteveJDM** [Gilded-Games/The-Aether#1194]
### What Feature Types Apply to This Bug?

Block, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.46

### The Aether Version

aether-1.19.4-0.7.0-forge

### Steps to Reproduce

use an aether axe, in this case I used Valkyrie, and right click a waxed copper block. ensure you do not have the "wax off" achievement when reproducing.

### What You Expect To Happen

the achievement would have been granted.

### What Actually Happened

the achievement wasn't granted, however, it was checked with a stone axe and the stone axe worked. 

### Additional Details

the video will be posted in dev aether chat.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Limitation with how vanilla handles a lot of its advancements.
