### ISSUE TITLE
Skyroot Milk buckets dont craft cake :(

### ISSUE THREAD

**Issue by SteveJDM** [Gilded-Games/The-Aether#1195]
### What Feature Types Apply to This Bug?

Item, System

### What Type of Bug Is This?

Compatibility

### Forge Version

45.0.46

### The Aether Version

aether-1.19.4-0.7.0-forge

### Steps to Reproduce

Try to make a cake recipe with skyroot buckets instead of iron buckets

### What You Expect To Happen

the cake to be made

### What Actually Happened

no cake :(

### Additional Details

Vanilla cake recipie 
![image](https://user-images.githubusercontent.com/83166955/233867613-ef58f4d7-3e00-43b6-801b-e92d087679ee.png)
Attempt with skyroot bucket
![image](https://user-images.githubusercontent.com/83166955/233867627-d252def9-5763-4916-86f2-ff55e6834a7b.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Jonathing** [comment]
In typical Jonathing fashion, I tried to make a black magic solution that involved reading all vanilla recipes that used buckets and creating new recipes in datagen that use skyroot buckets instead. Turns out, that would be too much file I/O and a waste of time instead of just copying the existing recipes that do this.
