### ISSUE TITLE
Bug: Dungeon Instances Overlapping

### ISSUE THREAD

**Issue by Jaryn-B** [Gilded-Games/The-Aether#1200]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta.1

### Client Log

https://gist.github.com/Jaryn-B/c8bd599325d4017243e4b77cc562dabd

### Steps to Reproduce

Uncertain on rarity
Step 1: Generate Aether.
Step 2: Locate dungeon.
Step 3: Get Lucky

Seed: 7062998705043299473
Coords (In Aether):  -132, 53, 176

### What You Expect To Happen

Dungeon instances should be exclusive to a location. Otherwise... Insert mess.

### What Actually Happened

Two Bronze dungeons overlapping, causing a grand mess.

### Additional Details

![2023-04-24_17 06 32](https://user-images.githubusercontent.com/91760563/234069967-e46238af-93a6-47ba-87b1-3277b1928c41.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kodadacod** [comment]
This is intended.

**Comment by Jaryn-B** [comment]
huh, okay then

**Comment by bconlon1** [comment]
Yeah this is mostly intended as something similar to how the dungeons behaved in beta, leading to cool interactions of the structures that don't break their functionality too much.
