### ISSUE TITLE
Bug: Falling with an Aerbunny equipped makes the crosshair attack indicator appear and flicker until you land.

### ISSUE THREAD

**Issue by devilbringer** [Gilded-Games/The-Aether#1201]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.47

### The Aether Version

1,19.4-1.0.0-beta.1

### Steps to Reproduce

Right click an Aerbunny to equip it to head.
Fall/Jump off something higher than a couple of blocks.
Just after you begin to fall watch the attack indicator flash.

### What You Expect To Happen

The attack indicator shouldn't have any reason to appear, let alone flicker.

### What Actually Happened

Attack indicator appears and flickers while falling.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
okay this happens when the player is descending with an aerbunny and using its ability while also looking at the proper angle to be looking at the edge of its hitbox or something

**Comment by OzPayn** [comment]
Just had this happen, seemed to happen just by falling a certain distance (try jumping off a cliff and just falling for a bit, the crosshair starts flashing kinda wildly)

**Comment by bconlon1** [comment]
Potential solution is I could make the aerbunny uninteractable when the player is falling with isPickable, would mean they can't dismount it but this is basically how all other mount-related entities work, but it would mean no crosshair showing up.

**Comment by bconlon1** [comment]
Nevermind figured out a better solution that doesn't change anything
