### ISSUE TITLE
general item dupe using skyroot sword

### ISSUE THREAD

**Issue by micrwvae** [Gilded-Games/The-Aether#1202]
### What Feature Types Apply to This Bug?

Entity, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.47

### The Aether Version

1.0.0 beta 1

### Steps to Reproduce

1.get a skyroot sword
2.equip a moa with a saddle
3.kill said moa

the moa drops 2 saddles

### What You Expect To Happen

no item dupe

### What Actually Happened

item dupe

### Additional Details

havent tested it with horses but it might also dupe the horse armor

could also work as a general item dupe with lamas or donkeys equipped with chests

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by MelonVision** [comment]
Can confirm the dupe works with items in llama and donkey chests.

**Comment by bconlon1** [comment]
Might have to mixin into dropFromLootTable for mobs for the ability so that only natural drops double.
