### ISSUE TITLE
Bug: ice ring/pendant void water from waterlogged blocks

### ISSUE THREAD

**Issue by micrwvae** [Gilded-Games/The-Aether#1203]
### What Feature Types Apply to This Bug?

Block, Item

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.47

### The Aether Version

1.0.0 beta1

### Steps to Reproduce

1.have watersources and waterlogge blocks at feet level
2.equip a ice trinket
3.water gets turned into ice while the waterlogged blocks 'dry out'

### What You Expect To Happen

waterlogged blocks dont void their water while sources freeze to ice

### What Actually Happened

water freezes as expected but waterlogged block loose their water

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
This is working as intended; there's no way to convert waterlogged blocks to ice so drying out waterlogged blocks instead seemed to make the most sense.

**Comment by bconlon1** [comment]
(If you think waterlogged blocks should prevent freezing you could open a feature request ticket and it could be discussed)

**Comment by micrwvae** [comment]
omw
