### ISSUE TITLE
Bug: Rubidium causes chunks to disappear

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#1207]
Supposedly this is fixable on our end. Even if it shouldn't have to be. https://github.com/Beethoven92/BetterEndForge/blob/master/src/main/java/mod/beethoven92/betterendforge/mixin/BiomeColorsMixin.java#L31
https://github.com/Asek3/Rubidium/pull/448

**Comment by embeddedt** [comment]
I'd advise against using the BetterEnd solution without doing more research first; I am not sure that `getBlockState` can safely be called on the client world from another thread (this is why `WorldSlice` exists in the first place).

**Comment by bconlon1** [comment]
Might just PR a fix to Rubidium myself when I have the time.

**Comment by bconlon1** [comment]
also, relevant issue https://github.com/Asek3/Rubidium/issues/468

**Comment by bconlon1** [comment]
Opened a PR here instead of trying to find a workaround on Aether's end: https://github.com/Asek3/Rubidium/pull/475
