### ISSUE TITLE
Bug: Valkyrie flight has odd interactions with the jump buffer.

### ISSUE THREAD

**Issue by sunsetbear** [Gilded-Games/The-Aether#1209]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta

### Steps to Reproduce

Happens consistently.
1. Jump normally once.
2. Moments before landing, press and hold jump. This will trigger a second jump, since minecraft's jump has an input buffer.
3. Continue holding space. During your ascent, flight will trigger, causing you to land abruptly instead of continuing to jump or fly. 

### What You Expect To Happen

Flight would wait until the peak of the buffered jump's ascent to begin, like normal.

### What Actually Happened

Flight triggers as if the player had remained airborne the whole time.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Occurs on multiplayer only, might be desync.
