### ISSUE TITLE
incompatibility with better recipe books

### ISSUE THREAD

**Issue by RichPrune** [Gilded-Games/The-Aether#1211]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

45.0.49

### The Aether Version

1.19.4 1.0.0

### Is This Bug a Conflict With Another Mod?

better recipe book +brewing stands

### Crash Report (if applicable)

<script src="https://gist.github.com/RichPrune/0744f3046562ef61af50f6e697e1191b.js"></script>

### Steps to Reproduce

every time u use these two mods it crashes

### What You Expect To Happen

not crash

### What Actually Happened

crash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Make a report to the Oculus github and link it here once you have.

**Comment by bconlon1** [comment]
I think this crash happened because you were missing Architectury or Cloth Config. I could only reproduce it when those dependencies were missing.
