### ISSUE TITLE
Music Discs not affected by distance

### ISSUE THREAD

**Issue by BigPhobos** [Gilded-Games/The-Aether#1212]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0-beta.1

### Steps to Reproduce

Occurs Everytime
1. Place Jukebox
2. Play "Aether Tune" or "Ascending Dawn" Music Disc
3. Audio does not fall of with distance

### What You Expect To Happen

Vanilla music disc audio falls off with distance.

### What Actually Happened

Aether music disc audio does not fall off with distance.

### Additional Details

Usually caused by record.ogg files not being exported to mono.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ZolaKluke** [comment]
Dejavu of this issue?
https://github.com/The-Aether-Team/The-Aether/issues/70
