### ISSUE TITLE
Bug: Moa Spawn Eggs don't spawn Moa when used by a Dispenser.

### ISSUE THREAD

**Issue by mengzach** [Gilded-Games/The-Aether#1215]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

1.0.0 beta 1

### Steps to Reproduce

Every instance of activating a dispenser with Moa Spawn Egg inside

1. Dispenser with Moa spawn Egg inside.
2. Activate Dispenser with redstone signal.
3. The Spawn Egg shoots out of Dispenser like a Dropper

### What You Expect To Happen

Spawn the Moa depending on their color corresponding to their Egg.

### What Actually Happened

Activating the dispenser resulted in the Moa Spawn Egg to drop out like a Dropper and output the item.

### Additional Details

Tested on All Aether Spawn Eggs, and the only ones that gave this behavior were:

- Blue Moa Spawn Egg. 
- White Moa Spawn Egg.
- Black Moa Spawn Egg.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
These eggs only work as spawn eggs when used by creative players, there wouldn't be a way to make them work this way for dispensers.
