### ISSUE TITLE
Bug: Some mobs are not affected by the knockback enchantment when they die

### ISSUE THREAD

**Issue by Lolothepro** [Gilded-Games/The-Aether#1216]
### What Type of Bug Is This?

None

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0-beta.1-forge

### Steps to Reproduce

1. Kill a Vanilla mob with the Knockback enchantment
2. Kill an Aether mob with the Knockback enchantment

### What You Expect To Happen

\\

### What Actually Happened

https://user-images.githubusercontent.com/68275908/234287891-0d33448e-5db5-4f1c-a7a2-1b780f5c2be3.mp4

https://user-images.githubusercontent.com/68275908/234288328-e7bf33c3-4992-4c67-8d18-6d8f6d540cd0.mp4

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Mobs that have this issue:
- Swets
- Flying Cow
- Moa
- Phyg

Mobs that don't:
- Aerbunny
- Cockatrice
- Fire Minion
- Mimic
- Sentry
- Sheepuff
- Valkyrie
- Zephyr

Mobs that have this issue but inversed for some reason:
- Aerwhales
