### ISSUE TITLE
Bug: Slider boss stuck during multiplayer fight

### ISSUE THREAD

**Issue by RodrigoLopesDF** [Gilded-Games/The-Aether#1218]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0-beta.1-forge

### Is This Bug a Conflict With Another Mod?

No, only JEI installed

### Steps to Reproduce

1. Play in Multiplayer, at least 2 players
2. Fight the Slider
3. Have one of the players die to the boss (we respawned in the overworld, unsure if it is a factor)
4. The boss will hug the room corner and will likely get stuck, unless if a player attacks it

### What You Expect To Happen

The Boss to change player targets, as soon the other dies

### What Actually Happened

The boss gets stuck in the uppercorner of a room and get stuck, unless provoked. While stuck, it seems to constantly do it's dash sound between random intervals (video shows this)

### Additional Details

The whole thing was recorded:
https://drive.google.com/file/d/1ys0cYIVCWMn7gX8cEtu4ysqyhbj3Zi4f/view?usp=share_link (sorry about audio quality, i didn't intend to record my voice)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Seems to be reproduceable and not dependent on whether the player respawns in the overworld or Aether. This may have been a bug introduced by the switch from the goal system to the brain system for the Slider, I think the Slider isn't properly resetting its memory for what target it should be going after when the target has died or something.
