### ISSUE TITLE
Bug: Falling Slime <ount bugged

### ISSUE THREAD

**Issue by 2009XboxLiveKid** [Gilded-Games/The-Aether#1219]
### What Feature Types Apply to This Bug?

Entity, System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.47

### The Aether Version

1.19.4

### Steps to Reproduce

have one of the slimes jump on you, let it fall off the side, land in deep water
[REMOVED]

### What You Expect To Happen

Id expect the player to dismount the slime when it shrinks/despawns

### What Actually Happened

Shown in video, stuck in mounted position

### Additional Details

I was using a sound pack, there are other mods, but nothing that has to do with mounting

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Please post a video file and not a zip file.

**Comment by 2009XboxLiveKid** [comment]
Couldn't post the video as it was too big, the only way I could post it was
with a zip file that is the only thing within the zip file

**Comment by bconlon1** [comment]
No worries I've ended up being able to fix the issue anyways since this seemed to be a general issue with mounts.

**Comment by micrwvae** [comment]
unrelated to the issue but if u get into the same situation again
https://streamable.com/
might help
