### ISSUE TITLE
Bug: <Overworld Shovel mines aether grass, doesn't drop the block, the block then reappears>

### ISSUE THREAD

**Issue by iLikeGothMommys** [Gilded-Games/The-Aether#1221]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0

### Steps to Reproduce

Overworld tool debuff is set to True
1. Mine grass with a diamond shovel, untested on other tools.
2. Watch as it doesn't drop the block and then respawns the grass

### What You Expect To Happen

It drops the grass

### What Actually Happened

It drops nothing and respawns the block

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might be caused by #1226
