### ISSUE TITLE
Pickaxe false breaking

### ISSUE THREAD

**Issue by HenriqueLB2006** [Gilded-Games/The-Aether#1223]
I was mining with a zanite pickaxe at half durability and it just made a tool breaking sound, spread purple particles and broke about 4 blocks really fast as if it was in low durability. After that I was mining with a stone pickaxe and it happened again (I just don't remember if the particles were purple or gray this time). I'm not using only the Aether mod tho, I'm using it with Deep Aether Addon, JEI, Just Zoom, Xaero's Minimap, Apple Skin, and Starlight (besides necessaries like Curios API ofc). I think that's a bug, and even tho it does not affect me, I think I should aware you guys 👍

Here you can see when it happened for the first time, with the zanite pickaxe.
https://user-images.githubusercontent.com/125204556/234719382-8fe73c7b-1619-4993-a260-77a80f7d2822.mp4

**Comment by bconlon1** [comment]
Probably was a zanite accessory breaking, based on the description.
