### ISSUE TITLE
the sliders damage sound is bugged

### ISSUE THREAD

**Issue by SLIMEMASTER000** [Gilded-Games/The-Aether#1224]
### What Type of Bug Is This?

None

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta.1-forge

### Is This Bug a Conflict With Another Mod?

no

### Client Log

https://gist.github.com/SLIMEMASTER000/d42c18cfafe73f7731445588b9a16b23

### Crash Report (if applicable)

it dident crash

### Steps to Reproduce

beat the shit out of a cube

### What You Expect To Happen

it should play the damage sound whenever you hit it

### What Actually Happened

when you hit the slider the BWOM damage sound only plays when you wake it up
whenever you hit it after its awake it just makes the normal player damage sound

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SLIMEMASTER000** [comment]
ok i set the type to audio idk why it didnt work

**Comment by bconlon1** [comment]
The bwom sound is the awakening sound, not the damage sound. The damage sound is played just fine when attacking the slider.
