### ISSUE TITLE
Bug: <Overworld Tool Debuff doesn't work when enabled server-side, only client-side>

### ISSUE THREAD

**Issue by iLikeGothMommys** [Gilded-Games/The-Aether#1226]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta.1

### Steps to Reproduce

1. Enabled tool debuff on the server server config
2. You will notice that the tool debuff does nothing for users on the server
3. Enable tool debuff on the clients end
4. You will notice tool debuff now works on the server

### What You Expect To Happen

I expected that the tool debuff would be a server-side only config. Meaning when I enable the overworld tool debuff the users on my server will have debuffed overworld tools. 

### What Actually Happened

The tool debuff didn't work unless also enabled on the clients end.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This looks like it would come from a desync, but I cannot reproduce such a desync. It also doesn't sound at all like how the sided config system should work which is even weirder.

**Comment by bconlon1** [comment]
Nevermind, I have determined how to reproduce this.
