### ISSUE TITLE
Bug: Spawnproofing

### ISSUE THREAD

**Issue by MinecraftSteveGaming** [Gilded-Games/The-Aether#1227]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

None

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta.1

### Steps to Reproduce

How often this happens: Enough for it to happen at least once in an enclosed space after a few hours of gameplay
Step 1: Build house out of player made materials such as skyroot planks and holystone bricks, no naturally generated blocks
Step 2: place ambrosium torches inside player made structure until it's acceptably lit

### What You Expect To Happen

Player made house should be spawnproof, no mobs, hostile or passive, appear without warning in the player made structure

### What Actually Happened

Aerwhale appears inside of player made structure and gets stuck inside

### Additional Details

Outside of this example, giving the player more options to control where and when mobs spawn in the aether would only improve the experience and make it even more fun in my opinion.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Related to spawnproofing: I'm thinking more and more it might be good to allow spawnproofing methods for other hostiles like swets and aechor plants, but they may depend on how we adjust their spawning.
