### ISSUE TITLE
Bug: Moas cannot be dismounted when in water

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [Gilded-Games/The-Aether#1231]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

beta 1.0.0

### Steps to Reproduce

1. mount a moa
2. use up all of its jumps, allow it to fall into water (in my case I fell into the ocean in the overworld, dont ask)
3. observe how you are helplessly dragged under the water while your moa drowns

### What You Expect To Happen

I would be able to dismount the moa, allowing it an myself to float back to safety

### What Actually Happened

we both drowned :(

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Moa behavior in water in general could be improved a bit I think.

**Comment by bconlon1** [comment]
And for other mounts
