### ISSUE TITLE
Bug: Quicksoil accelerates boat turning speed and crashes the game

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1241]
### What Feature Types Apply to This Bug?

Block, Entity

### What Type of Bug Is This?

None

### Forge Version

45.0.47

### The Aether Version

1.19.4-1.0.0-beta.1

### Steps to Reproduce

Consistently crashes at high speed.
1. Dig a 3x3x2 hole.
2. Fill the bottom with quicksoil.
3. Place a boat inside.
4. Enter the boat and start turning left or right.

### What You Expect To Happen

I expect the boat to turn at normal speed.

### What Actually Happened

The quicksoil accelerated the boat's turning speed, visually "snapping" the player's neck after a few seconds of turning and crashing the player's game if sat in for too long.

https://user-images.githubusercontent.com/112828225/235173240-41f5259b-05fe-4012-8369-1e47cda4d6c0.mp4

### Additional Details

Discovered by PRISIM182.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by SLIMEMASTER000** [comment]
best glitch ever
