### ISSUE TITLE
Feature Request: 1.19.2 Support

### ISSUE THREAD

**Issue by SpaceBoyHmm** [Gilded-Games/The-Aether#1242]
A lot of mods don't support 1.19.4, and choose to support 1.19.2 instead. For example, the create mod doesn't have any support for it. If you look to curseforge, there are 142 pages of results for 1.19.4 mods, but 488 pages of results for 1.19.2 mods - about 3.4x the amount of mods support 1.19.2 than ones that support 1.19.4. I currently play on a modded server, and I would love to suggest the aether mod as an addition to the modpack, but I can't since we play on 1.19.2.

**Comment by bconlon1** [comment]
Planned already
