### ISSUE TITLE
Feature Request: Different Water Color in the Aether

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1262]
### What Feature Types Apply to This Request?

World-Gen

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Since Minecraft 1.13, there have been biome-specific water colors. The Aether currently uses the default water color, but since the Aether is its own dimension, and has a vastly different climate and materials than other biomes, it would make sense for it's water color to be different.
My personal suggestion would be the following:
`    "water_color": 5542568,`
`    "water_fog_color": 862261`
which looks like this:
![2023-04-29_16 04 12](https://user-images.githubusercontent.com/60141811/235322118-e9e6eb8c-2cc4-4cb2-bc2e-9534724c326c.png)

### Why Should It Be in the Mod?

So that the Aether can have consistency with how other biomes with climates different than most have different water colors.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We're probably not gonna be doing this in Aether 1, but it should be doable with datapack. However it could be a good suggestion for Aether 2 since the color is nice and might fit there.
