### ISSUE TITLE
Bug: Sheep can't eat aether grass

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1276]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.49

### The Aether Version

beta 1

### Steps to Reproduce

Every time
1. Bring vanilla sheep to grass
2. Notice how they eat
3. Bring sheep to aether grass
4. Notice they do not eat

### What You Expect To Happen

The sheep would be able to eat aether grass.

### What Actually Happened

Sheep were unable to eat aether grass and pathfinded to vanilla grass.

### Additional Details

https://streamable.com/025kr2
This test was done at 300 tick speed but shouldn't have changed the results.
This likely extends to all vanilla mobs but I didn't test that.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Sheep can only eat grass and sheepuffs can only eat aether grass because of how their ai works.
