### ISSUE TITLE
Bug: (Diamond ) Gloves lose durability for each enemy hit with the same sweeping attack

### ISSUE THREAD

**Issue by FloppaWithDrip** [Gilded-Games/The-Aether#1278]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0-beta-1

### Is This Bug a Conflict With Another Mod?

Probably not, other mods installed: Aether: Lost Content, Clumps, jei, Elevator, Corpse

### Steps to Reproduce

1. Wear Gloves (only tested with diamond gloves).
2. Hit enemys with a sweeping attack
3. Gloves lose durability very fast :(

### What You Expect To Happen

For each attack only use 1 durability on the gloves, just like on the sword

### What Actually Happened

Lose one durability for each enemy hit in the sweeping attack.

See video:

https://user-images.githubusercontent.com/82812405/235763698-0a0d1e29-7a9e-4fe9-a1ca-f9d22cd1adee.mp4

### Additional Details

Only tested in multiplayer

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Might need a mixin to fix.
