### ISSUE TITLE
Feature Request: Fabric Port

### ISSUE THREAD

**Issue by ENC4YP7ED** [Gilded-Games/The-Aether#1282]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Fabric Port / Support

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

I would like to have a Fabric Version of the Mod so that both Forge & Fabric Users can enjoy the Mod from the Original Authors.

### Why Should It Be in the Mod?

Its 2023.

Most Mods have both Forge and Fabric or Quilt 

### Does This Feature Improve Compatibility With Another Mod?

Idk depends

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We already have plans for a Fabric port post-release.

**Comment by SirMishaa** [comment]
Hello, 

I see this as completed in GitHub project

Is that mean t have the possibility to compile the project for Fabric ? 

Thanks

**Comment by OzPayn** [comment]
The issue was closed because it is already planned, not because it has been completed
