### ISSUE TITLE
Feature Request: Aether Planks Item Tag

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1287]
### Other Type

Tags/Addon-useable content

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

An item tag that can be used to craft Skyroot tools and sticks, so that addon mods can add new items that craft into these without needing to add new recipes for every single item each time they add something new.

### Why Should It Be in the Mod?

So that addons can more easily add alternatives to skyroot planks for crafting recipes

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by darksonic300** [comment]
This would help a ton for addon making.
