### ISSUE TITLE
"Duplicated" Curio slots

### ISSUE THREAD

**Issue by vrork** [Gilded-Games/The-Aether#1304]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Design

### Forge Version

45.0.50

### The Aether Version

1.0.0-beta.1

### Is This Bug a Conflict With Another Mod?

Curios API 5.1.5.3

### Steps to Reproduce

Always
1- Have both Curios API and Aether installed
2-Have 2 acessories (gloves for example)
3-You can equip both, one in the Curios acessory slot and other in the Ather Gloves slot

### What You Expect To Happen

Ather use/overwrite Curios Slots, allowing only one glove or other acessory at the same time.

### What Actually Happened

Aether is not using curios slots, its duplicating the slots, not using/overwritting or whatever is should do, letting me wear double the things (for example, 2 gloves)

### Additional Details

Word from on the discord report:

> bconlon — Today at 12:53 AM
> actually wait i just fully looked at the images i see whats going on here
> hmmmm
> this is a design problem i did not account for, report this to the issue tracker. i made it so accessories can work in other mods' curios slots as well but did not consider the fact that'd mean they can double up with ones other mods add 

![2023-05-06_01 11 53](https://user-images.githubusercontent.com/8473676/236599189-9537ab35-2aa3-478a-98dd-bb39107ddfc7.png)

![2023-05-06_01 11 40](https://user-images.githubusercontent.com/8473676/236599191-4ddd6e3f-0cec-446a-9cbf-986619a861f0.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I'll probably need to prevent the items from working in default curios slots by default so I can leave it up to modpack makers to setup compat and whether they want to disable the aether's accessory slots to use curios instead, etc.

**Comment by vrork** [comment]
I am not sure if it is true, but Curseforge seems to think Curious is a depency (disable it and it disable Aether), but if it is a depency, in theory everyone should have Curios API installed to use Aether.

**Comment by bconlon1** [comment]
Curios should be marked as an embedded dependency. However, Curseforge seems to be having bugs with that considering I don't even see it displayed on the site.

**Comment by vrork** [comment]
Its what i imagined. 
I was thinking here, Aether has all the slots that Curios has and more, what if you could talk with the Curios dev and see if something like "if Aether is installed, disable CuriosAPI slots and "redirect" to Aether slots" could be worked on? Because i at least didn't saw a way to disable CuriosAPI slots manually (nothing in their configs)
