### ISSUE TITLE
You can sleep in the Aether during Thunderstorms prior to Beating Sun Spirit

### ISSUE THREAD

**Issue by Icreamcritter** [Gilded-Games/The-Aether#1305]
### What Feature Types Apply to This Bug?

Block, System

### Other Type

Day/Night Cycle

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.49

### The Aether Version

1.19.4-1.0.0-beta.1

### Client Log

https://gist.github.com/Icreamcritter/7ed527ebe40357ac700e4aaa7692b35d

### Steps to Reproduce

Always 
1:Set weather to thunder
2:Click on a Bed
3:Sleep

### What You Expect To Happen

The game not letting you sleep until beating the Sun Spirit

### What Actually Happened

You can sleep, and upon waking up the Day Night Cycle is turned on

### Additional Details

These were the Mods used 
MouseTweaks-forge-mc1.19.4-2.24.jar
structure_gel-1.19.4-2.12.0.jar
aether-1.19.4-1.0.0-beta.1-forge.jar
jei-1.19.4-forge-13.1.0.9.jar
geckolib-forge-1.19.4-4.1.3.jar
deep_aether-1.19.4-1.0.2.jar
lost_aether_content-1.19.4-1.1.1.jar

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This doesn't actually change the eternal day status, the sun moves because its trying to reset back into position for eternal day.
