### ISSUE TITLE
Feature Request: Golden Aercloud renewability with frogs

### ISSUE THREAD

**Issue by CalXee** [Gilded-Games/The-Aether#1307]
### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Currently, I don't believe there is a way to get aerclouds renewably, and I personally believe that there should at least be a way (feel free to disagree with me). I just noticed that frogs eat swets just like other slimes, so how about adding aercloud renewability by making frogs killing swets have a custom loot table?

Here's what I'm thinking. Make it so the white warm frogs drop cold aercloud when eating any two swet types since the white frogs are good at cooling off themselves in real life. Make the other two frogs drop only multiple blue aerclouds when eating blue swets and no swet balls, and make them drop golden aerclouds when eating golden swets instead of glowstone.

### Why Should It Be in the Mod?

Personally I think it's kind of weird that aerclouds are not renewable. Maybe this is intended design but it just doesn't feel good considering golden and cold aerclouds are required to craft parachutes. It also prevents the player having to strip the aether of every cloud in sight, which would make the dimension look a little less pretty over time. Bringing frogs to the aether is also a relatively late game activity, so it theoretically shouldn't change early game balance that much.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Cinex20** [comment]
Actually, they are renewable. Cold aerclouds drop from zephyrs, and those can be frozen in the freezer to produce blue aerclouds. Pretty sure you can't obtain gold aerclouds, though. Maybe it could be done through enchanting?

**Comment by bconlon1** [comment]
Blue Aerclouds are also renewable from Blue Swets.

**Comment by bconlon1** [comment]
We can discuss the design of whether enchanting golden aerclouds would be a good feature or not, it really depends on whether it might mess with their balance or not.

**Comment by CalXee** [comment]
I've updated the ticket to make a few corrections you guys have pointed out
