### ISSUE TITLE
Feature Request: A way for addons to change the color of crystal and golden oak leaf particles

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1323]
### What Feature Types Apply to This Request?

Block, System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Some sort of way for addons to be able to easily change the color of golden oak and crystal leaf particles

### Why Should It Be in the Mod?

So that addons can more easily alter the appearance of the mod's leaves and have consistent colors for the particles

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
You should be able to easily do this with a mixin, just make sure to leave it configurable in case of conflicts.

**Comment by Zepalesque** [comment]
oh, right, I forgot mixins even existed, good idea!
