### ISSUE TITLE
Bug: Jade compatibility for mimics doesn't work as intended in multiplayer

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1328]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Mod compat

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.57

### The Aether Version

1.19.4-1.0.0-beta.2

### Is This Bug a Conflict With Another Mod?

Jade

### Steps to Reproduce

Only happens in multiplayer.
1. Install the Jade mod.
2. Locate a bronze or silver dungeon in the Aether.
3. Look at chests inside it.

### What You Expect To Happen

I expect to be unable to tell the difference between normal chests and mimics without the debug menu.

### What Actually Happened

Normal chests display with just their names. Mimics display with their names and a message saying "Inventory isn't generated". This makes it very easy to spot mimics.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
It seems this display on servers depends on the server also having Jade installed.
