### ISSUE TITLE
Bug: Aerogel does not cull against its slabs

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#1351]
### What Feature Types Apply to This Bug?

Art, Block

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.47

### The Aether Version

1.0.0-beta.2

### Steps to Reproduce

# Place a block of aerogel
# Place an aerogel double slab beside it or a single or double slab on top of or below it
# Observe
# Compare with two slabs next to each other, or two normal aerogel blocks next to each other

### What You Expect To Happen

The interior faces would be culled to give the appearance of continuity.

### What Actually Happened

The interior faces are still completely visible.

### Additional Details

![2023-05-13_15 47 26](https://github.com/The-Aether-Team/The-Aether/assets/52297970/f5bf0c3e-586a-4c14-ac76-ee738ee84380)
![2023-05-13_15 47 28](https://github.com/The-Aether-Team/The-Aether/assets/52297970/df63676f-5540-468e-8c79-225c761d985e)
![2023-05-13_15 47 37](https://github.com/The-Aether-Team/The-Aether/assets/52297970/03352731-368b-405d-8ded-fe5a29545f3b)
![2023-05-13_15 47 50](https://github.com/The-Aether-Team/The-Aether/assets/52297970/426a29e9-a7bd-4578-8dd2-cf1e87b68f9b)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Not going to fix
