### ISSUE TITLE
Bug: Slider boss animation issue

### ISSUE THREAD

**Issue by beansthethird** [Gilded-Games/The-Aether#1369]
### What Feature Types Apply to This Bug?

Art, Entity

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.57

### The Aether Version

Third Beta 1.19.4

### Steps to Reproduce

Damage the slider boss with a pickaxe

### What You Expect To Happen

When you hit the slider, it is supposed to remain as it is and not be tilted or be moved by your hit

### What Actually Happened

Sometimes when I damage the slider, its model gets crooked

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Steve982950** [comment]
Can you add screenshots/videos?

**Comment by bconlon1** [comment]
The slider model has a tilting animation when it is hit, that is intended.
