### ISSUE TITLE
Feature Request: Improve High and chinchilla recipe

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1398]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To make the Music Disc chinchilla you have to put strad into to the Altar and put it again in the Altar to get High which just doesn't make much sense. It would be way better if you put Aether Tune in the Altar to get High and put Ascending Dawn in the Altar to get chinchilla.

### Why Should It Be in the Mod?

The current recipes are really strange. Like why strad? It doesn't have any correlation with the Aether

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
The recipe is staying the way it is, it is an easter egg, it is not meant to have an obvious recipe.
