### ISSUE TITLE
Bug: Missing Slab in the Valk Temple

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1399]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.49

### The Aether Version

1.0.0 Beta 3

### Steps to Reproduce

Go to the Stairs in the Valk Temple

### What You Expect To Happen

That there wasn't a slab missing

### What Actually Happened

There was a slab missing

### Additional Details

![missing_slab](https://github.com/The-Aether-Team/The-Aether/assets/81527321/03717f4e-cd81-4748-b328-b2071e6cbf10)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Beta-accurate

**Comment by Builderdog841** [comment]
not really as top slabs didn't exist in beta but they are in the structure. There is only one missing spot

**Comment by bconlon1** [comment]
In the future please elaborate that in the issue report.
