### ISSUE TITLE
Feature Request: Make Blue Aerclouds cause particles to bounce

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1402]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

For Blue Aerclouds to cause particles to bounce, like it did in older versions (tested in b1.7.3)

In versions with water particles coming from the clouds, bouncing on them caused a spray of water to launch upwards, which was fun

NOTE:
this might not be possible in newer Minecraft versions, I'm not sure. If it is, it would be a fun little addition from older versions of the mod

Here is a video showcasing it in beta 1.7.3 (I would do a version with the water particles, but I don't have them set up and I can't find any recent tutorials):

https://github.com/The-Aether-Team/The-Aether/assets/60141811/34beef10-58cb-4056-8369-1c9a9da68eb3

### Why Should It Be in the Mod?

It was in the original versions of the mod, including b1.7.3, along with _very_ likely 1.2.5, since it is still in the Aether II's 1.7.10 version which would have likely been carried over from 1.2.5

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I don't think minecraft applies physics to all particles in the same way it used to for this to work.

**Comment by Zepalesque** [comment]
idea for this, idk if I should reopen it or what so I'll just not just in case, but maybe a new particle type could be made for this, which starts with upward motion or something
