### ISSUE TITLE
Bug: Repulsion Shield breaks Valk Flight

### ISSUE THREAD

**Issue by M-W-K** [Gilded-Games/The-Aether#1411]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.49

### The Aether Version

1.0.0-beta3

### Steps to Reproduce

1. Equip full Valkyrie armor set
2. Equip shield of repulsion
3. Spawn a skeleton and get shot at
4. Try to fly shortly after the skeleton arrow is bounced by the shield

### What You Expect To Happen

Valk flight would still work

### What Actually Happened

Valk flight stops working for a short time after activation of the shield

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The player capability is having trouble syncing things when both the overlay and flight are being handled at once.
