### ISSUE TITLE
Bug: Incompatible with Better F3

### ISSUE THREAD

**Issue by 48004800** [Gilded-Games/The-Aether#1417]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Compatibility

### Forge Version

1.19.4-45.0.63

### The Aether Version

 1.19.4-1.0.0-beta.3-forge

### Is This Bug a Conflict With Another Mod?

BetterF3 Forge v6.0.1 (1.19.4)

### Steps to Reproduce

Use with Better F3 and press F3.

### What You Expect To Happen

The F3 interface appears.

### What Actually Happened

The F3 interface did not appear.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by 48004800** [comment]
I also reported this issue to the author of Better F3.
Corresponding version of better F3mod link:

https://www.curseforge.com/minecraft/mc-mods/betterf3/files/4513171

**Comment by bconlon1** [comment]
Please add the log and the link to the other issue report in the future.
https://github.com/cominixo/BetterF3/issues/147
https://gist.github.com/bconlon1/bd41a9e2bead7cab82be8b756775c943

**Comment by bconlon1** [comment]
From the BetterF3 issue report it sounds like this is not isolated to an Aether incompatibility. This can be reopened if its determined that there is something we need to fix on our end.
