### ISSUE TITLE
Feature Request: Baby Aether mobs spawning with groups of those mobs

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1434]
### What Feature Types Apply to This Request?

Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Flying around the Aether, I noticed that there were no baby Aether mobs anywhere.
I don't remember the _exact_ version, but I remember at some point Mojang made baby animals spawn in groups of those animals, because it was a feature in Bedrock edition that they wanted to bring over to Java edition.

### Why Should It Be in the Mod?

To add parity with vanilla Minecraft, which has baby mobs spawning with groups of those animals

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I think they do, it might just be incredibly rare; it seems incredibly rare for vanilla mobs too.
