### ISSUE TITLE
Bug: Incubator Gui is very glitchy

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#144]

**Comment by ZolaKluke** [comment]
Bug also affects the Freezer GUI
![image](https://user-images.githubusercontent.com/6497775/148002271-01fa9724-eaeb-4631-8104-cc2e850b8712.png)
![image](https://user-images.githubusercontent.com/6497775/148002187-e876d151-eea1-4631-b720-e30982585390.png)

**Comment by bconlon1** [comment]
> Bug also affects the Freezer GUI ![image](https://user-images.githubusercontent.com/6497775/148002271-01fa9724-eaeb-4631-8104-cc2e850b8712.png) ![image](https://user-images.githubusercontent.com/6497775/148002187-e876d151-eea1-4631-b720-e30982585390.png)

The issue you're mentioning is different from this one. This issue is from the incubator GUI just being incomplete, while the bugs with the other GUIs just have some bugs from porting over to 1.18 and changes to how textures are bound.
