### ISSUE TITLE
Feature Request: Config option to make whichever (inventory/accessories screen) was last closed open when pressing E

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1452]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A config to make it so that when you press E it opens whichever (inventory/accessories screen) you had open last.

Alternate explanation:

A configuration option so that when you press E, if you closed the accessories screen last, and _not_ the main inventory, it will reopen the accessories screen. If the previous open was the base minecraft inventory, then it would open the default minecraft inventory.

I'm not sure whether or not it would make sense to do it in creative mode though, personally I would like it but I can see why others wouldn't like it so much.

### Why Should It Be in the Mod?

For a couple of reasons:

1. The original mod always had the accessories screen by default
2. It's somewhat tedious to open the accessories screen over and over

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
`I` lets you open the accessories screen so I don't think this is too necessary.

**Comment by Zepalesque** [comment]
oh it does? I didn't know that lol, that could've been useful to know, alright then!
