### ISSUE TITLE
Feature Request: Make the slider only deal 1 durability damage to pickaxes

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1459]
### What Feature Types Apply to This Request?

Entity, Item

### Is This an Enhancement to a Preexisting Feature?

- [x] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Right now, when attacking the slider, it takes away 2 or 3 durability from the pickaxe. This makes it so that you need to bring a large amount of pickaxes to fight the slider, which can be inconvenient, especially if you have low inventory space. What _I_ think would be a bit better is if it only did _1_ durability damage to pickaxes, similar to when you mine a block.

### Why Should It Be in the Mod?

So that you don't need to bring an inconveniently large amount of pickaxes with you every time you want to fight the Slider

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Part of this is just how vanilla handles using tools to attack enemies, however this has made me realize we do have an extra damage durability call in the Slider code for tools which doesn't have to be there, so I can reduce the durability damage from 3 to 2 at least.
