### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by KeeganBWebb** [Gilded-Games/The-Aether#1461]
### What Feature Types Apply to This Bug?

Config, System

### What Type of Bug Is This?

Crash

### Forge Version

45.0.64

### The Aether Version

1.19.4-1.0.0-beta.4-forge.jar

### Is This Bug a Conflict With Another Mod?

This might be a conflict with another mod but im not sure which, refer to crash report for list.

### Crash Report (if applicable)

<script src="https://gist.github.com/Bubby0304/505a83464e61e320d609be7c25ea6741.js"></script>

### Steps to Reproduce

The game just crashes on launch and mentions something about slim glove texture. I figured I would share the crash report and hopefully this could be fixed/explained even though the mod list is quite extensive (although it might not even be related to a mod).

### What You Expect To Happen

I think something related to the removal/change of the glove textures tied to slim is the issue here.

### What Actually Happened

Just crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The gist you linked is not valid, please provide a valid gist link.

**Comment by bconlon1** [comment]
Nevermind, figured out a way to view it.

**Comment by bconlon1** [comment]
Yeah this is an issue with Upgraded Netherite: Aetherite, please report it to their issue tracker: https://legacy.curseforge.com/minecraft/mc-mods/upgraded-netherite-aetherite/issues. They will have to update their code to be compatible with beta.4.
