### ISSUE TITLE
Bug: Setting the "Debuff non-Aether tools" config to false creates strange behavior

### ISSUE THREAD

**Issue by Firedude0** [Gilded-Games/The-Aether#1467]
### What Feature Types Apply to This Bug?

Block, Config

### What Type of Bug Is This?

Design

### Forge Version

45.0.66

### The Aether Version

beta.4

### Steps to Reproduce

If you set the "Debuff non-Aether tools" config in a world to false and then enter the world, some strange behaviors occur:

- All Overworld tools except axes are effective against Aether blocks, but axes are not
- In a test in singleplayer, I tested both a stone pickaxe and a diamond pickaxe enchanted with efficiency V against holystone, and they had the same mining speed
- In another test, this time on a server, an efficiency IV diamond pickaxe was able to instamine all Aether stones without even playing the block breaking sound

### What You Expect To Happen

All overworld tools are made to work with regular speeds on Aether blocks

### What Actually Happened

They exhibit strange, inconsistent behaviors

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Cannot reproduce.
