### ISSUE TITLE
Feature Request: Portals only spawn on islands

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1471]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

For the Aether Portals to only spawn on the islands. I think this was a thing in GoTV, and I'd like to see it here too (I really do _not_ like spawning in places where it's hard to get to the islands lol)
I can see why some people might not like it though so maybe it could be a configuration option or something? I think it would be really helpful for making the mod more fun though.

### Why Should It Be in the Mod?

So that it's not as tedious and painful to get to the islands when you first enter the Aether, and by extension, to make the mod more fun (especially in the beginning)

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This is hard to do with the portal system, since the portal can't be generated on terrain if there is nothing there in the corresponding coordinates in the Aether from the Overworld.
