### ISSUE TITLE
Feature Request: Make the Slider stop making ambient sounds when awake

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1478]
### What Feature Types Apply to This Request?

Audio, Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

For the slider to stop making its cave noise ambient sounds when it's awake

### Why Should It Be in the Mod?

It's a little strange, and a bit annoying to hear cave sounds continue through the bossfight
in addition, they're supposed to be there to make the Slider sound more ominous, and once the Slider is awake they no longer serve that purpose

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This is consistent with beta implementation.
