### ISSUE TITLE
Feature: 1.20.1 Update

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#1490]
Wiki Page: https://minecraft.fandom.com/wiki/Java_Edition_1.20

Primer: https://gist.github.com/ChampionAsh5357/cf818acc53ffea6f4387fe28c2977d56
- Have an update.json with everything on it on this version. update mods.toml accordingly.

**Comment by Steve982950** [comment]
can u update to 1.20.1 aswell?

**Comment by MrKashew** [comment]
very excited for this - curious if this will be prioritized > #1498 since its backport

**Comment by Cinex20** [comment]
> very excited for this - curious if this will be prioritized > #1498 since its backport

Nope, current plan is 1.19.4 full release => 1.19.2 backport ==> Fabric port ==> 1.20

**Comment by bconlon1** [comment]
We have no specific planned order.

@Cinex20 please do not share false information to users.

**Comment by MrKashew** [comment]
> > very excited for this - curious if this will be prioritized > #1498 since its backport
> 
> Nope, current plan is 1.19.4 full release => 1.19.2 backport ==> Fabric port ==> 1.20

I would selfishly had hoped supporting forwards and shifting onward development to current version would be more intuitive with backports being afterthought @bconlon1 I see, appreciate what the team is doing and know it will take time for the devs as they are doing this electively, many thanks for bringing this mod back to the community
