### ISSUE TITLE
Bug: Book of Lore Bugs

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1511]
### What Type of Bug Is This?

Design

### Forge Version

45.0.49

### The Aether Version

1.0.0 Beta 4

### Steps to Reproduce

Crafting Table isn't written with upper case letters in the Skyroot Log Entry
Skyroot Wood doesn't have an Entry
Stripped Skyroot Wood has the exact same Entry as Stripped Skyroot Logs
That's all I have found for now

### What You Expect To Happen

To get the correct entries

### What Actually Happened

I didn't get the correct entries

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Builderdog841** [comment]
Found another one: In the Skyroot Sapling Entry Bonemeal is written as Bone Meal

**Comment by bconlon1** [comment]
> Found another one: In the Skyroot Sapling Entry Bonemeal is written as Bone Meal

Bone Meal is the correct spelling.
