### ISSUE TITLE
Bug: Shield of repulsion rapid durability loss

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1526]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

None

### Forge Version

45.1.0

### The Aether Version

1.19.4-1.0.0-beta.4

### Steps to Reproduce

Reproducible with relative ease.
1. Equip the shield of repulsion.
2. Shoot one arrow straight up to make it keep bouncing on your head.

### What You Expect To Happen

I expect the arrow to fall off eventually.

### What Actually Happened

The arrow will keep bouncing indefinitely, rapidly decreasing the shield's durability.

https://github.com/The-Aether-Team/The-Aether/assets/112828225/a9c8d969-879d-4bf2-aeb9-cae23c2f62dd

### Additional Details

Another bug from the ancient vaults :P

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I should check if the projectile source is the player during deflection.
