### ISSUE TITLE
Feature Request: Compatibility with End Remastered

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Gilded-Games/The-Aether#1530]
### What Feature Types Apply to This Request?

Item

### Other Type

Loot Table

### Is This an Enhancement to a Preexisting Feature?

- [x] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

When End Remastered is installed, add a chance for 3 unique eyes of ender related to each of the Aether dungeons to appear in their respective boss loot chests.

### Why Should It Be in the Mod?

It would allow more viable paths to the End dimension along the slower progression End Remastered introduces, and would appropriately mirror the 3 eyes that could be found in the Nether within fortresses, bastion remnants, and from the Wither. Additionally, it would be nice to know that the time you spend in the Aether isn't exclusively delaying how soon you can get some Elytra, since the Aether is where you'd want them the most.

### Does This Feature Improve Compatibility With Another Mod?

End Remastered R5.2.2

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Cinex20** [comment]
That sounds like something that should be done on the other mod's end.

**Comment by bconlon1** [comment]
This should probably be handled by an addon or End Remastered itself.
