### ISSUE TITLE
Feature Request: Berry Bush Parity/Consistency config

### ISSUE THREAD

**Issue by CrystalZink** [Gilded-Games/The-Aether#1543]
### What Feature Types Apply to This Request?

Block, Config

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Adding a config to make Aether's blue berry bushes consistent with how Vanilla's sweet berry bushes work.
As in, the final growth state with the berries being able to be walked through (as opposed to being stood on), and right clicking on the bushes giving you berries instead of flat-out breaking them.

### Why Should It Be in the Mod?

Vanilla Parity/Consistency, and for any resource pack authors who wish to make the berry bushes consistent with sweet berries, or general preference lul

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I think trying to adapt the current behavior to be configurable and allow for Berry Bushes to act like Sweet Berries would be more of a hassle than it is worth, considering the code for how their behavior is handled is pretty different. Likely won't be implementing this.
