### ISSUE TITLE
Feature Request: Make gold dungeons use Surface Rules for their surface/grass blocks

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1549]
### What Feature Types Apply to This Request?

Block, System, World-Gen

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

For the golden dungeons to use the surface rules of the current biome to choose their surface blocks, rather than always using Aether Grass Blocks

### Why Should It Be in the Mod?

So that addons that add new biomes with alternate surface rulea can still spawn the gold dungeon in their biome without it looking too out-of-place (since I’m pretty sure it’s supposed to at least *partially* blend in with the environment, just look a *little* bit suspicious, and if it has an entire different type of grass block then it would be pretty obvious that it’s a generated structure for new players)

### Does This Feature Improve Compatibility With Another Mod?

Addons that add new biomes with alternate surface rules

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Doesn't seem possible with how deep surface rules are in the worldgen code.
