### ISSUE TITLE
Bug: Floating blocks sometimes jitter when carrying entities.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#155]
Maybe someone else can figure this out since I can't.

**Comment by Kelvin285** [comment]
Added a bit of code to the floating block renderer to sync the client and server positions for entities riding on the blocks and it fixed the issue!

**Comment by Kelvin285** [comment]
so it's not as bad as it was before, but the jitter is still there.
When I moved the code to my GitHub fork it came back.  It works every once in a while though so that's a plus!

**Comment by bconlon1** [comment]
im tempted to just remove this behavior if it can't be made to work well by release.

**Comment by bconlon1** [comment]
Planning to remove in the port to 1.18.

**Comment by bconlon1** [comment]
Apparently they can now also get players stuck while floating. Setting noGravity is a bad idea.

**Comment by bconlon1** [comment]
Floating blocks seem to need a complete refactor as they seem to be broken.
