### ISSUE TITLE
Bug: When a player runs with an Aerbunny on his head, the Aerbunny's eyes are not synchronized with the Hitbox.

### ISSUE THREAD

**Issue by Lolothepro** [Gilded-Games/The-Aether#1558]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

None

### Forge Version

45.1.2

### The Aether Version

1.0.0 beta 5

### Steps to Reproduce

Put an Aerbunny on your head
Press F3+B
See

### What You Expect To Happen

Hitbox display synchronized with eyes

### What Actually Happened

https://github.com/The-Aether-Team/The-Aether/assets/68275908/ddef0082-4109-40d4-96e5-4bf8d61ded80

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Can't consistently reproduce, doesn't seem worth fixing anyways.
