### ISSUE TITLE
Entities riding on flying blocks continue floating upwards even after the floating block is destroyed

### ISSUE THREAD

**Issue by Kelvin285** [Gilded-Games/The-Aether#156]
Test:
 Ride on a floating block while in creative mode and wait for it to hit the height limit.  There's a chance that when the block breaks you will still be floating upwards.
Even after flying in creative mode or switching to survival mode you will continue to move up.

**Comment by bconlon1** [comment]
I'll have to remove the setGravity function probably.

**Comment by bconlon1** [comment]
Okay removing setNoGravity causes more bugginess so I guess I'm gonna have to spend some time looking into this again later on.

**Comment by Kelvin285** [comment]
removing setNoGravity and noPhysics fixed the issue!
Also fixed the issue where the screen shakes when you're going up on a floating block.
