### ISSUE TITLE
Bug: Quickload causes World Corruption

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1567]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.1.0

### The Aether Version

1.0.0 Beta 5

### Steps to Reproduce

1. Open an instance of Minecraft and have Quickload enabled
2. Then open another instance
3. Enter the world on one instance
4. See how it completely corrupted

### What You Expect To Happen

That Quickload would lock loading a world in the main menu to one instance like minecraft locks a world for one instance

### What Actually Happened

The world got corrupted

### Additional Details

![corruption](https://github.com/The-Aether-Team/The-Aether/assets/81527321/5bbc38e4-bd2a-4b00-aaba-1d729e35463f)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Builderdog841** [comment]
You can enter the world on 2 different instances at the same time but the world only corrupts once you enter and relog it
![relogged](https://github.com/The-Aether-Team/The-Aether/assets/81527321/59a614af-c2de-4a0c-be9a-ea6874a180e2)
![relogged2](https://github.com/The-Aether-Team/The-Aether/assets/81527321/f654b2c6-a46b-412c-bc0a-3d7de8f9488c)
these to screenshots are happening at the same time in the same world on 2 differntent instances of minecraft in one I relogged in the other one I didn't

**Comment by bconlon1** [comment]
Weird, Minecraft should be automatically locking worlds if you have them open in an instance.
