### ISSUE TITLE
Feature Request: Book of Lore grammar and consistency check

### ISSUE THREAD

**Issue by Zcaercat** [Gilded-Games/The-Aether#1577]
### What Feature Types Apply to This Request?

Item, Other (Please Describe)

### Other Type

Grammar and Consistency

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

(Since grammar and consistency in Book of Lore entries isn't really a bug, I'm using the Request template)

Several of the Book of Lore entries have capitalization errors or capitalize item or block names inconsistently. There are also several entries with comma splicing and awkward syntax. 

Additionally, Book of Lore entries for Netherite Gloves, Aether Farmland, and Aether Dirt Path are missing and the Golden Gloves entry refers to the Gold Armor set as both "Golden Armor set" and "Gold Armor set". 

For example, the Gravitite Axe entry states: `"lore.item.aether.gravitite_axe": "Part of Aether's best tool tier, this Axe not only can make wood blocks float, but it can mine Golden Oak logs for Golden Amber!",`. Axe is a common noun and would not normally be capitalized. 
![2023-07-09_20 22 50](https://github.com/The-Aether-Team/The-Aether/assets/139074711/8fa46530-32b0-44fd-9e86-3baef0b3a2b7)
![AethDirtPath](https://github.com/The-Aether-Team/The-Aether/assets/139074711/02e86332-0b1e-4cf1-861e-679aea7e62d5)
![AethFarmland](https://github.com/The-Aether-Team/The-Aether/assets/139074711/a95cedc0-7a16-4643-a519-9f78b70afc9a)
![GravAxe](https://github.com/The-Aether-Team/The-Aether/assets/139074711/c51b156d-7ec7-49a6-883b-4c42d27ced67)
![NethGloves](https://github.com/The-Aether-Team/The-Aether/assets/139074711/2640a835-3e9f-4ca3-8887-b33723875d8a)

### Why Should It Be in the Mod?

The comma splices can be left alone as a stylistic choice, but making capitalization consistent would add some polish and cleaning up some grammar and syntax would make reading easier. 

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Zcaercat** [comment]
Note: The Cloud Staff refers to the summoned entities as "Cloud Sentries" but the source code refers to them as "Cloud Minion."

**Comment by bconlon1** [comment]
Farmland and Dirt Path don't have entries due to being unobtainable blocks.

**Comment by bconlon1** [comment]
Axe being capitalized is consistent with vanilla capitalization choices in Advancements

**Comment by bconlon1** [comment]
> Farmland and Dirt Path don't have entries due to being unobtainable blocks.

Actually we should probably just add lore entries anyways, the Chest Mimic is unobtainable yet has a lore entry.
