### ISSUE TITLE
Feature Request: Make Aerclouds mineable faster with Shovels rather than Hoes

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1579]
### What Feature Types Apply to This Request?

Block, Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

For Aerclouds to mineable faster with shovels rather than hoes

### Why Should It Be in the Mod?

Hoes don't really seem like they would realistically be able to mine a cloud fast, they would just slice it up. Shovels on the other hand seem like they definitely could, since they could scoop up the aercloud, almost like a spoon

Additionally, I had no idea what tool was used for them before (I thought it could have been none), but the first one that came to mind for in the event it *wasn't* that no tool worked were shovels, as they seem fairly intuitive to be the tool to mine aerclouds (in my opinion, of course)

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Cinex20** [comment]
I disagree, Mojang made the hoe into a tool for miscellaneous soft blocks. Aerclouds fit perfectly here.

**Comment by bconlon1** [comment]
Not planning to change.
