### ISSUE TITLE
Bug: Valkyrie Queen Block Breaking Crash Outside of Silver Dungeon

### ISSUE THREAD

**Issue by sm644me** [Gilded-Games/The-Aether#1588]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

45.1.0

### The Aether Version

1.0.0-beta.5.1

### Crash Report (if applicable)

https://gist.github.com/sm644me/165f1e97368908b868dcfb9f1cd24e26

### Steps to Reproduce

1. Summon a Valkyrie Queen outside of a Silver Dungeon. I've tested this in the Overworld.
2. Give her 10 victory medals and begin the fight.
3. Hide behind blocks, like a hilly slope or a tree.
4. When she attempts to break blocks to reach the player, the game freezes and then crashes.

### What You Expect To Happen

I expect her to break the blocks around her.

### What Actually Happened

The game froze and crashed. Reentering the world causes this to repeat indefinitely.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Happens with Slider too.
