### ISSUE TITLE
Bug: Music Discs High and chinchilla don't work

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1592]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Design

### Forge Version

45.1.0

### The Aether Version

1.0.0 Beta 5.1

### Steps to Reproduce

Put a Sepia or a Super Music Disc in a Jukebox and see how no music plays

### What You Expect To Happen

To hear chinchilla and high

### What Actually Happened

The Music Disc were silent

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
OGG file compression apparently broke something with how these discs audio files get run in Minecraft, despite the fact they run fine in audio software.
