### ISSUE TITLE
Bug: Swets have odd behavior on Slime Blocks

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#1603]
### What Feature Types Apply to This Bug?

Block, Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.1.0

### The Aether Version

beta.5.1

### Steps to Reproduce

Step 1: Place a Slime Block
Step 2: Spawn a Swet on that Slime Block
Step 3: Observe

### What You Expect To Happen

The Swet would be able to properly navigate on the Slime Block

### What Actually Happened

The Swet got stuck on the block, seemingly trying to infinitely jump

### Additional Details

Video of the bug:

https://github.com/The-Aether-Team/The-Aether/assets/60141811/d7c11f08-0e2b-447f-9207-9341801438d0

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Can you get a video of this without any other mods.

**Comment by Zepalesque** [comment]
alright, here (sorry about the short video length, my recording software refused to make it under 10 MB otherwise lol):

https://github.com/The-Aether-Team/The-Aether/assets/60141811/8b66879c-ff7c-4e7f-a704-2732c6c9c475

another thing I found out right after making the issue report is that this *also* affects vanilla slimes, not sure if that affects whether or not it will get fixed but I thought I'd note that either way

**Comment by bconlon1** [comment]
Could you get a video of it affecting vanilla slimes too?

**Comment by Zepalesque** [comment]
https://github.com/The-Aether-Team/The-Aether/assets/60141811/b9a1263a-60f5-43e7-a50e-a1a7b8509870

**Comment by bconlon1** [comment]
While this is a vanilla bug, I think I'll still look into the animation speed of the Swet during this.

**Comment by bconlon1** [comment]
Okay apparently this is something I already fixed in my cleanup branch

**Comment by bconlon1** [comment]
Reopening so it can be closed by the merge of the branch.
