### ISSUE TITLE
Bug: Unescable Prisons using Icestone and Water

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1605]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Design

### Forge Version

45.1.0

### The Aether Version

1.0.0 Beta 5.1

### Steps to Reproduce

1. Get inside the ice generated by icestone in a pool of water
2. Try to get out

### What You Expect To Happen

To be able to get out

### What Actually Happened

I wasn't able to get out

### Additional Details

https://github.com/The-Aether-Team/The-Aether/assets/81527321/ef67156e-ce72-4573-b04b-6d7584964c2b

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Since Icestone freezing is partially driven by game events, I may be able to set a delay for freezing thats triggered when a player breaks an ice block (or any freezing result block).
