### ISSUE TITLE
Feature Request: Make Aether Structure Generation Height data-driven

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1633]
### What Feature Types Apply to This Request?

World-Gen

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

It would be a nice tool for Add-On Creators especially for the one sthat have a new world gen

### Why Should It Be in the Mod?

I have a more 1.18 Style Worldgen in my Add-On and it would be nice if I could change the generation Height of Structures like Large Aerclouds and Dungeons to better fit the Worldgen without having to make a new structure

### Does This Feature Improve Compatibility With Another Mod?

Ancient Aether

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Seems like it might be doable with the structure codecs.
