### ISSUE TITLE
Bug: Riptide does not temporarily disable the invis cape

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1647]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.1.4

### The Aether Version

1.19.4-1.0.0-beta.5.1

### Steps to Reproduce

Reproducible consistently.
1. Have the PVP invis cape balance enabled in the server config.
2. Equip the invis cape.
3. Use a trident with the riptide enchantment.

### What You Expect To Happen

I expect my character to be revealed briefly.

### What Actually Happened

My character stays cloaked unless the riptide hits a mob.

### Additional Details

Considering that using a rocket disables the invis cape, a riptide trident should probably do it too.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
It's not intentional that rockets disable the invisibility 🤔 I wonder why its doing that.
