### ISSUE TITLE
Bug: Cockatrices spawning in full light

### ISSUE THREAD

**Issue by Coach-mdl** [Gilded-Games/The-Aether#169]
Cockatrices appear to be spawning in any light level. Furthermore, they don't seem to de-aggro unless if they can't get to you.

I also haven't seen any Aechor plants yet, but I haven't been far from my house.

**Comment by bconlon1** [comment]
This might be fixed idk I haven't checked yet.

**Comment by bconlon1** [comment]
This still occurs, however seems to be caused by some issues with the Eternal Day system not making the Aether be considered day when its night in the overworld.

**Comment by Coach-mdl** [comment]
Yeah. Since it looks like it's just a daytime sky overlaid on top the normal. You get a similar issue with shaders where you can see past the Aether's skybox and see what time it actually is. Is it not possible to make time stop in just one dimension?
