### ISSUE TITLE
Bug: breaks betterf3 when used with the aether beta 6 build for 1.19.2 

### ISSUE THREAD

**Issue by RexkUr** [Gilded-Games/The-Aether#1693]
### What Type of Bug Is This?

Compatibility

### Forge Version

43.2.23

### The Aether Version

1.0.0 beta 6 1.19.2

### Is This Bug a Conflict With Another Mod?

BetterF3 version: 4.0.0 1.19.2

### Client Log

https://gist.github.com/RexkUr/114fb30358af3097936df5556717889a

### Steps to Reproduce

1. Download BetterF3 along with its dependencies and the latest wip build for 1.19.2 by bconlon
2. open minecraft and make a world
3. open F3

### What You Expect To Happen

showing the debug screen provided by the betterf3 mod

### What Actually Happened

debug screen didnt show 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Unfortunately seems to be the same error as this, although with different effects in 1.19.2. This is not fixable on our end.
- https://github.com/The-Aether-Team/The-Aether/issues/1417
- https://github.com/cominixo/BetterF3/issues/147
