### ISSUE TITLE
Bug: You can't use Aether Flowers to craft Dye

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1697]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Design

### Forge Version

45.1.0

### The Aether Version

1.0.0 Beta 6.1

### Steps to Reproduce

Try to use a White or Purple Flower to craft Dye
See how it's not possible

### What You Expect To Happen

To get Dye

### What Actually Happened

I didn't get it

### Additional Details

After looking at the Code the Recipes don't seem to exist. Probably has something to do with the Code Clean-Up

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
![6Cnq0SV](https://github.com/The-Aether-Team/The-Aether/assets/6759864/fe18f56a-21e5-4b8f-9e9c-9597fc3faf05)
![71IihkG](https://github.com/The-Aether-Team/The-Aether/assets/6759864/20da2689-b107-4eb5-b311-93a06ef879eb)

Working fine for me?

**Comment by Builderdog841** [comment]
That's odd. I'll test it further

**Comment by Builderdog841** [comment]
I looked again and I can't find any of those recipes in the Code.

**Comment by OzPayn** [comment]
It seems to be from line 168 onwards in the AetherRecipeData.java file, and outputs two json files with the recipes for each flower to dye conversion

**Comment by OzPayn** [comment]
Im sure if I knew GitHub better I could show it here in the comments but yeah, the recipes are definitely there and work in game perfectly fine

**Comment by Builderdog841** [comment]
![Screenshot 2023-09-13 155910](https://github.com/The-Aether-Team/The-Aether/assets/81527321/66866af0-c68e-48ef-a34b-b4b026cd71fa)

**Comment by OzPayn** [comment]
Do you have any other mods installed that could be potentially overriding the recipe?

**Comment by Builderdog841** [comment]
I have Ancient Aether installed but doesn't change such Recipe and the Recipes don't appear for me in the code
![Screenshot 2023-09-13 162308](https://github.com/The-Aether-Team/The-Aether/assets/81527321/bc9050da-d798-4240-a38d-0cdb5d9a18af)
There should be a white_dye_from_white_flower.json here and also can't find that recipe on the Github Repository

**Comment by OzPayn** [comment]
The recipes are called flower_to_purple_dye.json and flower_to_white_dye.json
they are very much so present in the repo

**Comment by Builderdog841** [comment]
oh wait after further inspection some thing does seem to be broken in Ancient Aethr it's not a regular Aether Issue. Soory for not properly checking
