### ISSUE TITLE
Bug: Aether passive mobs continue to spawn despite gamerule doMobSpawning being false

### ISSUE THREAD

**Issue by cshcrafter** [Gilded-Games/The-Aether#1710]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.2.23

### The Aether Version

aether-1.19.2-1/0/0

### Steps to Reproduce

Step 1: Create new default world
Step 2: Set gamerule doMobSpawning to false (or so so upon world creation)
Step 3: Go into the aether and see that passive mobs still spawn. This includes aerbunnies, shepuffs, moas, phygs, etc.
Step 4 (Optional): Try doing a /kill @e[type=!player] and see that stuff still respawns after that

### What You Expect To Happen

Step 1: Create a new world with the aether installed
Step 2: Set gamerule doMobSpawning to false (or do so upon world creation)
Step 3: Head into the aether and see that passive mobs still spawn. This includes phygs, shepuffs, moas, flying cows, and aerbunnies
Step 4 (Optional): Try doing a /kill @e[type=!player] and see that things still respawn

### What Actually Happened

Step 1: Create a new world with the aether installed
Step 2: Set gamerule doMobSpawning to false (or do so upon world creation)
Step 3: Head into the aether and see that passive mobs still spawn. This includes phygs, shepuffs, moas, flying cows, and aerbunnies
Step 4 (Optional): Try doing a /kill @e[type=!player] and see that things still respawn

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
As far as I can tell, this is apparently intentional https://bugs.mojang.com/browse/MC-56687. It happens in the Overworld too.
