### ISSUE TITLE
The Aether does not like shaders.

### ISSUE THREAD

**Issue by Coach-mdl** [Gilded-Games/The-Aether#172]
Tested with multiple shaders and _this_ is the result. Ambrosium ore and torches also don't seem to glow like they did in 1.12.2.

![2021-07-29_17 09 20](https://user-images.githubusercontent.com/59576000/127527556-fa4cd7ec-2585-47e8-bdba-e35862723236.png)

**Comment by bconlon1** [comment]
This is why there's a config to disable the custom skybox.
