### ISSUE TITLE
Bug: <title> "Server" either disconnects or crashes upon taking damage from Valkyries, Cockatrice needles, due to "Ticking Entity" in single player

### ISSUE THREAD

**Issue by What-The-Cheick** [Gilded-Games/The-Aether#1724]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

43.2.23

### The Aether Version

1.0.0 Forge Beta 1

### Is This Bug a Conflict With Another Mod?

[Unknown but potentially]

### Client Log

https://gist.github.com/What-The-Cheick/692a075f2394f17fdb6b5a9e36b18132

### Crash Report (if applicable)

https://gist.github.com/What-The-Cheick/957f69c995a98cb0a3dd8653499f62d8

### Steps to Reproduce

Constant
Step 1. Have a Valkyrie attack you, or have a Cockatrice shoot you
Step 2. Profit??

### What You Expect To Happen

Take damage

### What Actually Happened

Game crash/"disconnect"

### Additional Details

I'm not well versed in errors behind the scenes, so understanding what causes what is very difficult. I also understand that it may not actually be the Aether causing it, at least not directly, and that it may be difficult to find an issue as this isn't only using Aether

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This crash seems to be caused by `creaturesandbeasts`.

**Comment by bconlon1** [comment]
I'd recommend reporting the issue here: https://github.com/bonsaistudi0s/Creatures_And_Beasts-Forge/issues

**Comment by What-The-Cheick** [comment]
Do you know what specifically? If not that's fine, not your mod after all

**Comment by bconlon1** [comment]
something to do with mob attributes but I'm not sure beyond that.
