### ISSUE TITLE
Feature Request: Add INFO of items to the JEI tab

### ISSUE THREAD

**Issue by ffuentesm** [Gilded-Games/The-Aether#1729]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

My idea is to make use of the Info tab in the JEI to give a brief description of item functions. For a quick description of items such as the Altars, freezer, and others. 
Also, adding mob drop info on JER would have the same effect. Knowing where each item comes from is very helpful. 

### Why Should It Be in the Mod?

I think this would ease players into knowing what some things are for, as by just clicking on the item, you can find a description on the JEI tab. 

### Does This Feature Improve Compatibility With Another Mod?

JEI/JER/EMI/REI

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
For the info tab, I debated doing this, however it would make the Book of Lore redundant. So, I'd rather leave that up to modpack makers. For JER, it automatically gives mob drop information.

**Comment by ffuentesm** [comment]
You could just add Info for functional blocks, such as the incubator. No need to add all the lore to the JEI tab, as you mentioned, that would make the Lore Book redundant, but maybe non-lore information could be useful.

**Comment by bconlon1** [comment]
There's not really much more info to be given about functional blocks than what is already in the Book of Lore or from the already existing JEI integration for recipes.
