### ISSUE TITLE
Crafting: Many recipes broken

### ISSUE THREAD

**Issue by shxmie** [Gilded-Games/The-Aether#1731]
### What Feature Types Apply to This Bug?

Most; playability especially

### Other Type

Unable to craft certain items

### What Type of Bug Is This?

None

### Forge Version

43.2.14

### The Aether Version

1.19.2 1.0.0 Beta

### Client Log

https://gist.github.com/shxmie/cd4290fbee6c3988322b20a42b56ef4d#file-latest-log

### Steps to Reproduce

1: Generate world
2: Attempt to craft wood-based items
3: Results

### What You Expect To Happen

Items to be crafted. 

### What Actually Happened

Nothing

### Additional Details

I believe it is an issue where the code saying your recipe is the only one. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
Wood based recipes are working on my end. It looks like you're running quite a few other mods. This is likely an issue caused by one of your other mods creating some kind of recipe conflict.

**Comment by shxmie** [comment]
I figured I'd check here since the recipes in game only said Aether
recipes, even with polymorph, it won't let me select another.

**Comment by shxmie** [comment]
Thank you though I do appreciate the help

**Comment by shxmie** [comment]
the issue is actually Aether mod related, I checked. The only wood recipes
viable are aether ones

**Comment by shxmie** [comment]
Unless some other mod may influence Aether API? is there a dependent that
messes Aether up?

**Comment by bconlon1** [comment]
Remove mods to see which is conflicting

**Comment by shxmie** [comment]
Removing The Aether Mod fixed the issue. Like I said, it's an error in the
recipes. When downloaded the aether mod OVERRIDES other wooden recipes.

**Comment by shxmie** [comment]
I can send a video with proof if you'd like.

**Comment by bconlon1** [comment]
I mean have you reproduced this to happen *without other mods* and only Aether.

**Comment by shxmie** [comment]
Not yet, but this is still an issue with the Aethers code being unable to
cooperate with other mods.

I'll figure out which mod specifically it is that messes it up and let you
guys know. As of now, some random mod in my pack is having a war with
Aether XD

Thanks friends for the help. I'll hopefully be able to help back if I can
figure it out. Many thanks

**Comment by bconlon1** [comment]
It isn't guaranteed that this is an Aether issue without more information; that's not always how mods work.

**Comment by rcbernos** [comment]
It was probably TFC. Just had the exact same problem and resolved it by removing it.
