### ISSUE TITLE
Mod Not Working on Latest Version

### ISSUE THREAD

**Issue by JomarOliveras14** [Gilded-Games/The-Aether#1741]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Mod wont work despite being on 1.20.1 and forge

### What Type of Bug Is This?

Compatibility

### Forge Version

1.0.0

### The Aether Version

1.2

### Steps to Reproduce

i open minecraft, but then it closes and displays an error

### What You Expect To Happen

im on 1.20.1 and the mod is a 1.20.1 file

### What Actually Happened

i opened minecraft but the mod didnt work

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by micrwvae** [comment]
add the crash log

**Comment by bconlon1** [comment]
Please reopen a new issue with the correct version of Forge (1.0.0 is not a version of forge) and an attached log. Just saying there was a crash is not useful at all.
