### ISSUE TITLE
Bug: Players can't join dimension(s) if Bunny riding.

### ISSUE THREAD

**Issue by Cixon** [Gilded-Games/The-Aether#1742]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.3

### The Aether Version

1.20.1-1.0.0-beta.1-neoforge // latest

### Is This Bug a Conflict With Another Mod?

no.

### Client Log

n/a

### Crash Report (if applicable)

n/a

### Steps to Reproduce

1. Goto Aether.
2. Equip bunny entity.
3. Jump into the void.
4. Attempt to re-enter Aether from Overworld.
// temporarily fixable by unequipping. //

### What You Expect To Happen

To successfully enter dimension with bunny still riding player.entity

### What Actually Happened

Denied access. Portal sounds still que but nothing occurs.

### Additional Details

> // temporarily fixable by unequipping. //

this works for users who only use Aether but **not** in my modpack:
https://legacy.curseforge.com/minecraft/modpacks/legacy-forge/files/4760674

I will need to do more investigating and diagnosing for the modpack issue but I'm hoping that if the initial bug report is fixed, it'll fix this modpack anomaly too.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
Using an Aerbunny counts as riding a mount, you can't travel through portals on a mount. This is consistent with vanilla MC afaik

**Comment by Cixon** [comment]
> Using an Aerbunny counts as riding a mount, you can't travel through portals on a mount. This is consistent with vanilla MC afaik

Gotcha. I'll see what's occurring in my modpack that's preventing me from joining Aether despite after unmounting bunny. Thanks!
