### ISSUE TITLE
Feature Request: Allow Book of Lore to be placed on a Lectern

### ISSUE THREAD

**Issue by MinerMan60101** [Gilded-Games/The-Aether#1750]
### What Feature Types Apply to This Request?

Block, Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Vanilla Minecraft's lecterns allow you to place book and quill/signed books on them so you can read them from the lectern rather than from your inventory. The Aether's "Book of Lore" should have the same functionality. Comparator signals can be handled in the same way as vanilla books, based on what page you're on, although exiting the menu should return the item you're learning about to your inventory and reset the comparator signal strength to one.

### Why Should It Be in the Mod?

Implementing this would create a cool way of displaying the book within your house, allowing you to walk over and use it at your leisure. Currently you either have to let it take up space in your inventory, or take it out of a chest or item frame and then put it back when you're done. I naturally had the idea to try this during my playthrough and some proportion of other players will too.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Unfortunately this isn't easily doable because of how different the book of lore is from vanilla books
