### ISSUE TITLE
Bug: Skyroot planks do not satisfy "Craft wooden planks" tutorial

### ISSUE THREAD

**Issue by MinerMan60101** [Gilded-Games/The-Aether#1754]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

None

### Forge Version

43.3.0

### The Aether Version

1.00

### Steps to Reproduce

1. Create a brand new installation of Minecraft and launch it
2. Create a new world in survival mode with cheats enabled
3. Confirm that the tutorials are activated by seeing the "Use WASD to move" in top right of screen
4. Immediately give yourself the materials to construct an Aether portal with commands
5. Enter the Aether portal and navigate to land
6. Wait long enough for the "Destroy the Tree" tutorial to appear
7. Punch a Skyroot tree and obtain its logs
8. See the "Open your inventory" tutorial appear and open your inventory, then close it
9. Wait long enough for the "Craft wooden planks" tutorial to appear
10. Craft Skyroot planks

### What You Expect To Happen

I expect Skyroot planks to satisfy the "Craft wooden planks" tutorial

### What Actually Happened

Crafting Skyroot planks does not remove the tutorial from the top right of my screen

### Additional Details

Confirmed on both 1.20.1-1.00 and 1.19.2-1.00 (please add fields to the bug report template to indicate mod loader (e.g. Forge/Neoforge/Fabric) and Minecraft version)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Builderdog841** [comment]
Iirc Skyroot Planks would need to be in the #minecraft:planks tag for that which they aren't since that wouldn't make Skyroot Tools and Stuff craftable

**Comment by bconlon1** [comment]
Yeah this is a vanilla limitation unfortunately.
