### ISSUE TITLE
Feature Request: Invis cape texture

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1756]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Give the invis cape an actual texture / model to display on the player character.

### Why Should It Be in the Mod?

In earlier versions of the mod, wearing the invis cape automatically rendered the wearer invisible, so there was no point in giving it a proper cape texture. Now that you can toggle invisibility, it would be nice to be able to see it on players, both as a cosmetic and to make it clear that the other player is not running around without a cape.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Not planned; the cloak is invisible so you still can't see it.
