### ISSUE TITLE
Bug: Enchanted Aether Grass Blocks don't have double drop property

### ISSUE THREAD

**Issue by MinerMan60101** [Gilded-Games/The-Aether#1761]
### What Type of Bug Is This?

None

### Forge Version

47.1.77

### The Aether Version

1.00

### Steps to Reproduce

1. Use Ambrosium on a naturally generated block of Aether Grass
2. Mine that block with a Skyroot Shovel

### What You Expect To Happen

I expect a naturally generated but enchanted block of aether grass to drop two blocks of Aether Dirt when I mine it with a Skyroot Shovel.

### What Actually Happened

It only drops one block of Aether Dirt.

### Additional Details

F3 screen confirms the block is missing the "double_drops" flag.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This is intentional, as the block has been modified it is no longer natural.
