### ISSUE TITLE
Feature Request: Add sound for enchanting Aether Grass

### ISSUE THREAD

**Issue by MinerMan60101** [Gilded-Games/The-Aether#1763]
### Is This an Enhancement to a Preexisting Feature?

- [x] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Using Ambrosium on a block of Aether Grass enchants it, but this happens without any accompanying sound. I suggest creating or finding a sound to go along with this action.

### Why Should It Be in the Mod?

The change would bring this action in line with vanilla's tilling dirt, making dirt paths, and stripping logs, as well as improve game feel.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I should maybe do this with a vanilla slime sound for Swet Balls too tbh.
