### ISSUE TITLE
Feature Request: Aechor Plants could benefit from unique sounds

### ISSUE THREAD

**Issue by MinerMan60101** [Gilded-Games/The-Aether#1766]
### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Right now, Aechor Plants use the default set of sounds for being hit or dying. I suggest creating new sounds which better fit a plant.

### Why Should It Be in the Mod?

The current sounds don't quite fit a living plant, and give the impression of "default sounds that haven't been replaced". New sounds would make the plant feel more unique and complete.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We don't have any plans of adding new sounds to entities.
