### ISSUE TITLE
Bug: Blueberry bush stems have the same hardness as the ripe berry bush.

### ISSUE THREAD

**Issue by Coach-mdl** [Gilded-Games/The-Aether#177]
This is often causes you to break the bush stem when you are harvesting berries, which is irritating if you have a bush farm.

**Comment by bconlon1** [comment]
Technically not a bug but should maybe be looked into regardless.

**Comment by Coach-mdl** [comment]
Could be an idea to swap the functionality to hoes. Make it so the grown berry bush is affected by hoes but the stem is not.

**Comment by bconlon1** [comment]
Probably just gonna make the bush part harvestable by hoe while the stem stays harvestable by axe yeah.

**Comment by bconlon1** [comment]
Apparently this was already fixed when the switch to specifying harvestability through block tags was made.
