### ISSUE TITLE
Bug: <title>Aether not working with optifine error

### ISSUE THREAD

**Issue by Supermariobuzzerd62** [Gilded-Games/The-Aether#1771]
### What Type of Bug Is This?

None

### Forge Version

43.2.23

### The Aether Version

1.0.0

### Is This Bug a Conflict With Another Mod?

optifine version 1.19.2_HD_U_I2

### Client Log

https://gist.github.com/Supermariobuzzerd62/f469a38e38099a29411817ca1f6fcaed

### Crash Report (if applicable)

https://gist.github.com/Supermariobuzzerd62/0ece8cf3e169dcb84323ec261874284f

### Steps to Reproduce

A lot 

### What You Expect To Happen

So I decided to change the version of optifine that I was using because I was using optifine version 1.19.2_HD_U_H9 so I thought 
since maybe I was using the wrong version of optifine so I change it to version _1.19.2_HD_U_I2.

### What Actually Happened

Even though I change the version of optifine I was using it still didn't work.

### Additional Details

When I looked up this error I have only sceen on more older versions of minecraft.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Optifine is unsupported. You will have to remove it.

**Comment by sunsetbear** [comment]
Aether is not compatible with optifine. Optifine is closed-source, so fixing it from the Aether's end is unreasonable. 
Some info about that: https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Note%20on%20Optifine.md
List of alternatives: https://github.com/TheUsefulLists/UsefulMods/blob/main/Performance/Performance119.md
