### ISSUE TITLE
Bug: [1.20.1 Forge] Server tick timeout - EntityListener_onEntityJoin_EntityJoinLevelEvent - [Nether dimension]

### ISSUE THREAD

**Issue by melvinczyk** [Gilded-Games/The-Aether#1772]
### What Type of Bug Is This?

Crash

### Forge Version

47.1.0

### The Aether Version

aether-1.20.1-1.0.0-beta.1.2-neoforge

### Is This Bug a Conflict With Another Mod?

likely not

### Crash Report (if applicable)

https://gist.github.com/melvinczyk/23c7cc37b41f3bd82548ab4f6d0319df

### Steps to Reproduce

1. Run server with mods listed in the server
2. Go close to unexplored region of nether dimension
3. Server tick timeout occurs

### What You Expect To Happen

No tick timeout

### What Actually Happened

Server tick timeout and crash

### Additional Details

This is very similar to the server tick timeout that was occurring in the previous version of the mod (1.1). Version 1.2 (current) fixed the issue of tick timeout in the overworld but continues inside of the nether dimension.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The log says this crash is coming from pehkui.
