### ISSUE TITLE
Bug:  Cockatrice arrows make servers shut down

### ISSUE THREAD

**Issue by gravelcookie** [Gilded-Games/The-Aether#1776]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

v.0.234.3.1

### The Aether Version

1.1.0beta

### Is This Bug a Conflict With Another Mod?

Might be with Creatures and Beasts

### Steps to Reproduce

1. Go to The Aether via Portal
2. Find Cockatrice
3. As soon as the arrow sound is hearable, the server crashes and tries to restart

### What You Expect To Happen

Nothing

### What Actually Happened

Servercrash

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
There is no log in this issue report and neither versions given are valid.
