### ISSUE TITLE
Bug: Leather Gloves do not have their b1.7.3 Texture in the b1.7.3 Texture Pack

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1779]
### What Feature Types Apply to This Bug?

Art

### What Type of Bug Is This?

Design

### Forge Version

47.1.77

### The Aether Version

1.20.1 b1.2

### Steps to Reproduce

Turn on Aether v1.7.3 Textures
Notice how it uses the Wrong texture for Leather Gloves

### What You Expect To Happen

For Gloves to have the b1.7.3 texture

### What Actually Happened

they didn't have it

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The current leather gloves in the legacy packs were made more consistent with leather armor.
