### ISSUE TITLE
Connection Lost on 1.19.2 Server

### ISSUE THREAD

**Issue by FaroshRyujinden** [Gilded-Games/The-Aether#1782]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Error on Server Join

### What Type of Bug Is This?

Compatibility

### Forge Version

43.3.0

### The Aether Version

1.0.0 Beta 1.2

### Steps to Reproduce

I put this mod on the modpack that i'm creating
Load the server
Load the game
Go to Multiplayer and try to connect
Result:
![Sem título](https://github.com/The-Aether-Team/The-Aether/assets/96817363/2d04c166-79f6-468d-ad94-d7c1174e29cb)

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "p_130069_" is null

### What You Expect To Happen

I expected to just work since the server was working normally.

### What Actually Happened

Even after deleting the world and creating a new one, i just can join the server anymore. I also tried the Beta 1.1, same error.

I've search this error on google
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "java.lang.Enum.ordinal()" because "p_130069_" is null
and some old macaw mod trigger this problem, But i've tried removing all macaw mods and the error keeps happening.

### Additional Details

I know that i'm running a lot of mods (326) and i have no problem to remove or change the mods, but i need to discover what mod is causing this incompatibility.

Prints of the mods folder.
![1](https://github.com/The-Aether-Team/The-Aether/assets/96817363/3ec46ba9-208f-49f6-b574-cc4390697f7e)
![2](https://github.com/The-Aether-Team/The-Aether/assets/96817363/a6ba4f5b-b31c-4bbd-8631-e148e29bbff4)
![3](https://github.com/The-Aether-Team/The-Aether/assets/96817363/6764ff12-4795-443c-b9e3-18eb70badd4a)

And my server mods folder also has:
FastLeafDecay-30.jar
SimpleBackups-1.19.1-2.1.10.jar
smoothchunk-1.19.2-3.4.jar
toofast-1.19-0.2.2.4.jar

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The bug report needs to include a log from the server and client.

**Comment by FaroshRyujinden** [comment]
Sorry about that. here are they.

[client latest.log](https://github.com/The-Aether-Team/The-Aether/files/12773573/client.latest.log)
[server latest.log](https://github.com/The-Aether-Team/The-Aether/files/12773574/server.latest.log)

Also, i have tested on single-player and everything works fine.

**Comment by bconlon1** [comment]
Hmm, the logs don't really seem to point to anything, you might have to test with mod removal until something works.

**Comment by FaroshRyujinden** [comment]
This will take forever LoL.
Anyway, I'm going to test what I can and if I discover any mod that is incompatible I'll post it here.

**Comment by darksonic300** [comment]
Don't know if this might help, but it's an issue present with Deep Aether 1.19.2 too. We still haven't figured it out, but seems related to Armor and Tools. Gonna wait for an update on this.

**Comment by FaroshRyujinden** [comment]
Found it, the mod causing the issue was the "SurvivalPlus-1.19.2-0.1.7.jar"

https://www.curseforge.com/minecraft/mc-mods/survivalplus

Hope u can fix it sometime 😁👍

**Comment by bconlon1** [comment]
The solution would likely be to remove SurvivalPlus

**Comment by bconlon1** [comment]
Or report it to their issue tracker.

**Comment by FaroshRyujinden** [comment]
I'll do that later, anyway thanks for the assist and for the New Forge version, I miss this mod on 1.16.5 😂👍
