### ISSUE TITLE
Feature Request: The Fog

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1784]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Gameplay

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To reimplement the fog from older versions

### Why Should It Be in the Mod?

In older versions of Aether 1 the Sky went darker (which gave of a foggy effect) when it rained in the Overworld. Cockatrice were also able to spawn during "The Fog" and it made for some Survival Challenge since a day-night cycle does not exist after the Sun Spirit has been defeated. It was a pretty cool gameplay aspect imo. There could also be a Config for the people that don't want it.
It was also pretty atmospheric.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Builderdog841** [comment]
Though I think it could be balanced to not have Cockatrice literally everywhere

**Comment by bconlon1** [comment]
The sky going darker is an existing feature, it is just toned down so that it has a less harsh color contrast. We've also disallowed Cockatrice spawning during weather as the amount that spawned due to how mob caps work became annoying for players to deal with.
