### ISSUE TITLE
Bug: Skyroot Bookshelves don't use the correct top texture in b1.7.3 pack

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1786]
### What Feature Types Apply to This Bug?

Art

### What Type of Bug Is This?

Design

### Forge Version

47.1.77

### The Aether Version

1.20.1 b1.3

### Steps to Reproduce

The Skyroot Bookshelf never existed in the original, though 2 textures called "LibraryLoreTop.png" and "LibraryLoreSide.png" did exist in the files. The LibraryLoreSide Texture was used for the Skyroot Bookshelf though the top texture wasn't and imo it could be a neat thing for the b1.7.3 texture pack since the files existed in that version.

### What You Expect To Happen

To get the old texture

### What Actually Happened

I didn't get it

### Additional Details

![LibraryLoreSide](https://github.com/The-Aether-Team/The-Aether/assets/81527321/e132ebd9-3d5a-412b-8e2b-469f790da9d9)
![LibraryLoreTop](https://github.com/The-Aether-Team/The-Aether/assets/81527321/46820465-9afa-4232-b45e-0f7a062b37fc)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
For consistency with vanilla and the revamped textures, this will be kept as is.
