### ISSUE TITLE
Will this mod be ported to Fabric?

### ISSUE THREAD

**Issue by allanonmage** [Gilded-Games/The-Aether#1787]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Fabric mod loader

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Will this mod be ported to Fabric?  There was a comment saying that the plan was to backport, then port to Fabric, but 2 or 3 people said there was no plan, so if there is no plan, I have no idea what you are planning or not planning.

### Why Should It Be in the Mod?

Fabric is way MOAR BETTER(TM) than Forge.

Also, this form you made is INCREDIBLY pretentious.

### Does This Feature Improve Compatibility With Another Mod?

All modern mods

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
If you dislike GitHub ticket forms, I would recommend seeing if your ticket has already been made, that can help you avoid them entirely: #1282, #703. We have plans for a Fabric port, you can always check out our Discord for more official info about development plans.
