### ISSUE TITLE
*When* will this mod be ported to Fabric?

### ISSUE THREAD

**Issue by allanonmage** [Gilded-Games/The-Aether#1788]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Fabric

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

I don't have Discord, because for 10 years they have not let me use my account.  idk why, nor do I know what all the hype is about, since I've never used it.  So "ask us on Discord" does not apply.

When I searched Github earlier today, search wasn't working, so obviously I didn't find anything related to a port to fabric, besides one guy saying there was a plan, and then more people saying there was no plan, let alone a plan to port the mod to Fabric.  Which I explained in my feature request earlier today.  Which has now been locked where I can't add to it, nor edit it, so here I am making a whole new post instead.

Please clarify "We have plans for a Fabric port".  Is that "Soon(TM)", or a plan-that-will-never-be-implemented, or somewhere in between?  I don't know you, your team, nor where you learned language from, but in my neck of the woods, that's orders of magnitude more vague than simply "vague", rude, and amounts to "trust me bro"..

Issue #703 indicates that you won't be supporting fabric, and issue #1282 is as vague and noncomittal as the answer that you provided me earlier today, leaving everything, as we say, "clear as mud".  Although, I guess we're 2-1 in favor of Fabric eventually being supported, so support seems to be winning.

I'm sure someone on your team can speak in more than uber-terse half sentences that amount to "leave me alone, go away", so have them write a paragraph explaining your plan and approximate timetable.  For example:

_"We at the dev team who made the mostest awesomest mod evar have been working on Fabric support for 9001 years, and we're currently targeting 1.20 for Fabric.  We think we might be done in 3-6 months, but since this is a new platform for us, things might take longer.  Thanks for asking, and we'll post followups here, including and revised timetables.  We will not target older versions, for example, 1.16.5, at all."._

### Why Should It Be in the Mod?

Because Fabric has beaten Forge

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I am sorry that you are not satisfied with the answer of us having plans for it. We do not give ETAs for any releases, as is the general rule within in the modding community with most hobbyist developers. We also have other platforms that aren't just Discord such as Twitter where we share this kind of information, this issue tracker is not one of them as this isn't an issue nor a feature request.
