### ISSUE TITLE
(Game Version 1.19.2) The Aether is Incompatible With OptiFine HD U I2

### ISSUE THREAD

**Issue by floofycatto** [Gilded-Games/The-Aether#1796]
I'm trying to play modded and I really noticed that this mod just will not load with this version of optifine, I'm using the aether beta.1.2 and forge version 43.3.2

The issue I noticed is if you have the aether even in the same mod folder with this version of optifine, it will just crash and won't load into the menu

and yes, I did single out these two mods and removed every mod etc and narrowed it down to these two, The aether runs completely fine without this version of optifine, but a lot of people use optifine and I'm pretty sure they don't wanna compromise on performance or do what I'm doing and check if they can use a previous version of optifine for this version, here are the logs I got

(this writing is from edit) Even when going to back to older versions of optifine it still just crashes

[crash-2023-10-08_09.44.56-client.txt](https://github.com/The-Aether-Team/The-Aether/files/12840981/crash-2023-10-08_09.44.56-client.txt)

crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

Exit Code: -1

**Comment by Builderdog841** [comment]
The mod is incompatible with optifine.

**Comment by Mrthomas20121** [comment]
Optifine is not compatible, use embedium+occulus for shader support.
