### ISSUE TITLE
Hourglass has a effect on the day moving very slowly in the aether

### ISSUE THREAD

**Issue by ClockworkzAI** [Gilded-Games/The-Aether#1797]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.3.2

### The Aether Version

aether-1.19.2-1.0.0-beta.1.2

### Is This Bug a Conflict With Another Mod?

hourglass

### Steps to Reproduce

Load up a world with hourglass mod and aether mod
go to the aether
look at the sun moving slightly.

### What You Expect To Happen

The time should have stopped

### What Actually Happened

time went on as normally slowly 

### Additional Details

If it is not fixed by you let me now so that I can ask the creator of hourglass to see if he can fix it

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Report this to https://github.com/DuckyCrayfish/hourglass/issues as well, I think they are affecting the time of all dimensions which is messing with the Aether's time, but I'm not entirely sure how their mod works.

**Comment by Maypul** [comment]
@ClockworkzAI you could try Better Days mod instead that is a fork of Hourglass but updated, and if it does not work with it, report it to them as there is probably better chance it will be looked into.

**Comment by bconlon1** [comment]
If Hourglass is currently unmaintained, then I would also recommend using Better Days and reporting the issue to them if it persists.
