### ISSUE TITLE
Bug: <Slider boss will not activate>

### ISSUE THREAD

**Issue by Pietonn** [Gilded-Games/The-Aether#1807]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.2.0

### The Aether Version

1.0.0-beta.6.2

### Client Log

https://gist.github.com/Pietonn/260c6243138dee262be24f40a087bfbb

### Steps to Reproduce

1. hit slider boss with pickaxe 
2. text says use pickaxe 
3. boss doesn't activate
4. can only kill boss with kill command 
5. doesn't recognize pickaxe in players hand

### What You Expect To Happen

you will not be able to kill the boss or deal damage with pickaxe

### What Actually Happened

I couldn't kill the boss with a pickaxe

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Do you have divinerpg installed?

**Comment by Pietonn** [comment]
yep lol

**Comment by Pietonn** [comment]
is that the prob?

**Comment by bconlon1** [comment]
Yes, it is an issue they have to fix on their end.
