### ISSUE TITLE
mimicBug

### ISSUE THREAD

**Issue by Pokemon0992010** [Gilded-Games/The-Aether#1808]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

43.2.14

### The Aether Version

1.19.2 

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

i just went up to the chest mimic and interacted with it to start the fight

### What You Expect To Happen

i though the mimic would be a normal battle

### What Actually Happened

as soon as the mimic attacked me the game crashed and when i repoened it all my items where gone along with the mimic

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Please provide a crash log as requested in the form.
