### ISSUE TITLE
Bug: Error when connecting server

### ISSUE THREAD

**Issue by littlepianist** [Gilded-Games/The-Aether#1812]
### Other Type

MaoType

### What Type of Bug Is This?

None

### Forge Version

47.2.1

### The Aether Version

1.20.1-1.0.0-beta.1.3-neoforge

### Client Log

https://gist.github.com/littlepianist/85b5e382a40d6871f5ffd43d5451d352

### Steps to Reproduce

join server 
error

### What You Expect To Happen

to join server successfully without error

### What Actually Happened

can't join server and have error

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Use Forge 47.1.0.
