### ISSUE TITLE
Bug: Phoenix bow ignores protections

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1813]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.44

### The Aether Version

1.0.0-beta.1.3-neoforge

### Steps to Reproduce

Consistently reproducible.
1. Get the phoenix bow.
2. Shoot a player wearing the shield of repulsion.

### What You Expect To Happen

I expect the arrow to just bounce off.

### What Actually Happened

The arrow did not deal damage on impact, but still ignited the player.

### Additional Details

Also ignores claim protections on OATS, allowing the user to kill mobs inside claims by letting them slowly burn.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Does this apply to flame bows? if so, sounds like a cadmus bug

**Comment by Cinex20** [comment]
Pretty sure I checked a regular bow and it did not work.

**Comment by bconlon1** [comment]
Report this to Cadmus, it seems they don't account for the ProjectileImpactedEvent so it doesn't prevent behavior run by that.
