### ISSUE TITLE
Feature Request: Adding the ability to spawn in the Aether & for the Aether void to function as a normal void

### ISSUE THREAD

**Issue by AGUrGrill** [Gilded-Games/The-Aether#1814]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Could you add the ability to make the Aether the default world spawn, as well as the ability to disable the void from connecting with the overworld?

### Why Should It Be in the Mod?

It would allow for a more robust gameplay option (and the ability for me to make a modpack where the user spawns in the Aether) :)

### Does This Feature Improve Compatibility With Another Mod?

Forgiving World - Dimension Stacking [forgivingworld-1.20.1-4.2]

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
These options already exist as world configs.
