### ISSUE TITLE
Bug: Blocks and Items don't have proper tagging

### ISSUE THREAD

**Issue by Stray216** [Gilded-Games/The-Aether#1816]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Minecraft Tags

### What Type of Bug Is This?

Compatibility

### Forge Version

47.1.3

### The Aether Version

1.20.1-1.0.0-beta.1.3-neoforge

### Client Log

not necessary

### Steps to Reproduce

1) Open crafting table
2) Look up a recipe that includes wood, planks or stones (either recipe book or JEI)
=> for example the minecraft grindstone
3) In the case of the grindstone and looking up in JEI, you will see separate recipes

### What You Expect To Happen

I expected to see one recipe for the grindstone that lists "Skyroot Planks" as a possibility for "Accepts any: minecraft:planks" and Holystone Slab as a substitute for Stone Slab.

This is possible to do using the minecraft tagging system.

### What Actually Happened

I'm seeing 3 different recipes:

- Sticks + Stone Slab + Skyroot Planks = Grindstone
- Sticks + Holystone Slab + Skyroot Planks = Grindstone
- Sticks + Stone Slab + Any Planks = Grindstone

### Additional Details

Curiously, the combination:
- Sticks + Holystone Slab + Any Planks

does **not** make a grindstone, which only supports the fact that the blocks/items need proper tagging.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This is because tagging skyroot planks as wood would introduce various recipe conflicts between Aether and Minecraft.
