### ISSUE TITLE
Bug: {Compatibility} 1.19.2 w/ HMaG

### ISSUE THREAD

**Issue by togera13** [Gilded-Games/The-Aether#1817]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### What Type of Bug Is This?

Compatibility

### Forge Version

43.3.2 Forge

### The Aether Version

1.0.0-beta.1.2-Forge

### Is This Bug a Conflict With Another Mod?

hmag-forge-mc1.19.2-6.2.7

### Steps to Reproduce

The Aether - 1.19.2-1.0.0-beta.1.2-forge: https://www.curseforge.com/minecraft/mc-mods/aether/files/4771515

W/ hmag-forge-mc1.19.2-6.2.7: https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls/files/4787085
1 Start a multiplayer session either through Essential or a server.
2 Have your friend join, or join your server that contains The Aether & HMaG.
3 You will be booted from the session when attempting to join. Oddly both mods will work together when in singleplayer for whatever reason, but not in multiplayer.

### What You Expect To Happen

I expected the game to not get a disconnect when trying to play with friends from whatever that was.

I reported these issues to both sides.

### What Actually Happened

The game crashed when playing multiplayer (w/ HMaG)

### Additional Details

When booted from the server in combination with HMaG:
![Screenshot 2023-10-18 023538](https://github.com/The-Aether-Team/The-Aether/assets/119283778/2b36f3d1-ea7e-43ec-80b7-b8936114874b)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Mechalopa** [comment]
Ummm, if the json file that adds the aether repairing recipe is deleted, it will connect to the server successfully...
https://github.com/Mechalopa/Hostile-Mobs-and-Girls/tree/1.19.2/src/main/resources/data/hmag/recipes/aether

**Comment by bconlon1** [comment]
These sound like separate issues, could you please split this issue so I can handle this separately.

**Comment by togera13** [comment]
> These sound like separate issues, could you please split this issue so I can handle this separately.

How should I or they go about doing that?

Should I just wipe off the IC2C issue off of this one since someone involved with HMaG responded & make a new post for IC2C instead or?

I don't really used github that often.

**Comment by bconlon1** [comment]
Yeah that would work.

**Comment by bconlon1** [comment]
> Ummm, if the json file that adds the aether repairing recipe is deleted, it will connect to the server successfully... https://github.com/Mechalopa/Hostile-Mobs-and-Girls/tree/1.19.2/src/main/resources/data/hmag/recipes/aether

@Mechalopa do you mean for your mod or the Aether itself?

**Comment by Mechalopa** [comment]
> @Mechalopa do you mean for your mod or the Aether itself?

Means removing the recipe json from the HMaG jar file.

**Comment by bconlon1** [comment]
Issue determined to be on HMaG's end.
