### ISSUE TITLE
Feature Request: Request updates to 1.20.2 and Fabric versions

### ISSUE THREAD

**Issue by SadEPa0628** [Gilded-Games/The-Aether#1818]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.
  (Uh, idk does that count)

### What Is Your Feature Request?

I expect this mod to be updated for versions of 1.20.2 and Fabric.

### Why Should It Be in the Mod?

I'm using 1.20.2 Fabric and I want to be able to use this mod.

And if you can't, don't be like the Ultimate Car writer [_____], he has a bad attitude.
The content is translated by Chinese machine. Please understand if there is any mistake.

### Does This Feature Improve Compatibility With Another Mod?

Fabric API All versions

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We already have plans for Fabric and future versions.

**Comment by SadEPa0628** [comment]
Okay, thank you.
