### ISSUE TITLE
Bug: Gravitite ore does not float up.

### ISSUE THREAD

**Issue by Coach-mdl** [Gilded-Games/The-Aether#182]
The ore is sad today.

**Comment by Coach-mdl** [comment]
Modlist:
-Forge 36.2.0
-Adorn
-Appleskin
-AstikorCarts
-Better Third Person
-Charm
-Charmonium
-Clumps
-Comforts
-Controlling
-Corail Tombstone
-Craftable Horse Armor and saddle
-Create
-Curious elytra
-Doggy talents
-Dude where’s my horse
-Fastfurnace
-Fastworkbench
-Horse combat controls
-Mrcrayfish gun mod
-Shoulder surfing reloaded
-stupid horse stand still
-storage drawers
-swing through grass 
-waystones
-mouse tweaks
-Dungeon crawl
-PHC food core
-Odd water mobs
-Mob grinding utils
-Name tag tweaks
-Netherite Horse armor 
-Tetra
-Spawnerfix

**Comment by bconlon1** [comment]
(Note: Not the same as #324)
