### ISSUE TITLE
Bug: {Compatibility} 1.19.2 w/IC2C

### ISSUE THREAD

**Issue by togera13** [Gilded-Games/The-Aether#1820]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Compatibility

### What Type of Bug Is This?

Compatibility

### Forge Version

43.3.2 Forge

### The Aether Version

1.0.0-beta.1.2-Forge

### Is This Bug a Conflict With Another Mod?

IC2Classic-1.19.2-2.0.7.1

### Steps to Reproduce

1 Start the game with The Aether & IC2C installed.
2 Place any sign from IC2C
3 The game crashes & you then have to either disable the Aether & break the signs, or you can disable IC2C & unload the signs.

### What You Expect To Happen

To place a sign from Industrial Craft 2 Classic.

### What Actually Happened

The game crashed when placing the sign. (Notably only IC2C signs crash the game, Aether signs can be placed without a crash.)

### Additional Details

The Aether - 1.19.2-1.0.0-beta.1.2-forge: https://www.curseforge.com/minecraft/mc-mods/aether/files/4771515

W/ IC2Classic-1.19.2-2.0.7.1: https://www.curseforge.com/minecraft/mc-mods/ic2-classic/files/4746971

I don't know if this is a client log or crash report so I didn't put it in the thing:
https://github.com/TinyModularThings/IC2Classic/files/12806293/crash-2023-10-04_13.14.22-client.txt

I could probably get a fresh crash & client log by running a test instance with both mods if necessary.

https://github.com/TinyModularThings/IC2Classic/issues/876

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Source for reference: https://github.com/TinyModularThings/IC2Classic

**Comment by Speiger** [comment]
Found the issue. 
It was clear that this wasn't a Aether issue, but i never figured out why.
Thanks to Aether i figured it out, thanks guys...

https://github.com/The-Aether-Team/The-Aether/blob/1.20.1-develop/src/main/java/com/aetherteam/aether/client/AetherAtlases.java#L26

I never did this.
When we added the blocks that never existed... (1.14.4)
So yeah this will be addressed.
