### ISSUE TITLE
Feature Request: Config option to disable falling into the Overworld from the Aether

### ISSUE THREAD

**Issue by TheMagicalSC** [Gilded-Games/The-Aether#1823]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

I think that a config option to disable falling into the Overworld when falling off the Aether would be a great idea.

### Why Should It Be in the Mod?

I feel that such a feature would greatly expand modpack makers options when add the Aether mod to their packs.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This already exists in the mod's world configs.
