### ISSUE TITLE
Bug: {Compatibility} 1.19.2 W/ Citadel's chunk gen spawn modifier set ≥4

### ISSUE THREAD

**Issue by togera13** [Gilded-Games/The-Aether#1825]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Compatibility

### Forge Version

43.3.2 Forge

### The Aether Version

1.0.0-beta.1.2-Forge

### Is This Bug a Conflict With Another Mod?

citadel-2.1.4-1.19

### Steps to Reproduce

Open the citadel config
set the chunk gen spawn modifier to anything equal to or higher than 4
load into a world
place an Aether portal
enter the Aether
The Aether will not load & you will be endlessly falling, attempting to close the game will require task manager.

### What You Expect To Happen

Load into The Aether.

### What Actually Happened

Endless falling / server freeze / unclosable game (task manager needed).

### Additional Details

https://www.curseforge.com/minecraft/mc-mods/aether/files/4771515
https://www.curseforge.com/minecraft/mc-mods/citadel/files/4556677

I was using Citadel's feature to increase the mob spawn count per chunk & the Aether would fail to load & freeze the server if anyone entered it when the config option of citadel was set to anything equal to or higher than 4.

Oddly enough it is only after it hits 4 that The Aether fails to load, 3 & below loads The Aether successfully, but as soon as the option is set to 4 or higher it fails to load The Aether.

Setting the option to 3 or lower seems to be a workaround-ish, I just wanted to make this known in case if anyone else was using the feature from Citadel to increase their mob spawns & was wondering why The Aether wouldn't load in.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I'll need the logs for this.

**Comment by togera13** [comment]
This was all that was in the logs folder I don't know if this is what you needed or not, I ran it an additional time & posted the logs again so idk if one of them is a duplicate or not, if you have anything else you need me to do let me know.
[latest.log](https://github.com/The-Aether-Team/The-Aether/files/13161510/latest.log)
[latest.log](https://github.com/The-Aether-Team/The-Aether/files/13161558/latest.log)
[2023-10-25-1.log](https://github.com/The-Aether-Team/The-Aether/files/13161560/2023-10-25-1.log)

I appreciate your work btw.

**Comment by bconlon1** [comment]
Source for reference: https://github.com/AlexModGuy/Citadel

**Comment by bconlon1** [comment]
My current theory is that setting the value to 4 and quadrupling the spawn count is just making too many mobs spawn in the Aether for the game to handle, but I'm going to wait for a response from the Citadel developers since if it is only happening with Aether then that's still odd.

**Comment by bconlon1** [comment]
This seems to technically be an issue with Citadel, they allow for the spawn modifier config value to be set too high for certain circumstances which causes stalls like this, so they'll need to add a safety check on their end. https://github.com/AlexModGuy/Citadel/issues/141
