### ISSUE TITLE
Bug: Invis cape multiplayer desync

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1827]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

47.1.44

### The Aether Version

1.0.0-beta.1.3-neoforge

### Steps to Reproduce

Happens very often.
1. Equip the invis cape.
2. Teleport to another dimension, either through a portal or via commands.
3. Go to another player.

### What You Expect To Happen

I expect to be completely invisible.

### What Actually Happened

My character is invisible, but their armor, cape and other external elements (like elytra, accessories, halo) are fully visible, making the cape roughly as effective as an invisibility potion.

### Additional Details

Traveling between dimensions also causes other players wearing invis capes to be revealed like this. Rejoining the server may trigger the bug as well. Toggling invisibility with a keybind fixes the desync.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Dimension travel syncing moment.

**Comment by bconlon1** [comment]
This code for syncing must not be working for invisibility capes specifically for some reason. https://github.com/The-Aether-Team/The-Aether/blob/db5ad873baf7c80cd03d94bac948048dd8db6def/src/main/java/com/aetherteam/aether/event/hooks/CapabilityHooks.java#L75
