### ISSUE TITLE
Bug: Flaming Sword and Phoenix Bow do not attribute kills by burning to the player

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#1829]
### What Type of Bug Is This?

None

### Forge Version

47.1.44

### The Aether Version

1.0.0-beta.1.4-neoforge

### Steps to Reproduce

Consistently reproducible.
1. Get a flaming sword / phoenix bow.
2. Use it to damage a mob that drops XP.
3. Let it burn to death.

### What You Expect To Happen

I expect the mob to drop XP.

### What Actually Happened

The mob did not drop XP.

### Additional Details

The mob has to die at least 3 seconds after being hit.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment]
This appears to be consistent with vanilla behaviour, killing a mob with fire aspect II does not yield xp after a certain duration, I imagine it relates to how vanilla MC tracks attribution of the kill.

Closing the issue
