### ISSUE TITLE
Feature Request: Makes gloves in vanilla loot configurable

### ISSUE THREAD

**Issue by zeid0ne** [Gilded-Games/The-Aether#1830]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Makes gloves in vanilla loot configurable to allow disabling of it

### Why Should It Be in the Mod?

Cause i want to control overworld loots in my modpack

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
They're done through Forge GLMs which you should be able to overwrite with empty files.

**Comment by zeid0ne** [comment]
can you explain me how i can do that please ?

Edit : i did it by altering the code source but it's not optimal cause i'll need to do it after each update.
