### ISSUE TITLE
Natural spawn options for Valkyrie and Sentry.

### ISSUE THREAD

**Issue by karaagedesu1** [Gilded-Games/The-Aether#1831]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Please create a configuration that will allow Valkyrie and Sentry to spawn naturally in their respective dungeons instead of when they step on traps. 

### Why Should It Be in the Mod?

The reason is that spawning by traps crashes my modpack.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Builderdog841** [comment]
You could do that easily with a datapack

**Comment by Builderdog841** [comment]
Also you should send a crash log

**Comment by MidK284** [comment]
My modpack also crash when Valkyries spawn,here is the crash log
[crash-2023-11-03_00.08.30-server.txt](https://github.com/The-Aether-Team/The-Aether/files/13242113/crash-2023-11-03_00.08.30-server.txt)

**Comment by bconlon1** [comment]
This is an issue with Auditory, they should be ensuring `itemStack != null`, since the ItemStack parameter in `EntityType#spawn` is nullable: https://github.com/Sydokiddo/auditory/blob/91dd0a58bb3766b4d1c9312e1832925af2d5378b/src/main/java/net/sydokiddo/auditory/mixin/items/SpawnEggUseSoundMixin.java#L26
