### ISSUE TITLE
Feature Request: More Aether blocks should change a note block's instrument

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#1833]
### What Feature Types Apply to This Request?

Audio, Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

As it stands, only the skyroot and holystone building sets change the "instrument" that a note block plays, but only because of the forge tag system. This request is to make more aether blocks change the instrument of a note block, not to add more sounds.

### Why Should It Be in the Mod?

It would improve the parity between the note block system and the aether's blocks, and further the cohesion of the mod.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We'd be willing to do this but it would be useful to have some suggestions if there's any specific ideas regarding this.
