### ISSUE TITLE
Any plans for adding forge modloader for 1.20.1?

### ISSUE THREAD

**Issue by FirdausCraft10** [Gilded-Games/The-Aether#1836]
### What Feature Types Apply to This Request?

Add the forge modloader for Minecraft 1.20.1

### Other Type

Nothing

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Add the forge modloader to the version of 1.20.1

### Why Should It Be in the Mod?

Nothing

### Does This Feature Improve Compatibility With Another Mod?

Nothing

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by OzPayn** [comment]
1.20.1 already supports Forge
