### ISSUE TITLE
Bug: World generation crash on FieldsproutTreeFeature

### ISSUE THREAD

**Issue by LoneStarrr** [Gilded-Games/The-Aether#1837]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

47.1.3

### The Aether Version

1.20.1-1.0.0-beta.1.4-neoforge

### Crash Report (if applicable)

https://gist.github.com/LoneStarrr/a65602ef152646808bd5c1ac601ebe52

### Steps to Reproduce

Player entering the Aether dimension through a portal at a specific location

### What You Expect To Happen

Worldgen works

### What Actually Happened

Server crashed on chunk generation

### Additional Details

modpack: https://www.curseforge.com/minecraft/modpacks/chosens-modded-adventure-chunk-by-chunk/files/4839084 version 0.1.2

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Zepalesque** [comment]
this isn’t an aether bug, its a bug with one of its addons which was made by me, called the Aether: Redux (which adds fieldsprout trees), so you’ll have better luck [reporting that at its issue tracker (this is a link)](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/issues)
but I can understand why you’d get it mixed up, I should probably change the package name lol

**Comment by LoneStarrr** [comment]
Thanks for clearing that up! I did notice the add-on and figured indeed based on the package name it would be this mod instead. Closing the bug here since I see you already have it listed @Zepalesque

**Comment by LoneStarrr** [comment]
Not completed, retracted
