### ISSUE TITLE
Bug: Event Hook causing low TPS on Multiplayer Server MC 1.19.2

### ISSUE THREAD

**Issue by xkobalx** [Gilded-Games/The-Aether#1841]
### What Type of Bug Is This?

Performance

### Forge Version

43.2.21

### The Aether Version

1.19.2-1.0.0-beta.1.2-forge

### Steps to Reproduce

Only effecting some players.
On player log in.
![image](https://github.com/The-Aether-Team/The-Aether/assets/10780881/a8fdd013-d2f8-4010-b5b8-191f1c2abd98)
This event appears on the profiler and there are constant tps issues.
This event is triggering no matter what dimension the player is in or where they are in those dimensions.
The issue will sometimes disappear for a minute or two before resuming.
The image shows 10% but it has gone as high as 25%.
Effected players log out.
The issue stops immediately.

### What You Expect To Happen

The event should not be constant and should not be using so much of the servers resources.

### What Actually Happened

Event triggering when certain players log in causing TPS issues.

### Additional Details

Issue persists on the effected players between reboots and logins.

Other players have been to the Aether, to the same areas and have completed the same content but are not effected.

Dedicated Server
Server is running Java 17.0.8.1
AMD Ryzen 9 5950x
16GB of 64GB RAM allocated to MC
Running on NVME RAID.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Floofle** [comment]
Can additionally confirm this, with Forge 43.3.0 and the same Aether version/ no optifine/custom modpack. This issue appears with the config option "Disables falling into the Overworld" set to TRUE and before any player on the server has even entered the aether. 

See(as one example); https://spark.lucko.me/IJLpxSULDc

EDIT: notably, seems to happen to a player that has placed the portal and then not gone in. will update if that fixes the issue.

**Comment by bconlon1** [comment]
I need to rearrange the checks starting here: https://github.com/The-Aether-Team/The-Aether/blob/cc76cf7ebda0f55356623e7a984dc8bf02a45b5f/src/main/java/com/aetherteam/aether/event/hooks/DimensionHooks.java#L174

**Comment by bconlon1** [comment]
A commit has been pushed that may fix this issue, it will need testing: https://output.circle-artifacts.com/output/job/0dcf30b1-84de-47b2-b572-fc07fc27bbe2/artifacts/0/~/project/build/libs/aether-1.20.1-1.0.0-beta.1.4-neoforge.jar

**Comment by Floofle** [comment]
Could we get the beta jar with the fix for 1.19.2 as well, or would the fix be the same if I backported the relevant commit and built it myself?

**Comment by bconlon1** [comment]
I can backport the fix for testing, I will get back to you once that is done

**Comment by Floofle** [comment]
Thank you!

**Comment by bconlon1** [comment]
@Floofle https://output.circle-artifacts.com/output/job/22a378a0-5497-4266-9e2a-08a7fb437ba7/artifacts/0/~/project/build/libs/aether-1.19.2-1.0.0-beta.1.3-forge.jar apologies for the wait

**Comment by Floofle** [comment]
Initial test shows it's fixed. Will keep fiddling and see.
