### ISSUE TITLE
Bug: Game Crashes

### ISSUE THREAD

**Issue by YejiYeah** [Gilded-Games/The-Aether#1846]
### Other Type

The game crashes:  "soundInstance" is null

### What Type of Bug Is This?

None

### Forge Version

47.2.0

### The Aether Version

1.0.0 beta 1.4

### Is This Bug a Conflict With Another Mod?

I have removed all the mods related to "sounds" and fancy menu and it keeps crashing, there are more mods in the modpack: Yes Nicer Minecraft 1.1.6: https://www.curseforge.com/minecraft/modpacks/yes-nicer-mc-forge-1

### Client Log

https://gist.github.com/SaraXianLin/9af35d607db327a7be35f113799e2c9b

### Crash Report (if applicable)

https://gist.github.com/SaraXianLin/079d19f4ce4e43dac6274a4fc04358d9

### Steps to Reproduce

 Reproduce the crash:

1. Create a new world in the YNM modpack
2. Create the portal and go inside
3. the game crashes while in the Aether

### What You Expect To Happen

I hope it stop crashing

### What Actually Happened

This happens everytime, when I join the Aether in the next 1 -4 min even I walk or just stay near the portal.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I think this is an issue with Team Midnight Dust's Visual Overhaul mod, they should be checking if `soundInstance != null` here: https://github.com/TeamMidnightDust/VisualOverhaul/blob/e9539ba28fa60f023ff910480bbce31ec79de19b/common/src/main/java/eu/midnightdust/visualoverhaul/mixin/MixinSoundSystem.java#L23C1-L26C10
