### ISSUE TITLE
Bug: Infinite loading to aether on Vivecraft

### ISSUE THREAD

**Issue by Trelsonowsky** [Gilded-Games/The-Aether#185]
Both VR and non-VR versions of Vivecraft can't load to Aether dimension. It just says "Ascending to Aether" and 
game is NOT not-responding.

**Comment by bconlon1** [comment]
Should probably be reported to the Vivecraft GitHub at some point if it hasn't already.

**Comment by bconlon1** [comment]
Can only be tested once Vivecraft is ported to Forge 1.18

**Comment by bconlon1** [comment]
Considering the fact Vivecraft is still not on Forge 1.18 and code has probably changed quite a bit on both ends since this issue's creation, I'm just gonna close this.
