### ISSUE TITLE
Bug: Custom rarity is missing localization

### ISSUE THREAD

**Issue by Foozey** [Gilded-Games/The-Aether#1864]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

47.2.16

### The Aether Version

1.20.1-1.0.0-beta.1.4-neoforge

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

1. Get item with The Aether's custom rarity tier.
2. Display localized name somehow (in my screenshot I'm using the tooltip renderer from Loot Beams).

### What You Expect To Happen

Name should have a translated form, eg. "Aether Loot".

### What Actually Happened

Name wasn't localized as shown in image.

### Additional Details

![image](https://github.com/The-Aether-Team/The-Aether/assets/68371808/7610a1d3-c026-44a7-831a-de6b63a77662)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Foozey** [comment]
Comparison image from Apotheosis:
![image](https://github.com/The-Aether-Team/The-Aether/assets/68371808/99311806-6a82-41cf-bedc-1efc823b622d)

**Comment by bconlon1** [comment]
The functionality for allowing localization does not yet exist in the Loot Beams mod so there is nothing I can do yet. This has been talked about with the developer though (who originally brought up this issue to us) and we'll fix it once the support is there.

**Comment by bconlon1** [comment]
The support is now being worked on at Loot Beams end and I need to test working on Aether compat so I'm reopening this issue so I remember to do that.
