### ISSUE TITLE
Bug: Aether dimension appears as eternal night with shaders enabled

### ISSUE THREAD

**Issue by caryosyntrips** [Gilded-Games/The-Aether#1876]
### What Feature Types Apply to This Bug?

Art

### What Type of Bug Is This?

Compatibility

### Forge Version

43.3.5

### The Aether Version

1.19.2-1.0.0-beta.2-forge

### Is This Bug a Conflict With Another Mod?

oculus 1.19.2-1.6.9

### Client Log

https://gist.github.com/caryosyntrips/00fc9619dbefe34a65a30fa97ccd5197

### Steps to Reproduce

1. Launch Minecraft
2. Load World
3. Enter Aether

### What You Expect To Happen

The world is bright as day, with the sun directly overhead.

### What Actually Happened

The sun is overhead, but the lighting is consistent with nighttime.

### Additional Details

When time is changed manually, the vanilla sun and the shader sun overlay and skybox move at different speeds, resulting in broken shadow effects.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This is an issue with the shaders, and not something we can fix

**Comment by Bmedina82** [comment]
Had this issue with complementary shaders, updating the shaders to r5.1 or above fixed it for me.
