### ISSUE TITLE
Bug: Aether Multiplayer not working at all.

### ISSUE THREAD

**Issue by Pantheris2019** [Gilded-Games/The-Aether#1877]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

43.3.5

### The Aether Version

beta.2

### Is This Bug a Conflict With Another Mod?

No

### Client Log

No Client Log, Multiplayer Only

### Crash Report (if applicable)

https://gist.github.com/Pantheris2019/d7f612e6b3ac14d6b196d26e51a3066b

### Steps to Reproduce

Okay so all you need to do is put Aether in a server, and load that up.
Second, try to connect to the server
Third, get connection reset error

### What You Expect To Happen

Server allows connection.

### What Actually Happened

Server crashes on join and I get booted out of connecting.

### Additional Details

I am playing on a modpack I am developing myself.  This is an issue that I am encountering myself, and therefore am tracking the issues myself.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This will be fixed in a beta hotfix release soon, in the mean time use this build: https://output.circle-artifacts.com/output/job/214414f1-931d-4cd9-8001-ab593af4a9fe/artifacts/0/~/project/build/libs/nitrogen_internals-1.19.2-0.2.2-forge.jar

**Comment by Pantheris2019** [comment]
Thanks man!  You are great!  Where do I put this though?
