### ISSUE TITLE
Feature Request: Life Shard configuration

### ISSUE THREAD

**Issue by Yirmiri** [Gilded-Games/The-Aether#1882]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A configuration option to be able to disable life shards on servers would be helpful!

### Why Should It Be in the Mod?

I currently am running a server and want to keep people from going above 20 hit points. I feel many others could find use for it aswell as this especially could get very powerful and break balance when paired with other mods that have items to increase the maximum amount of hit points.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
You could set the configuration option for max usable life shards to 0.
