### ISSUE TITLE
Bug: Graphics mods cause crashes randomly?

### ISSUE THREAD

**Issue by MsVella** [Gilded-Games/The-Aether#1891]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Graphics / Rendering

### What Type of Bug Is This?

Crash

### Forge Version

43.3.0 (1.19.2)

### The Aether Version

1.0.0, Beta 2.2 (1.19.2)

### Is This Bug a Conflict With Another Mod?

Possibly Embeddium

### Client Log

https://gist.github.com/MsVella/80f782cca762758935237201e88bd1f4

### Crash Report (if applicable)

https://gist.github.com/MsVella/41f7cef2263925952a351e679eb44f9e

### Steps to Reproduce

Unfortunately this appears to happen at random and therefore i cannot give easy steps to reproduce, but I've found that random worlds are afflicted with this issue with this pack of mods (i'm using the Ruincraft & create modpack which I made, with the addition of aeroblender, aether enhanced extinguishing, aether, aether redux and deep aether, but this issue persists with just the aether installed over the pack.), if you would like a copy of my multiplayer server's save for testing, please let me know!

### What You Expect To Happen

The game to run smoothly without issue.

### What Actually Happened

The game crashes when turning in randomly directions, seemingly as if something specific is crashing when rendered, but sometimes this direction changes.

### Additional Details

After starting the world without the aether (on a backup) and reinstalling it a subsiquent time the crashing "direction" changed, i think it's likely aether is causing the game to crash when *something* is being rendered sue to either modernfix or embeddium, but i'm not code literate enough to tell what.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
If I am to make a guess bere, its that Malum's Runewood sign does not have a wood type material properly registered, only because I've seen a similar log from that kind of situation with IC2C, but this seems to also be caused by Rubidium so it's slightly different.

**Comment by bconlon1** [comment]
Found it on their issue tracker: https://github.com/SammySemicolon/Malum-Mod/issues/153.

**Comment by MsVella** [comment]
Thanks!
