### ISSUE TITLE
Feature Request: Remove Enchanting Glint from Healing Stone

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1913]
### What Feature Types Apply to This Request?

Art

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To remove the Enchanting Glint from Healing Stones

### Why Should It Be in the Mod?

It doesn't fit the item and just obstructs the texture. In the original mod the Healing Stone also never had Enchanting Glint. This was  added by Modding Legacy into the 1.7.10 and 1.12.2 builds.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
The Healing Stone had the glint in the 1.2.5 version.
