### ISSUE TITLE
Crystal Trees only have 2 logs

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#192]
![crystals](https://user-images.githubusercontent.com/81527321/133083171-3a66b9e0-04c2-4d72-ba5a-0a9db78d259b.png)

**Comment by Builderdog841** [comment]
A Crystal Tree without leaves

**Comment by raptor494** [comment]
Can you provide a seed/coordinates of that screenshot?

**Comment by bconlon1** [comment]
i think this is an nbt issue and needs more logs added... unless the meaning of this issue is that this crystal tree literally spawned without leaves this issue report isn't clear.
