### ISSUE TITLE
Bug: two background musics playing simultaneously

### ISSUE THREAD

**Issue by nu290** [Gilded-Games/The-Aether#1921]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Annoyance

### Forge Version

47.2.0

### The Aether Version

1.20.1-1.0.0-neoforge

### Is This Bug a Conflict With Another Mod?

Suspected: Music Manager 1.3.13(Neo)Forge 1.20

### Steps to Reproduce

it happens once in about 5 music pieces, spontaneously as long as the player is in the aether

### What You Expect To Happen

one music plays until it ends, then another music plays after a few seconds as set by the music manager

### What Actually Happened

while one music is playing and has not ended, another music starts playing to overlap with the first music

### Additional Details

i suspect the music files metadata to specify wrong durations

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by nu290** [comment]
i would like to add that just as often, a music piece abruptly stops and another starts playing. i suspect this to be related

**Comment by Builderdog841** [comment]
From my experience this isn't a conflict and also happened to me with only the base mod installed. It seems to only happen when the player enters a different biome.

**Comment by bconlon1** [comment]
Is this in creative or survival mode?

**Comment by bconlon1** [comment]
Also have you tweaked any config variables from the Aether or Music Manager, or modified the Aether's biome data?

**Comment by nu290** [comment]
when confirming this, it was in creative. no config variables were tweaked in the aether. for music manager, i have shortened the music interval to min 4 max 6. another mod i now suspect is Deep Aether that adds biomes. i'll test that

**Comment by nu290** [comment]
further testing revealed that this bug occurs when i switch between creative and survival modes using F3+F4. biomes do not appear relevant.
i confirmed this with vanilla1.20.1 + neoforge47.1.88 + aether1.20.1-1.0.0-neoforge + music manager1.20.1-1.3.13, and no extra mods.
i could not properly test without music manager because the music is too infrequent.

this did not result in the abrupt stopping of a music piece for another to begin. that phenomenon did not occur at all during this test session

**Comment by Builderdog841** [comment]
Okay, I actually found what's causing this issue. In the biome json files the "replace_current_music" field is set to true which means that it resets the music delay everytime a player switches biomes. So this issue should be fixable by simply setting it to false
