### ISSUE TITLE
no 1.18 version

### ISSUE THREAD

**Issue by Aceplante** [Gilded-Games/The-Aether#1923]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

nonexistent version

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

1.18.2

### The Aether Version

n/a

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

install forge 1.18.2
search aether

### What You Expect To Happen

There should be a version available for 1.18.2

### What Actually Happened

There was not

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Alexmasonseals** [comment]
the team has no plans on supporting 1.18.2
