### ISSUE TITLE
Bug: Emissive bits and layers still render on a moa when said moa is invisible

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#1924]
### What Feature Types Apply to This Bug?

Entity

### Other Type

m a o

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.0

### The Aether Version

release 1.0

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

apply a moa donor skin that has emissive bits
splash your moa with an invis potion
enjoy

### What You Expect To Happen

moa to go completely invisible (with the saddle still being rendered)

### What Actually Happened

the emissive bits n layers still show up

### Additional Details

![image](https://github.com/The-Aether-Team/The-Aether/assets/75763838/62072dd8-b1f0-4001-8159-95e13358869f)
![image](https://github.com/The-Aether-Team/The-Aether/assets/75763838/c64dffba-3d8b-44c1-941c-5dbc43181214)
![image](https://github.com/The-Aether-Team/The-Aether/assets/75763838/88920262-fa16-4e02-9cb2-eb3a01b2e75e)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Apparently Horse Saddles go invisible, so the solution to this will likely be making Moa Saddles always go invisible even for default as well as the glow layer.
