### ISSUE TITLE
Bug: Hammer of Notch Text doesn't render with the Remedy and Inebration Vignette

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#1936]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Design

### Forge Version

47.1.79

### The Aether Version

1.20.1-1.0.0

### Steps to Reproduce

Use a Hammer of Notch
Give yourself the Remedy or the Inebration Effect
See how the text above the Cooldown bar doesn't render when you have vignette of these effects active

### What You Expect To Happen

For the text to render

### What Actually Happened

It didn't

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Trico-Everfire** [comment]
![image](https://github.com/The-Aether-Team/The-Aether/assets/55441008/4fe500d7-83f4-4056-a228-99db0aa412e5)

It seems to still work. However, it seems to fade along with the effect as it wears off. Eventually becoming invisible.
![image](https://github.com/The-Aether-Team/The-Aether/assets/55441008/5433197e-6b12-401e-971b-fe7bbd79a132)
