### ISSUE TITLE
Bug: Water lakes rarely generate

### ISSUE THREAD

**Issue by 0Navis0** [Gilded-Games/The-Aether#1948]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.2.19

### The Aether Version

1.20.1-1.0.0

### Steps to Reproduce

Just go in the Aether and you will quickly notice how hard it's to find a water lake.

### What You Expect To Happen

Water lakes should generate more often, at least as much as in Overworld.

### What Actually Happened

Water lakes rarely generate in Aether, compared to the Overworld.

### Additional Details

It seems that water lakes have as much difficulties to generate in Aether addon biomes.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Water lakes in the Aether are not handled in the same way as vanilla does. We do not plan to increase their generation rate.

**Comment by 0Navis0** [comment]
Why not simply increase the generation rate of water lakes? It would be a pretty simple way to fix this issue.

**Comment by Builderdog841** [comment]
because it doesn't look good

**Comment by bconlon1** [comment]
The current rate was decided to be enough without becoming an eyesore on the landscape.

**Comment by 0Navis0** [comment]
Maybe you can make ask what the people think about it in the server if you're not sure about it.
