### ISSUE TITLE
 Bug: <structure>

### ISSUE THREAD

**Issue by Math0uu** [Gilded-Games/The-Aether#1951]
### What Feature Types Apply to This Bug?

Block, World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

47.2.0

### The Aether Version

1.0.0

### Is This Bug a Conflict With Another Mod?

no

### Crash Report (if applicable)

 https://mclogs.minestrator.com/ldkZhNu

### Steps to Reproduce

1: go in the aether dimension
2: generate the aether map by traveling
3: a structure will try to generate but it can't get generate
(sorry for my bad english)

### What You Expect To Happen

The structure was suposed to get generate

### What Actually Happened

The server is crashing because the structure can't get generate

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This appears to be a crash due to the Deep Aether addon, not the Aether itself.
