### ISSUE TITLE
Bug: Small item duplication bug with Ketket's Graves

### ISSUE THREAD

**Issue by burdoto** [Gilded-Games/The-Aether#1952]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Design

### Forge Version

arclight-1.20.1-1.0.2-SNAPSHOT-71acd73 (MC: 1.20.1)

### The Aether Version

aether-1.20.1-1.0.0-neoforge.jar

### Is This Bug a Conflict With Another Mod?

https://www.planetminecraft.com/data-pack/ketket-s-graves-secure-your-items/

### Client Log

https://paste.atlauncher.com/view/3d5c8aa6-b10d-4687-8689-c1b22b3ca824

### Steps to Reproduce

1. Wear Aether cosmetics (such as Golden Pendant, Golden Ring, Zanite Ring are known affected)
2. Die
3. You might still have your items, as well as have them inside the Gravestone

### What You Expect To Happen

no item duplication

### What Actually Happened

item duplication

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Our accessories behavior is handled by Curios API, so this would be a bug between that mod and the data pack you are using.
