### ISSUE TITLE
Translation Updates: <Update zh_cn.json of The Aether>

### ISSUE THREAD

**Issue by LuminaHeinsborough** [Gilded-Games/The-Aether#1964]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Translation

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Updating translations of zh_cn.json.

### What's the content?

"dimension.aether.the_aether": "天境",
"structures.aether.bronze_dungeon": "青铜地牢",
"structures.aether.gold_dungeon": "黄金地牢",
"structures.aether.large_aercloud": "大境云",
"structures.aether.silver_dungeon": "白银地牢",

### Does This Feature Improve Compatibility With Another Mod?

Yes. Nature's Compass and Explorer's Compass

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I should add these to the base English translation as well. Which I should probably do through Nitrogen.
