### ISSUE TITLE
Skyroot bed texture glitch

### ISSUE THREAD

**Issue by Aceplante** [Gilded-Games/The-Aether#1968]
### What Feature Types Apply to This Bug?

Art

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.2.19

### The Aether Version

1.1.0

### Is This Bug a Conflict With Another Mod?

Probably not

### Steps to Reproduce

Place skyroot bed

### What You Expect To Happen

It should look like a bed

### What Actually Happened

![bed](https://github.com/The-Aether-Team/The-Aether/assets/101857505/44789238-65a8-4429-82b0-57182d3e0e7b)
The side is z fighting between the bed and planks texture

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by ZolaKluke** [comment]
Someone mentioned this in the discord server, it's a bug with the better beds mod
![image](https://github.com/The-Aether-Team/The-Aether/assets/6497775/9aadfb46-690d-4569-891d-bb526e14b6ac)

**Comment by Aceplante** [comment]
I dont have that one though, I dont have any mods that should be affecting the textures of beds like that. Still, if you're saying it doesnt happen with just your mod, I suppose it has to be an incompatibility of some kind

**Comment by bconlon1** [comment]
Could you please provide a list of installed mods as well as the game logs.

**Comment by Alexmasonseals** [comment]
> I dont have that one though, I dont have any mods that should be affecting the textures of beds like that. Still, if you're saying it doesnt happen with just your mod, I suppose it has to be an incompatibility of some kind

embeddium++ added a "fast beds" optimization that messes with beds on it's latest update, you could either disable this optimization or remove the mod.
