### ISSUE TITLE
Bug: Attempting to use Aether biomes in a Superflat world defaults to minecraft:plains.

### ISSUE THREAD

**Issue by raptor494** [Gilded-Games/The-Aether#197]
**(No longer relevant)**
> **Steps to reproduce:**
> 1. Start creating a new superflat world
> 2. Edit the preset, change the default preset biome from `minecraft:plains` to `aether:aether_skylands`
> 3. Click "Done"
> 
> Log: [debug.log](https://github.com/Gilded-Games/The-Aether/files/7198332/debug.log)

**Comment by bconlon1** [comment]
Might be fixed by registering biomes in code, which is being done in the 1.18.2 port.
