### ISSUE TITLE
Feature Request: Config to disable custom Hammer of Kingbdogz cooldown bar

### ISSUE THREAD

**Issue by sm644me** [Gilded-Games/The-Aether#1978]
### What Feature Types Apply to This Request?

Config, Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The Aether adds a custom cooldown bar for the Hammer of Kingbdogz. I would like to request a client config option to hide this bar from view (not to disable the cooldown, that already exists in server config).

### Why Should It Be in the Mod?

This bar can feel out of place in modpacks that add many items with cooldowns, especially since Minecraft has added a cooldown overlay to items such as Ender Pearls. A client config option to disable this bar would be a nice option to have for consistency with modern Minecraft and its mods.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by PinkLasagna03** [comment]
Yes please, the cooldown overlay is so annoying and tbh very out of place
