### ISSUE TITLE
Bug: Portal keeps breaking and relighting underwater

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#1980]
### What Feature Types Apply to This Bug?

System

### Other Type

P O R T A L

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.0

### The Aether Version

release1.1.0

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

place an aether  portal underwater

### What You Expect To Happen

portal would be broken and wouldnt light up

### What Actually Happened

portal kept breaking and lighting up

### Additional Details

https://youtu.be/HCqh0w2P_RQ (portal related video)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Maybe I need to make it so water can't break the portal.
