### ISSUE TITLE
Bug: There's no slot for gloves in curios

### ISSUE THREAD

**Issue by Sketiq** [Gilded-Games/The-Aether#1986]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Design

### Forge Version

47.2.19

### The Aether Version

1.20.1-1.1.0

### Is This Bug a Conflict With Another Mod?

No I think

### Steps to Reproduce

I tried to wear gloves and it works but there's no glove slot

### What You Expect To Happen

Fix a bug where there's no glove slot

### What Actually Happened

You can wear the gloves but there's no glove slot

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Do you have any other mods installed?

**Comment by Sketiq** [comment]
> Do you have any other mods installed?

Yep I'm playing on my modpack that I'm going to publish in some time.

**Comment by bconlon1** [comment]
Could you provide your mods list? Last time I saw this occur was also within a modpack.

**Comment by Sketiq** [comment]
> Could you provide your mods list? Last time I saw this occur was also within a modpack.

[mods.txt](https://github.com/The-Aether-Team/The-Aether/files/13983289/mods.txt)
here

**Comment by Sketiq** [comment]
> > Could you provide your mods list? Last time I saw this occur was also within a modpack.
> 
> [mods.txt](https://github.com/The-Aether-Team/The-Aether/files/13983289/mods.txt) here

Oh now I noticed that rings doesn't go in ring slot but somewhere else, like there's other slot for it

**Comment by Sketiq** [comment]
![image](https://github.com/The-Aether-Team/The-Aether/assets/129682530/e49f1f2a-c93a-4295-b4d6-f03443f7f63f)
Okay I found there's other slots for aether items, but slots are in wrong positions?

**Comment by bconlon1** [comment]
You will have to narrow down which other mod is causing this, since this is definitely a mod incompatibility.

**Comment by Sketiq** [comment]
> You will have to narrow down which other mod is causing this, since this is definitely a mod incompatibility.

I installed my modpack again and it works now, idk why.
