### ISSUE TITLE
Feature Request: Altar stores XP

### ISSUE THREAD

**Issue by Aeonsteel** [Gilded-Games/The-Aether#1995]
### What Feature Types Apply to This Request?

Block, System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The Altar should store XP inside of it, filled by crafting items. Hoppers could take items out, without lowering the XP output. When an item is taken out of the Output slot, or the block is broken, the stored xp should spawn as an orb and be recieved by the player.

### Why Should It Be in the Mod?

The vanilla furnace (and it's specialized variants) all do this, and as the Altar is an analogue to the furnace, it should do it as well.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
I need a video of this since I cannot reproduce it.
