### ISSUE TITLE
Bug: "moaType" is null

### ISSUE THREAD

**Issue by toErIpNid** [Gilded-Games/The-Aether#1999]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

47.2.0

### The Aether Version

1.20.1-1.1.0-neoforge.jar

### Is This Bug a Conflict With Another Mod?

Don't know.

### Client Log

https://gist.github.com/toErIpNid/c97eebba14874006f3d29eab1eb8fa69

### Crash Report (if applicable)

Crash log was not produced.

### Steps to Reproduce

1. Generate a world on my modpack.
2. Fly around in creative in a random direction.
3. The game randomly crashes after a bit.

### What You Expect To Happen

It not to crash.

### What Actually Happened

It crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
I've happened to already push a commit that fixes this, so the next release will no longer have this issue when it comes out.
