### ISSUE TITLE
Feature Request: Life Shard Reset Command/Item

### ISSUE THREAD

**Issue by N7NobodyCats** [Gilded-Games/The-Aether#2000]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Command?

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

i used too many shards after changing the amount in the config, i didnt realize 10 shards would equal 40 hearts total, so i changed it to 20 allowed consumable and now have over 60 hearts, i wanna reset so my max is 40, i cannot find a way to reset the life shard effect, and would very very very much like to have one. please add a way to reset or otherwise a way to remove the hearts i now have.

### Why Should It Be in the Mod?

well why not? it should have been something in there to begin with idk, something that can add more hearts? i feel like it makes sense to have a way to remove/undo it as well.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
`/aether player life_shards set [username] 0` should let you do this.
