### ISSUE TITLE
Feature Request: Disable insomnia for invisible players

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#2001]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

When rendered invisible by an invis cape, players should not have phantoms spawning on them.

### Why Should It Be in the Mod?

Phantoms cannot see invisible players anyway. Also, they can attack visible players who did not cause them to spawn.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Invisibility doesn't prevent Phantom spawning in vanilla either, so it doesn't make sense for it to do that with the Invisibility Cloak.
