### ISSUE TITLE
Feature Request: Add description to effects

### ISSUE THREAD

**Issue by FarLemon** [Gilded-Games/The-Aether#2016]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Effect

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To add descriptions to the current and future effects. That currently being 'Inebriation' and 'Remedy'. I believe it's under effect.[mod_id].[effect_name].description.

### Why Should It Be in the Mod?

To enhance understanding of what the effects do, and to further the integration with recipe view and description mods.

### Does This Feature Improve Compatibility With Another Mod?

JEED, EMIffect, Any other Effect Descriptor mod. Any version

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Status:
- [x] 1.20.2
- [x] 1.20.1
- [x] 1.19.4
- [x] 1.19.2
