### ISSUE TITLE
Feature Request: Tag for Gravitite toolset crafting items (and possibly other materials too for consistency)

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2020]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A tag for items used to create Gravitite tools, weapons and armor (and possibly for consistency the other materials as well)
note: I can most likely (and probably will) make a pull request for this in case that’s helpful

### Why Should It Be in the Mod?

So that addons can change the materials used for different toolsets and keep compatibility with other addons (the specific use case I have in mind: I’d like to add Gravitite Ingots to my addon)

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Status:
- [x] 1.20.2
- [x] 1.20.1
- [x] 1.19.4
- [x] 1.19.2
