### ISSUE TITLE
Bug: Aether mod prevents setting bedrock on fire for Grains of Infinity

### ISSUE THREAD

**Issue by KABLUEE2** [Gilded-Games/The-Aether#2022]
### What Feature Types Apply to This Bug?

Block, Entity, Item, System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.2.0

### The Aether Version

1.2.0

### Is This Bug a Conflict With Another Mod?

Ender IO 6.0.23-alpha

### Client Log

https://gist.github.com/KABLUEE2/09b94cd7aa64612058dfd8b998d3e0d2

### Steps to Reproduce

Happens everytime I try to do it.

Step 1: Find a piece of bedrock in the overworld
Step 2: Light a single or multiple piece of bedrock on fire with flint and steel
Step 3: Wait for the fire to extinguish naturally
Step 4: No grains spawn from it at all when they are supposed to

### What You Expect To Happen

What is supposed to happen is that in the Ender IO mod, you are supposed to light bedrock on fire to obtain an item called 'Grains of Infinity'. Ender IO also has another way of obtaining Grains of Infinity where you have to have a flint and steel in your off-hand, and a piece of deep slate in your main hand, you are then meant to right-click either a piece of obsidian, or grind stone with the deep slate in your hand however, this also does not work.

### What Actually Happened

Lighting the bedrock on fire results in no grains of infinity spawning at all.

### Additional Details

A few people have said in a different post on the Ender IO github that the Aether mod is the potential cause of this, however I myself could not pinpoint exactly what is causing this. 

Below are some relevant links to this issue:
https://github.com/Team-EnderIO/EnderIO/issues/603
https://github.com/BBoldt/ThePioneers/issues/95
 https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4586 <---- **this post has a nice workaround for the issue by using the crafttweaker mod** 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Fixed on EnderIO's end.
