### ISSUE TITLE
Bug: Valkyrie Queen Crash

### ISSUE THREAD

**Issue by Mikeatron-User** [Gilded-Games/The-Aether#2031]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

47.2.0

### The Aether Version

1.20.1-1.2.0-neoforg

### Crash Report (if applicable)

https://mclo.gs/hrbKSKV

### Steps to Reproduce

1. Fight the Valkery Queen

### What You Expect To Happen

For it not to crash

### What Actually Happened

It crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by ImReallyCreative** [comment]
I'm also experiencing this bug. The crash seems to trigger once the Queen gets below ~330 health.
Crash log: [https://mclo.gs/qIO231t](https://mclo.gs/qIO231t)
