### ISSUE TITLE
Bug: Entities like Zephyrs still have some issues with spawning in spaces they shouldnt

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#2035]
They seem to still be able to spawn in rooms and enclosed areas that aren't fully in view of skylight.

**Comment by indrada** [comment]
I've been unable to reproduce this bug. Can you specify how this bug was produced or add screenshots of the location where the zephyr spawned?
![2024-06-09_01 02 35](https://github.com/The-Aether-Team/The-Aether/assets/61097641/1858ea34-24fd-49ba-8b7c-bcfd86ad7a03)
