### ISSUE TITLE
Feature Request: Simplify Dungeon Block Item Model Code

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#2054]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Currently the entire Item Model gets generated for each individual block again. By making a template model for the Dungeon Block Model and then have it be the parent model of the Item Model, you would simplify the code a lot

### Why Should It Be in the Mod?

It improves code

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Probably not going to bother with this since it's so minor of a code change.
