### ISSUE TITLE
Feature Request: A config for making Aether Music more common

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#2055]
### What Feature Types Apply to This Request?

Audio

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To have a proper config for the aether music frequency

### Why Should It Be in the Mod?

Having a way of listening to the music more frequently in game is very nice for the atmosphere

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This is configurable in biome jsons
