### ISSUE TITLE
Bug: PlayerRevive incompatibility, Player can bypass death

### ISSUE THREAD

**Issue by CreativeMD** [Gilded-Games/The-Aether#2061]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Compatibility

### Forge Version

47.2.20

### The Aether Version

1.2.0

### Is This Bug a Conflict With Another Mod?

PlayerRevive

### Steps to Reproduce

* Open a world in singleplayer
* Open the world to LAN
* type in `/kill`
* Exit to main menu
* Log back in

### What You Expect To Happen

Deathscreen and being forced to hit respawn (then obviously return to spawn location)

### What Actually Happened

Sometimes no death screen. Player drops items, but stays in same location.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by CreativeMD** [comment]
This issue has been reported here: https://github.com/CreativeMD/PlayerRevive/issues/142
When a player disconnects while bleeding/ being knocked out the player will be killed immediately. Code for it can be found here: https://github.com/CreativeMD/PlayerRevive/blob/1.20/src/main/java/team/creative/playerrevive/server/ReviveEventServer.java#L73

Somehow the aether mod changes this behavior. I have looked through the code a little bit, maybe this is caused by this?https://github.com/The-Aether-Team/The-Aether/blob/0a84184dafcde7c86ef6f9848173d87c012a59ca/src/main/java/com/aetherteam/aether/capability/player/AetherPlayerCapability.java#L628-L633

In Regards
CreativeMD

**Comment by bconlon1** [comment]
Solution offered at https://github.com/CreativeMD/PlayerRevive/issues/142#issuecomment-2062919322, if that doesn't work then I can reopen this issue and fix it on our end.
