### ISSUE TITLE
Bug: <Removal Of Mod caused my world to corrupt on itself and wont open unless i install the mod back (don't know if it's necessarily a bug)>

### ISSUE THREAD

**Issue by MatchaMysteries** [Gilded-Games/The-Aether#2063]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

1.20.1

### The Aether Version

1.20.1

### Client Log

https://gist.github.com/MatchaMysteries/514146498f2114d89d1e7ffa41172d87

### Steps to Reproduce

1. Download the 1.20.1 version of aether
2. Put it in mod file.
3. Open game and load world.
4. Exit world saving it as is.
5. Get rid of aether.
6. Go back on minecraft and open up world
7. World won't load due to error.

### What You Expect To Happen

It uninstalls the mod and I would be able to play as usual without it.

### What Actually Happened

It doesn't let me on the world.

### Additional Details

![Screenshot 2024-03-17 205800](https://github.com/The-Aether-Team/The-Aether/assets/163776113/393122c8-1570-4b3a-96a0-62903d0cbcd1)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
You'll have to get an NBT editor like NBTExplorer and remove the dimension from your level.dat. This explanation is for an older version but I believe it is still accurate: https://github.com/MinecraftForge/MinecraftForge/issues/8800#issuecomment-1178330353
