### ISSUE TITLE
Bug: Advancement Sound Overrides always choose the general advancement sound

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2069]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.2.0

### The Aether Version

1.3.0 (1.19.2, likely affects other versions)

### Steps to Reproduce

1: Open any world
2: Give yourself one of the advancements for beating a boss (not including the gold one ofc as the base mod does not have a unique one for this)
3: Observe that the correct sound does not play

### What You Expect To Happen

The correct sound would play

### What Actually Happened

The general advancement sound played rather than the override

### Additional Details

Using the debugger, I was able to figure out that this is caused by the first override to match the parameters being used, which is always the general one as it matches all aether advancements.

~~A possible fix for this might be to implement an advancement override tag called something around the lines of `#aether:low_priority`, and if the override chosen is in the tag, the method keeps checking the others in case there is another that also overrides the sound, in which case it uses that instead (and maybe continues checking if that one is also in the tag)~~

Better solution (keeping the other just in case it could be useful): Maybe the advancement sound overrides could have an integer field, called `priority`, and then the sound would use the highest priority override which matches, or perhaps a random one if there are multiple with the same priority that match? not sure

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
darn it
