### ISSUE TITLE
Bug: Exit code -1073741819

### ISSUE THREAD

**Issue by MrAyfan** [Gilded-Games/The-Aether#2077]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

47.2.20

### The Aether Version

1.3.1

### Client Log

https://pastebin.com/SbMpumjA

### Steps to Reproduce

Just change dimensions (like: Overworld <--> Nether) Single player or multiplayer

### What You Expect To Happen

Don't crash and travel through dimensions

### What Actually Happened

The game is freezing for 5 seconds and close. Minecraft launcher says exit code -1073741819

### Additional Details

I try to remove one by one mods to try to find the one but nothing

I just add Aether to the modpack on a existing world

List of mods:
aether-1.20.1-1.3.1-neoforge.jar
alexsmobs-1.22.8.jar
amendments-1.20-1.1.11.jar
Aquaculture-1.20.1-2.5.1.jar
architectury-9.2.14-forge.jar
balm-forge-1.20.1-7.2.2.jar
BiomesOPlenty-1.20.1-18.0.0.592.jar
born_in_chaos_[Forge]1.20.1_1.2.jar
Botania-1.20.1-443-FORGE.jar
citadel-2.5.4-1.20.1.jar
corpse-forge-1.20.1-1.0.12.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CraftTweaker-forge-1.20.1-14.0.36.jar
CreativeCore_FORGE_v2.11.25_mc1.20.1.jar
cristellib-1.1.5-forge.jar
Croptopia-1.20.1-FORGE-2.3.2.jar
CroptopiaAdditions-1.20.1-FORGE-2.2.jar
curios-forge-5.7.2+1.20.1.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
EasierSleeping-1.20.1-2.1.3.jar
elevatorid-1.20.1-lex-1.9.jar
embeddium-0.3.1+mc1.20.1.jar
emotecraft-for-MC1.20.1-2.2.7-b.build.50-forge.jar
EpheroLib-1.20.1-FORGE-1.2.0.jar
fancymenu_forge_3.1.2_MC_1.20.1.jar
ferritecore-6.0.1-forge.jar
framework-forge-1.20.1-0.6.27.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.1.5.jar
ftb-ranks-forge-2001.1.3.jar
geckolib-forge-1.20.1-4.4.4.jar
goblintraders-forge-1.20.1-1.9.3.jar
handcrafted-forge-1.20.1-3.0.6.jar
hiddennames-1.20.1-1.0.2.jar
InventoryProfilesNext-forge-1.20-1.10.9.jar
ironchest-1.20.1-14.4.4.jar
item-filters-forge-2001.1.0-build.59.jar
Jade-1.20.1-forge-11.7.1.jar
jei-1.20.1-forge-15.3.0.4.jar
journeymap-1.20.1-5.9.18p1-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.10.0-all.jar
libIPN-forge-1.20-4.0.1.jar
LOG.txt
LuckPerms-Forge-5.4.102.jar
mcw-furniture-3.2.2-mc1.20.1forge.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
modernfix-forge-5.15.0+mc1.20.1.jar
moonlight-1.20-2.11.9-forge.jar
morevillagers-forge-1.20.1-5.0.0.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
oculus-mc1.20.1-1.6.15.jar
Paraglider-forge-20.1.3.jar
Patchouli-1.20.1-84-FORGE.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
resourcefullib-forge-1.20.1-2.1.23.jar
SimpleBackups-1.20.1-3.1.4.jar
sophisticatedbackpacks-1.20.1-3.20.3.1034.jar
sophisticatedcore-1.20.1-0.6.12.589.jar
supplementaries-1.20-2.8.6.jar
TerraBlender-forge-1.20.1-3.0.1.4.jar
Towns-and-Towers-1.12-Fabric+Forge.jar
Twigs-1.20.1-3.1.0.jar
twilightforest-1.20.1-4.3.2145-universal.jar
waterframes-1.20.1-2.0.0-beta5.1.jar
watermedia-2.0.28.jar
waystones-forge-1.20-14.1.3.jar
WI-Zoom-1.5-MC1.20.1-Forge.jar
worldedit-mod-7.2.15.jar.disabled
yawp-1.20.1-0.0.2.9-beta3-forge.jar

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by MrAyfan** [comment]
Problem is not happening  when generating a new world......

**Comment by bconlon1** [comment]
Use Forge 47.1.3, anything beyond that is not guaranteed to work.

**Comment by MrAyfan** [comment]
Not working with forge 47.1.3 !!!

**Comment by bconlon1** [comment]
Can you post a new crashlog after the Forge change?

**Comment by MrAyfan** [comment]
I don't have a crash report or crash "log"

https://pastebin.com/M8Vvh1gh Minecraft Launcher log
https://pastebin.com/1C2R39Ut latest log

**Comment by MrAyfan** [comment]
After testing (having time to do it yay), Problem solved when removing twilight forest
Maybe a incompability ?

**Comment by bconlon1** [comment]
Finally found some things on this issue, it seems to potentially be related to java or your computer's drivers (which would explain why the crash doesn't appear to be logging anything), something is probably out of date.
- https://forums.minecraftforge.net/topic/125488-rules-and-frequently-asked-questions-faq/
- https://www.reddit.com/r/Minecraft/comments/zvi4vi/help_bad_exit_code_11073741819/
