### ISSUE TITLE
Bug: Gear effects causes server crashes when enemies wear them (1.19.2)

### ISSUE THREAD

**Issue by ItsYuriil** [Gilded-Games/The-Aether#2078]
### What Feature Types Apply to This Bug?

Entity, Item, System, Other (Please Describe)

### Other Type

weapon effect incompatibility with NPCs

### What Type of Bug Is This?

Crash

### Forge Version

43.3.0

### The Aether Version

1.3.1

### Is This Bug a Conflict With Another Mod?

improvedmobs-1.19-1.11.0-forge

### Client Log

https://pastebin.com/kdXVuYrY

### Crash Report (if applicable)

https://pastebin.com/md2Zs8Kq

### Steps to Reproduce

Have a mob wear any item with an effect, like a shield or a sword.

### What You Expect To Happen

For the system to work trough and display the effect of the given gear.

### What Actually Happened

The server instantly freezes trying to replicate the effect, or action.

### Additional Details

I wish I can have more data about this, but the server becomes unresponsive and I can't even close the profiler to take a deeper look.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by ItsYuriil** [comment]
I have modified improvedmobs gear list to exclude ALL aether items, and it seems that something still spawned with them

**Comment by Builderdog841** [comment]
This a progression thing from the modpack you're playing. This isn't a thing added by the mod

**Comment by Builderdog841** [comment]
oh wait sorry I accidently commented on the wrong the issue

**Comment by bconlon1** [comment]
The server crashes because your server properties cap the maximum tick time at 60s, however the stacktrace does point to Aether relating to the cause, so I will have to look into that.

**Comment by bconlon1** [comment]
Okay I believe the crash log at the max tick time is coincidence or not actually tied to the crash you got from the latest.log, it seems the one in the latest.log is caused by End of Herobrine: https://github.com/lgow/endofherobrine/issues/20
