### ISSUE TITLE
Bug: Unknown force prevents you from entering 

### ISSUE THREAD

**Issue by SirBotak** [Gilded-Games/The-Aether#2080]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

0.248.2

### The Aether Version

1.19.2

### Steps to Reproduce

Made the aether portal and placed water in the frame. Portal was formed but there was  text appearing at the my hotbar saying "a vile force prevents this gate from opening" and when trying to enter, a text saying "unknown force prevents you from entering".

### What You Expect To Happen

Maybe the aether portal was placed too near a nether portal but tried it in a separate creative world, and the results were the same.

### What Actually Happened

Made the aether portal in my survival world, wanting to go to the aether. Was greeted with the following texts and unsure of how to proceed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Builderdog841** [comment]
This a progression thing from the modpack you're playing. This isn't a thing added by the mod

**Comment by OzPayn** [comment]
I believe this is a feature added by the Fear Nightfall modpack, it is an intended part of their progression and is not a feature of our mod. Closing the issue.
