### ISSUE TITLE
Bug: <Quick Load Crash with Serene Seasons and Very Many Players>

### ISSUE THREAD

**Issue by AmazeingGames** [Gilded-Games/The-Aether#2082]
### What Feature Types Apply to This Bug?

System, Other (Please Describe)

### Other Type

Main Menu Quick Load

### What Type of Bug Is This?

Crash

### Forge Version

43.3.0

### The Aether Version

1.3.1

### Is This Bug a Conflict With Another Mod?

[SereneSeasons-1.19.2-8.1.0.24](https://www.curseforge.com/minecraft/mc-mods/serene-seasons/files/4037228) and [vmp-forge-mc1.19.2-0.2.0+beta.7.35-all](https://modrinth.com/mod/vmp-forge/version/0.2.0+beta.7.35+1.19.2)

### Crash Report (if applicable)

https://gist.github.com/AmazeingGames/9ae18e59d5d7276b250b29e66a4cf7fe

### Steps to Reproduce

From my testing this happened without fail when the given mods are loaded alongside the Aether.

Launch Minecraft
World begins to load in
-- Game Crashes --
1.1. If game has not crashed, hit 'Toggle World' in the top right
-- Game Crashes --

### What You Expect To Happen

The 'quick world' feature should load and display properly.

### What Actually Happened

The game crashes and I'm hit with a crash report.

### Additional Details

My Game version is 19.2. 
My mod folder was completely empty besides the necessary mods, being Aether, Serene Seasons, and Very Many Players.
This crash does not occur with only Very Many Players + The Aether, nor does it occur with only Serene Seasons + The Aether, but it does crash with exactly the three of them together.
Very Many Players is a very unstable and early development mod; normally I would delete it from the list without even posting a report because of its instability, but its crashing only with Serene Seasons seemed weird and, along with my time spent tracking down the issue, made me think it would be worthwhile to share. I hope this is useful to somebody!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
This crash report is only pointing to Very Many Players, so it would probably be better to report to them instead as to what the cause might be for the incompatibility.
