### ISSUE TITLE
Feature Request: Optional Field for Biome specific Moa Spawning

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#2085]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To add an Optional Field into the new Moa json system that allows moa types to only spawn in certain biomes

### Why Should It Be in the Mod?

It would be a nice tool for add-on and datapack creators

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Since the MoaTypes are set in finalizeSpawn after spawning checks have gone through, I don't think I have a clean way of going about this. I think I will leave implementation up to addons unless any come up with a good solution.
