### ISSUE TITLE
Feature Request: Re-add the Hammer of Notch for aesthetic purposes

### ISSUE THREAD

**Issue by mrjasonn** [Gilded-Games/The-Aether#2095]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

To make it so you can craft a Hammer of Kingbdogz with an Enchanted Golden Apple to get a Hammer of Notch that functions exactly the same as the Hammer of Kingbdogz for aesthetic purposes. I'd suggest sharing the same cooldown with the Hammer of Kingbdogz so people can't swap between them to avoid cooldown issues. The Hammer of Notch should have some visual distinctions between the Hammer of Kingbdogz so you can know which is which by just looking at it.

### Why Should It Be in the Mod?

Since the point of Aether 1 is to keep the original Aether feel and that this mod outright replaced the Hammer of Notch with the Hammer of Kingbdogz, I think it would be a good idea to add a Hammer of Notch for aesthetic purposes, as Notch has left the Minecraft Dev Team like how Kingbdogz left the Aether Dev Team, I think it would be good to make sure he is honoured in this mod as well.

### Does This Feature Improve Compatibility With Another Mod?

No, and it shouldn't break other mods.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Nothing else has changed with the item besides its renaming to the Hammer of Kingbdogz, and we would not add any other additional items. An anvil can still be used for changing the name of an item.
