### ISSUE TITLE
Bug: Berry bush doesn't turn black when opaque with fast graphics

### ISSUE THREAD

**Issue by mrjasonn** [Gilded-Games/The-Aether#2096]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Design

### Forge Version

20.4.219 (NeoForge)

### The Aether Version

1.3.2

### Steps to Reproduce

1. Turn on fast graphics
2. Get berry bush
3. Place it down and observe

### What You Expect To Happen

That it will turn black like other leaves when using fast graphics

### What Actually Happened

It didn't turn black and instead was still transparent

### Additional Details

I'd suggest fixing this first then waiting for the author of #2014 to compress it before merging #2014

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
The opacity code for this is fairly hardcoded and hard to mess with.

**Comment by GizmoTheMoonPig** [comment]
This actually isnt too hard to fix, you just need a custom model like so: https://github.com/TeamTwilight/twilightforest/blob/1.20.x/src/main/java/twilightforest/client/model/block/leaves/BakedLeavesModel.java
and then just wrap the models in the ModifyBakingResult event like so: https://github.com/TeamTwilight/twilightforest/blob/1.20.x/src/main/java/twilightforest/client/TFClientEvents.java#L93-L96
