### ISSUE TITLE
Enhancement: Moa (polishing)

### ISSUE THREAD

**Issue by Jaryt** [Gilded-Games/The-Aether#210]
- [x] Remember to implement visual HUD element that pulls from the Moa's jump counter.
- [x] Make saddling and sitting dependent on isPlayerGrown.
- [x] Egg laying timer is not final and should be based on older values instead of being copied chicken code.
- [x] Finish Incubator incubate() method with the stuff requiring Moa code.
- [x] Fix the issues with the Moa not being detected as on the ground when the world first loads up. This also applies to any other entities that use the .isOnGround check for an animation. Try using .isAirBorne.

**Comment by bconlon1** [comment]
Related Issues:
- #117 
- #125
- #137
