### ISSUE TITLE
Invis cape not functioning

### ISSUE THREAD

**Issue by TolupS** [Gilded-Games/The-Aether#2107]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.2.0

### The Aether Version

1.20.1-1.3.0

### Steps to Reproduce

1.Had Lightning sword in use
2.Struck a pillager patrol
3.recieved bad omen for under a second

### What You Expect To Happen

To be fully invisible 

### What Actually Happened

It was not turning the player invisible, even after removing and putting back on

### Additional Details

Happened just after killing a pillager patrol, for some reason the bad omen went away instantly as well, was using the lightning sword as well, not sure if that may have any relation to the issue.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Cannot reproduce, if you can, please provide a video and/or mods list.
