### ISSUE TITLE
Feature Request: Event for falling out of the Aether

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2109]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

An event for when a player falls out of the Aether
could also be cancelable, not sure how that'd impact performance though since it'd keep doing the event every tick, although that's probably fine considering tick events exist

### Why Should It Be in the Mod?

so addons can do stuff when the player falls out of the aether ~~and so i can remove a mixin from my addon that only exists because this doesn't~~

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Could you let me know more about what behavior you need the event for? It would give me a better idea of what stage of the code to put the event at.

**Comment by Zepalesque** [comment]
the initial reason was for an advancement when you fall out of the aether, although I ended up removng that since genesis might have that anyway, I think I had some other ideas too but I can’t remember them now 😂
but yeah it would probably fit best around where the player or mob (would be nice to make it use a LivngEntity, I can see myself trying to make non-player mobs also go to the overworld in redux at some point) gets teleported to the overworld, or maybe right before that happens, not 100% sure

**Comment by bconlon1** [comment]
May not be necessary because of the dimension travel event.
