### ISSUE TITLE
Bug: Very rarely and unpredictably, whirlwinds can launch you really far into the air

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2121]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.1.70

### The Aether Version

1.4.0 (although it also affects pretty much every other version)

### Steps to Reproduce

Inconsistent, I haven't been able to narrow down exactly how it happens but running around near whirlwinds seems to eventually cause the bug

### What You Expect To Happen

the whirlwind would either do nothing or pick up the player normally

### What Actually Happened

very rarely, the whirlwind launches the player 20+ blocks into the air

### Additional Details

I've had this happen sometimes for a LONG time but never happened to be recording when it happened, but this time I decided to just run around near them until it happened again:

https://github.com/The-Aether-Team/The-Aether/assets/60141811/b1c86d1b-4cf5-457c-893b-6e5e8ce850a3

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
In my opinion this counts as intended behavior.
