### ISSUE TITLE
Bug: With default curios menu, clicking toggle visibility while moving an item with your cursor will drop the item

### ISSUE THREAD

**Issue by sunsetbear** [Gilded-Games/The-Aether#2124]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Annoyance

### Forge Version

47.1.39

### The Aether Version

1.4.0

### Steps to Reproduce

With the curios menu config enabled, enter the inventory, pick up an item, and click toggle visibility on one of the curios slots.

### What You Expect To Happen

I expect the visibility to toggle, and the item to remain in my inventory, still being moved around by my cursor (this is what happens with the default config.)

### What Actually Happened

The visibility toggles, but the item i was moving with my cursor drops as if i had clicked outside of my inventory (i did not.)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
curios bug
