### ISSUE TITLE
Ticking entity crash with valkyries

### ISSUE THREAD

**Issue by PapaDimitri** [Gilded-Games/The-Aether#2137]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

43.2.4

### The Aether Version

1.4.0

### Is This Bug a Conflict With Another Mod?

Auditory

### Client Log

https://gist.github.com/PapaDimitri/4be62b79a85b951b9b45b7be0ae18239

### Crash Report (if applicable)

https://gist.github.com/PapaDimitri/9bb9a1a08b71937797dd6745301da252

### Steps to Reproduce

Everytime I go to the valkyrie dungeon and crash occurs when new valkyrie spawns 

### What You Expect To Happen

Dont crash?

### What Actually Happened

Crashed

### Additional Details

I use oculus and I m also new to the mod :/

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by PapaDimitri** [comment]
I found that Auditory causes client to crash, so removing it fixes the issue

**Comment by Jonathing** [comment]
If you know how to use this, go nuts. Credit me if you do. CC-BY-SA-4.0.
https://gist.github.com/Jonathing/d7954176203a34f6e8866f8627cfec18

shhh, don't tell anyone :wink:
