### ISSUE TITLE
Bug: the sleeve layer on the player's skin is not covered by gloves

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether#2140]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

NeoForge 47.1.104

### The Aether Version

1.20.1-1.4.1-neoforge

### Steps to Reproduce

1. Use a player skin that has a sleeve layer.
2. Equip any Aether gloves.

### What You Expect To Happen

I expect the glove texture to completely cover the sleeve texture.

### What Actually Happened

The top of the sleeve layer sticks out in first person view.
![image](https://github.com/The-Aether-Team/The-Aether/assets/112828225/f1df6db9-415e-473a-9fd4-c24935ac4cc3)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment]
Seems to be an oversight with 4x4 arms.
