### ISSUE TITLE
Backhand's Offhand doesn't render with Aether Legacy installed

### ISSUE THREAD

**Issue by brandyyn** [Gilded-Games/The-Aether#2167]
### What Type of Bug Is This?

None

### Forge Version

1.7.10 1614

### The Aether Version

aether-1.7.10-v1.1.2.3

### Steps to Reproduce

install backhand mod with unimixins and aether legacy

put any item into offhand

### What You Expect To Happen

offhand item should appear on the left

### What Actually Happened

doesnt appear 

![image](https://github.com/The-Aether-Team/The-Aether/assets/11356565/7031e8b3-3394-4a4d-ab57-ce1729e45407)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This repository is for versions 1.19.2 and up.

**Comment by brandyyn** [comment]
> This repository is for versions 1.19.2 and up.

so where do i post it because there was a 1.7 PR accepted on this repository a few months ago
