### ISSUE TITLE
Feature Request: Convert dungeon block conversions to DataMaps on 1.20.4+

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2179]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

It would be helpful for the block conversions (such as Locked Carved Stone -> Carved Stone) when killing a boss to be able to be datadriven with data maps

### Why Should It Be in the Mod?

That way addon creators can add new dungeon blocks without needing to use a mixin to convert their locked blocks

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Ended up doing this in a different way than data maps; I don't think they quite work for what's needed.
