### ISSUE TITLE
Bug: Moa eyes shows inside mouth

### ISSUE THREAD

**Issue by Acat1234** [Gilded-Games/The-Aether#2183]
### What Feature Types Apply to This Bug?

Art, Entity

### What Type of Bug Is This?

Design

### Forge Version

47.3.1

### The Aether Version

1.4.2

### Steps to Reproduce

Find a moa
look at its mouth (kinda ez cuz it looks at you

### What You Expect To Happen

It to not show there

### What Actually Happened

It shows in the mouth and on outside

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This has been an old funny quirk of the texture so we probably won't be changing it.
