### ISSUE TITLE
Feature Request: Inventorio Compatibility

### ISSUE THREAD

**Issue by jzyserman** [Gilded-Games/The-Aether#2186]
### What Feature Types Apply to This Request?

System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Like the title, there should be compatibility with Inventorio for a more uniform GUI

### Why Should It Be in the Mod?

Better look for compatibility/parity especially for expanded inventory. Reduces unneeded switching between GUI

### Does This Feature Improve Compatibility With Another Mod?

Inventorio 1.20.1+, https://github.com/RubixDev/Inventorio

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This would be something a compatibility addon would likely have to handle.
