### ISSUE TITLE
Bug: Portal

### ISSUE THREAD

**Issue by PikachuLuke5** [Gilded-Games/The-Aether#2215]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Portal

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.3.0

### The Aether Version

1.4.2

### Steps to Reproduce

ALL THE TIME

### What You Expect To Happen

To Light the Portal

### What Actually Happened

The water just doesn't light it!

### Additional Details

![2024-06-25_09 29 07](https://github.com/The-Aether-Team/The-Aether/assets/142318212/1c563cd6-0498-4497-99c8-4f5c4f2e0247)
That's what happened!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by ZolaKluke** [comment]
Not a bug, by the looks your playing a modpack, I'd ask in their discord as they've probably locked the Aether behind some kind of progression goal

**Comment by bconlon1** [comment]
Yeah this sounds like a question for the modpack maker.
