### ISSUE TITLE
Bug: The indicator overlaps the HP bar

### ISSUE THREAD

**Issue by Kastik404** [Gilded-Games/The-Aether#2225]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Annoyance

### Forge Version

47.3.0

### The Aether Version

1.4.2

### Steps to Reproduce

If you use Life Shard and get any HP boost, the bar with gray hearts goes down and overrides the standard HP bar

### What You Expect To Happen

The gray hearts indicator should not go down

### What Actually Happened

I use a mod for colored hearts, and for example, after using a 10 life shard and getting a level 15 HP boost, gray hearts completely cover the HP bar and make it impossible to track health

### Additional Details

![heart](https://github.com/The-Aether-Team/The-Aether/assets/170334439/230495a7-b74f-440d-877c-9d8718a3aac0)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Heart overlay code is hard to make compatible so we have a client configuration option that you can use to disable them if you're running into issues.
