### ISSUE TITLE
Bug: Darts underwater seem to have odd desyncing behavior(?)

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#2226]
### What Feature Types Apply to This Bug?

Entity, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

NeoForge 47.1.70

### The Aether Version

1.4.2

### Steps to Reproduce

1: Find some sort of large body of water
2: Shoot a dart into the water
3: *Observe*

### What You Expect To Happen

The dart would move normally, potentially sinking like an arrow or something similar

### What Actually Happened

It froze and got all bugged and stuff

### Additional Details

https://github.com/The-Aether-Team/The-Aether/assets/60141811/31158e96-2655-46a9-aa98-b9cf5d7b9c0a

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Maybe I should apply gravity to them if they're in liquid. Or maybe thats what it's trying to do but that's what desyncs, idk.
