### ISSUE TITLE
1.21 please

### ISSUE THREAD

**Issue by JackieJK** [Gilded-Games/The-Aether#2227]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

1.21 please

### Why Should It Be in the Mod?

1.21 support

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
yeah

**Comment by Herobrine982950291** [comment]
Wait- so the Aether will be in 1.21?

**Comment by darksonic300** [comment]
that's the plan

**Comment by Herobrine982950291** [comment]
how long until it releases?

**Comment by Herobrine982950291** [comment]
@darksonic300 how long till release???

**Comment by Builderdog841** [comment]
There is no ETA, no need to spamm comments

**Comment by Herobrine982950291** [comment]
sorry sorry i just need it to release as soon as possible

**Comment by Builderdog841** [comment]
Well you still probably have to wait some time since before another Aether 1 Update needs to be done and the team is currently busy with that, Aether II and the offical Aether Genesis Add-On
