### ISSUE TITLE
Feature Request: Disable boss bar overlay

### ISSUE THREAD

**Issue by PinkLasagna03** [Gilded-Games/The-Aether#2234]
### What Feature Types Apply to This Request?

Art

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

I think it looks weird to have double boss bar, would be nice to disable the one featured by the Aether.

![2024-08-14_02 31 12](https://github.com/user-attachments/assets/ace0b1c1-2c77-4934-a138-10f4ba2255c7)

### Why Should It Be in the Mod?

Because it looks weird and out of place

### Does This Feature Improve Compatibility With Another Mod?

no

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This looks to be a conflict with another mod that you will have to narrow down.
