### ISSUE TITLE
Bug: Icestone doesn't freeze water until a block is placed within 4 block radius of any Icestone

### ISSUE THREAD

**Issue by USERNAMEzfugnhsknudgfsnudhfk** [Gilded-Games/The-Aether#2243]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.3.1

### The Aether Version

1.4.2

### Steps to Reproduce

Always happend:

1. Have normal water (can be source or running) within freezing radius of Icestone.
2. Save and quit the game while the water is not frozen.
3. Rejoin.
4. Icestone doesn't freeze water until a block update by player (place or destroy) or spawn mob with egg within 4 block radius of any Icestone. Block update by piston and block state update (even by player) can't make water freezing again.

### What You Expect To Happen

Water near icestone will get frozen after a while if not frozen upon joining a world.

### What Actually Happened

Icestone doesn't freeze water until a block update by player (place or destroy) or spawn mob with egg within 4 block radius of any Icestone if water is not frozen upon joining a world.

### Additional Details

https://github.com/user-attachments/assets/ffce8708-3f51-4a86-96a5-68b68d662055

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by USERNAMEzfugnhsknudgfsnudhfk** [comment]
I found this bug while trying to make an ice farm using refined storage's destructor, tried without any other mods and it still get reproduced.

**Comment by USERNAMEzfugnhsknudgfsnudhfk** [comment]
Update: water placed or removed by any kind of machine (modded or vanilla redstone) near the icestone can make all the icestone work again. so if you want to make a ice farm using what I'm using, this is a work around.

**Comment by bconlon1** [comment]
This is a limitation that had to be made for performance reasons so this likely won't change.
