### ISSUE TITLE
Bug: Moa won't eat Aechor Petal

### ISSUE THREAD

**Issue by BlackAures1** [Gilded-Games/The-Aether#2245]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

47.3.7

### The Aether Version

aether-1.20.1-1.4.2-neoforge

### Is This Bug a Conflict With Another Mod?

no

### Client Log

<script src="https://gist.github.com/BlackAures1/d339b22641760532378968883aefdbee.js"></script>

### Steps to Reproduce

Hatch white moa on incubator, growth timer shows static 800, try to feed it - it doesn't eat Petals and it looks like a bug. After restarting the game the growth timer was showing static 1200. Sometimes they release evil particles, but in those moments I can't feed them either. Only after a few minutes did I manage to feed it once, but I still didn't understand why it didn't work at all the other times.

https://github.com/user-attachments/assets/1c89b121-fb04-4357-af62-b7043d3d4d90

### What You Expect To Happen

I expect to be warned somehow that I can't feed them now (at least the particle effect) or that I have the option to feed it after it hatches.  Or just update the description on the wiki along the lines of “you can only feed baby moa once every 10 minutes”

### What Actually Happened

I can't feed Moa and I don't understand why he doesn't eat Aechor Petal after hatching as write in wiki-book

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Builderdog841** [comment]
You can only feed them while they have the evil particles so it must be some sort of mod incompatibility if you can't do it consistently during this period of time, try doing it with just the aether mod installed

**Comment by bconlon1** [comment]
If you can get a video of the interaction not working when the Moa is hungry and provide more info on what the modpack is then that would be able to help here.
