### ISSUE TITLE
Bronze Dungeons not spawning 

### ISSUE THREAD

**Issue by Spaghettt** [Gilded-Games/The-Aether#2246]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Design

### Forge Version

1.20.1

### The Aether Version

1.4.2

### Steps to Reproduce

Go to aether

### What You Expect To Happen

All structures spawn

### What Actually Happened

Bronze Dungeons doesn't spawn

### Additional Details

Bronze Dungeons won't spawn 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Spaghettt** [comment]
Sorry, edited it

**Comment by bconlon1** [comment]
Have you confirmed whether /locate structure aether:bronze_dungeon detects any in your world?
