### ISSUE TITLE
Bug: Torches Give Failure Message in Aether Regardless of if an Attempt is Actually Made to Use Them

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Gilded-Games/The-Aether#2248]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

N/A (NeoForge 20.2.88)

### The Aether Version

aether-1.20.2-1.4.2-neoforge

### Steps to Reproduce

1. Get a Vanilla Torch or Flint and Steel.
2. Go into The Aether.
3. Find or Place a Chest or other Block that has a right-click function.
4. Right-click on the Chest or other Block with the Torch or Flint and Steel in hand.

### What You Expect To Happen

The Chest or other Block is interacted with using the right-click functionality. The Torch should not be relevant here as the right-click functionality of a Block generally overrides that of a held Item. For example, it is possible to open Chests in the Overworld with a Torch in Hand; this does not attempt to place down the Torch. Even if a Torch could be placed there, such as on a Barrel, the Torch is not placed as its functionality is overridden by the Block.

### What Actually Happened

A message comes up stating that the Torch cannot be used.

### Additional Details

The Aether Official Server Modpack does not appear to have its own issue tracker.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is unfortunately a NeoForge limitation due to the ordering of their interaction events. This likely won't be easily fixable until their plans of reworking interaction events go through.
