### ISSUE TITLE
Feature Request: Game version

### ISSUE THREAD

**Issue by Rehlin** [Gilded-Games/The-Aether#2249]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

The game version that the Aether is available on

### Is This an Enhancement to a Preexisting Feature?

- [x] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Could you please release the Aether for version 1.16.5?

### Why Should It Be in the Mod?

You should release it in version 1.16.5 so people can add it to their 1.16.5 modpacks, and, the reason I'm asking is because I'm making my very own modpack based off of the Aphmau youtube channel, and she uses the Aether, but my modpack is version 1.16.5, it would be great if you could help out!

### Does This Feature Improve Compatibility With Another Mod?

MrCrayfish's Furniture Mod (Legacy) 1.16.5

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by darksonic300** [comment]
nope, there's no official plans for 1.16 support.
It's quite an old version and would be pretty much impossible to maintain given the circumstances

**Comment by Rehlin** [comment]
Thank you for telling me, and responding at all, most times I'll request
something, and they won't even respond.
