### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by kewl810** [Gilded-Games/The-Aether#2255]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

None

### Forge Version

47.3.5

### The Aether Version

1.20.1-1.4.2-neoforge

### Steps to Reproduce

1. Get mending on diamond gloves
2. Have other equipment with mending
3. Kill a mob

### What You Expect To Happen

I should have been able to repair all my other gear that had mending when I killed a mob

### What Actually Happened

The xp went to my xp bar instead when I had the gloves on when I killed mobs

### Additional Details

I should note that this only happens with xp from killing mobs. getting xp from mining ores seems to work

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Cannot reproduce, XP seems to be going to repairing both the gloves and the equipment just fine.

**Comment by kewl810** [comment]
Do you have any other mods enabled? Or is there somewhere else I can talk to you on? I was just able to replicate it on another world myself

**Comment by bconlon1** [comment]
Could you get a video of it without any other mods? In a development environment I couldn't reproduce it with only Aether.

**Comment by kewl810** [comment]
I am doing this on the BMC4 modpack, I was just told to go here to report it after Oz told me to go here to report it

**Comment by bconlon1** [comment]
It would still be good if you can determine whether the issue is occurring with or without the modpack.

**Comment by kewl810** [comment]
The issue is occurring with the modpack.

**Comment by bconlon1** [comment]
So you haven't been able to reproduce it without the modpack?

**Comment by kewl810** [comment]
Didn't try without the modpack

**Comment by bconlon1** [comment]
If this is an issue with the modpack report it to the modpack devs. Otherwise, this issue can be reopened.

**Comment by kewl810** [comment]
Alright I can, I was just linked here by an aether dev to report it
