### ISSUE TITLE
Bug: Gloves don't have a correctly assigned Curios slot

### ISSUE THREAD

**Issue by Yadokingu** [Gilded-Games/The-Aether#2256]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Compatibility

### Forge Version

47.3.7

### The Aether Version

1.4.2

### Is This Bug a Conflict With Another Mod?

Curios

### Steps to Reproduce

Try to put gloves into one of the Hands slots.

### What You Expect To Happen

Gloves go into the Hands slot.

### What Actually Happened

Gloves don't go into the Hands slot.

### Additional Details

From the art it seems pretty obvious that gloves are supposed to go into "Hands" curio slot, but their discription says that they are supposed to go into a nonexistent "Gloves" slot and they won't go into the "Hands" slot if you try to put them in there.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
The Gloves slot is in the Aether's accessories inventory, which you can access by clicking the cloud icon in the bottom corner of the player render in the main inventory. To make the Aether's accessories go into Curios slots instead of the custom accessories inventory, there is an option in the mod's configs that you can adjust for that.

**Comment by Yadokingu** [comment]
Well that's egg on my face. 
The art looks exactly the same as the hands slot in Curios, they do go into the generic curio slot and the description "Slot: XXX" looks exactly the same as it does for Curios. It isn't very obvious that The Aether has an extra menu for its items.

**Comment by bconlon1** [comment]
Usually with Aether installed on its own, the default Curios slots won't show up so it becomes a bit more obvious that the accessories don't go in there, but maybe there are some places where we could be more clear about that information for those who aren't as familiar with the mod.
