### ISSUE TITLE
Bug: Cannot load server: Faailed to load datapacks...

### ISSUE THREAD

**Issue by Kielbashnikov** [Gilded-Games/The-Aether#2257]
### What Feature Types Apply to This Bug?

System, Other (Please Describe)

### Other Type

Server loading

### What Type of Bug Is This?

Crash

### Forge Version

47.3.7

### The Aether Version

1.4.2

### Client Log

https://gist.github.com/Kielbashnikov/8299411f56b245a964a55c80a48d9a6f.js

### Steps to Reproduce

It happens on every server startup.
Reproduction:
1. Setup forge server
2. Install Aether
3. Launch server

### What You Expect To Happen

I expected server to start with no issues.

### What Actually Happened

Server crashed in the middle of startup.

### Additional Details

Removing the Aether mod solved startup issue, putting mod back after first startup does not solve the problem.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Could you please provide a valid log file link.

**Comment by Kielbashnikov** [comment]
There you go: https://gist.github.com/Kielbashnikov/8299411f56b245a964a55c80a48d9a6f
Sorry for inconvenience.

**Comment by bconlon1** [comment]
Ah, I have seen this crash before, it'll be fixed as a part of the next update.
