### ISSUE TITLE
Feature Request: Falling into Void

### ISSUE THREAD

**Issue by ENC4YP7ED** [Gilded-Games/The-Aether#2263]
### What Feature Types Apply to This Request?

Config

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

I want a config option for wehn a player falling from aether it should die instead of spawning high up in the overworld.

### Why Should It Be in the Mod?

Because it breaks Immersive Portals Dimesion Stack Feature in a way that if you falling down you get a dimesion loading screen even if Immersive Portals Dimesion Stack Feature is enabled and i can't find any setting to change that

### Does This Feature Improve Compatibility With Another Mod?

Yes

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
There is already a config option for this in the mod.

**Comment by ENC4YP7ED** [comment]
> There is already a config option for this in the mod.

Where ?

**Comment by bconlon1** [comment]
It's handled by the per-world `serverconfig`s you can find in each save folder, inside the Aether's config the option is titled `"Disables falling into the Overworld"`. If you need to make them work for a modpack then you can change a server world config and then copy it to the pack directory's `defaultconfigs` folder.
