### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by saniky16** [Gilded-Games/The-Aether#2264]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

14.23.5.2854

### The Aether Version

1.5.2

### Client Log

https://gist.github.com/b48a78779802654281f65f857899682d.git

### Crash Report (if applicable)

https://gist.github.com/605451d0e9d1e240dbef1dc4a94f114a.git

### Steps to Reproduce

happens every 2-5 or so minutes, 
1 - enter the dimension and it crashes after a while

### What You Expect To Happen

its expected for the game to run smothly and no crashes to occur while in the aether dimension

### What Actually Happened

the game crashes after a few minutes in the dimension, going as far as blue screening my computer once

### Additional Details

this might be a memory issue, but i find it weird since minecraft 1.12 does not use alot of resources, neither did most of the mods i had installed. this bug is present on the aether legacy modpack.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
The crash seems to report this as an issue with `netherrocks`, not The Aether.
