### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Fishirboy** [Gilded-Games/The-Aether#2276]
### What Feature Types Apply to This Bug?

Entity, Item

### What Type of Bug Is This?

Crash

### Forge Version

47.1.99 -Neo

### The Aether Version

1.4.2

### Is This Bug a Conflict With Another Mod?

Neruina - Ticking Entity Fixer

### Client Log

https://gist.github.com/Fishirboy/3f58a3a84550917e1e26116177dccf00

### Crash Report (if applicable)

https://gist.github.com/Fishirboy/3f58a3a84550917e1e26116177dccf00

### Steps to Reproduce

All armor with the reflection effect causes the issue to have a mob tick and then the server kills them so they don't crash the server.
If a player hits someone with the armor it crashes the server since it can't just kill another player.

### What You Expect To Happen

I think the modifier for reflect is broken and has a collision with something. My best bet would be something with our fabric connector or I am not sure.

### What Actually Happened

Something to do with Damage Reflect. But I can't recreate in another world single player so I will trying and do some further testing but if someone has a better direction I can test it may be best.
![image](https://github.com/user-attachments/assets/2328139e-273f-4705-b927-82870cf64571)

![VanutKo8MQ](https://github.com/user-attachments/assets/b9197afd-8d2e-401f-9dfd-61c8c959c1d7)

### Additional Details

Sorry for wasting time if this for some reason needs further testing to identify but I am not super skilled in identifying the core issue with this and was wondering if this was a bug with reflect or not. I will keep manually testing on my end to find the solution but if it is a bug with another mod I thought it would be good to post here.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Fishirboy** [comment]
Also happening to our player where if they are in the Aether and are hit it happens to the monsters where they would crash the server but the entity is killed beforehand. If the user equips the armor and goes out of the aether and unequips it somehow he had a permanent modifier I couldn't see in my debug of his account. So I wiped his attributes and it went away.

**Comment by Fishirboy** [comment]
This is happening with just default armor as well I put on. 
![jQKRetKxam](https://github.com/user-attachments/assets/7aa42465-b7ab-4afe-8178-f0b36aa08014)

I also tested in Singleplayer and it works fine on the same world file that it wasn't in Multiplayer

**Comment by bconlon1** [comment]
This has a fix pending for when our next update releases.

**Comment by Mitchell5200** [comment]
this issue is related to/caused by https://github.com/KyaniteMods/DeeperAndDarker/issues/351, BTW

**Comment by Fishirboy** [comment]
Thank you I have test and got it fixed
