### ISSUE TITLE
Bug: Game crash when entering or creating a world

### ISSUE THREAD

**Issue by 162534XXX** [Gilded-Games/The-Aether#2297]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

neoforge 47.1.106

### The Aether Version

1.5.0

### Client Log

https://gist.github.com/162534XXX/08dfaab4d684dec8b6ed4742ea25daf1

### Crash Report (if applicable)

https://gist.github.com/162534XXX/5dfe92c9466372057bbfbdae0b4a8ec0

### Steps to Reproduce

Simply enter the world or create the world, then it would happen.

### What You Expect To Happen

I thought I would smoothly enter or create a world.

### What Actually Happened

But when I create or enter a world the game just crashes.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This appears to be a crash from Aether Redux

**Comment by 162534XXX** [comment]
Thanks a lot!
