### ISSUE TITLE
Bug: "File aether-1.20.4-1.5.0-neoforge.jar is not a valid mod file" even though it's on the exact neoforge and minecraft version

### ISSUE THREAD

**Issue by LeGamerDe2005** [Gilded-Games/The-Aether#2299]
### What Type of Bug Is This?

Crash

### Forge Version

neoforge 20.4.2 beta

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

no

### Client Log

https://gist.github.com/LeGamerDe2005/c40e9f64e20a100ffa581cf4b4b0dd43

### Steps to Reproduce

1 - install the latest ather mod in a 1.20.4 neoforge instance
2 - launch the game
3- voila

### What You Expect To Happen

i exept the game to launch normaly

### What Actually Happened

it show me this error message : 
![image](https://github.com/user-attachments/assets/8f5c080c-a621-4630-ab9e-16c3df5f80e8)

### Additional Details

i use the latest version of neoforge and the corect mc version and mod

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Using NeoForge 20.4.200 should fix this.
