### ISSUE TITLE
Bug: mouseClicked event handler crash with aether installed

### ISSUE THREAD

**Issue by H311F1R3** [Gilded-Games/The-Aether#2300]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

47.3.6

### The Aether Version

1.5.0

### Client Log

https://gist.github.com/H311F1R3/2d90d62a06d9c674d4e19887f2dd994c

### Crash Report (if applicable)

https://gist.github.com/H311F1R3/21e6ee069d73b1f831c70726f204c199

### Steps to Reproduce

1. Start up the game with the aether mod enabled (mod being on version listed)
2. Load into Minecraft
3. Go to load existing world 
4. Get a "errors in selected datapacks prevent world from loading error". If safe mode is chosen, game will say world contains invalid or corrupted save data.
5. If attempting to make a new world, game will say "Loading world generation" then "saving game", and then crash to minecraft installer while displaying crash warning.

### What You Expect To Happen

Expected Game to load in normally, world to load in normally, and game to not crash when trying to make a new world

### What Actually Happened

Game gives "errors in selected datapacks" warning when trying to load up world, and crashes when "create new world" is chosen.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This seems to be a crash with Ancient Aether, you should report this to that addon.
