### ISSUE TITLE
Bug: neoforge doesnt recognise the aether mod as a valid mod files in the recent versions (in this case, neoforge 20.4.2 beta)

### ISSUE THREAD

**Issue by LeGamerDe2005** [Gilded-Games/The-Aether#2301]
### What Type of Bug Is This?

Crash

### Forge Version

neoforge 20.4.2 beta

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

no

### Client Log

https://gist.github.com/LeGamerDe2005/c40e9f64e20a100ffa581cf4b4b0dd43

### Steps to Reproduce

1 - install the latest ather mod in a neoforge 20.4.2 beta instance
2 - launch the game
3- voila

### What You Expect To Happen

launch the game normaly 

### What Actually Happened

it gave this error message 
![373946292-8f5c080c-a621-4630-ab9e-16c3df5f80e8](https://github.com/user-attachments/assets/f35bbf60-fb7f-4a98-8f5b-0a3928019f3d)

### Additional Details

i already made a bug report about this (here : https://github.com/The-Aether-Team/The-Aether/issues/2299 ) and someone found a solution but the solution was to downgrade the neoforge version, witch is not optimal, so i made a more apropriate bug report 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Upgrade to 20.4.200

**Comment by bconlon1** [comment]
Nevermind I see the additional issue link, let me look into this further.

**Comment by bconlon1** [comment]
Okay I had to double check: 20.4.200 is an upgraded version from 20.4.2-beta, although for some reason some launchers like Prism do not seem to order the versions chronologically for some reason, but this is the order given by https://projects.neoforged.net/neoforged/neoforge
