### ISSUE TITLE
Bug: <与Mohist核心不兼容 Not compatible with Mohist><1.20.1>

### ISSUE THREAD

**Issue by Lonmo0208** [Gilded-Games/The-Aether#2302]
### What Feature Types Apply to This Bug?

Config, World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

47.3.10

### The Aether Version

1.5.0

### Crash Report (if applicable)

https://mclo.gs/VHrwhy5

### Steps to Reproduce

1.下载最新的1.20.1的Mohist服务端 / Download the latest 1.20.1 Mohist server
2.将1.5.0的Aether安装到mods文件夹 / Install Aether from 1.5.0 to the mods folder
3.启动服务端过程中奔溃 / Crash during the start of the server

### What You Expect To Happen

The server is successfully started / 成功启动服务端

### What Actually Happened

Failed to start

### Additional Details

根据Mohist开发者回应，是因为1.5.0的Aether调用了客户端的类 net.minecraft.client.resources.sounds.SoundInstance
According to the Mohist developers, it was because Aether 1.5.0 called the client's class net.minecraft.client.resources.sounds.SoundInstance

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Could you try redownloading the mod and seeing if that works? It's possible you might've downloaded a version we took down, since this was an issue at first that had to be quickly patched.

**Comment by Lonmo0208** [comment]
> Could you try redownloading the mod and seeing if that works? It's possible you might've downloaded a version we took down, since this was an issue at first that had to be quickly patched.

哦，好的好的，已经修复了
