### ISSUE TITLE
Bug: Updating Aether from 1.4.2 to 1.5.0 crashes my game upon trying to load into a world

### ISSUE THREAD

**Issue by logenlol** [Gilded-Games/The-Aether#2304]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Opening a world

### What Type of Bug Is This?

Crash

### Forge Version

47.3.0

### The Aether Version

1.5.0

### Client Log

https://gist.github.com/logenlol/927947f579f087699590fee27cdbd237

### Crash Report (if applicable)

https://gist.github.com/logenlol/3e10e10409b041cb333a5a9653a2c892

### Steps to Reproduce

This happens every time I try to open my survival world AFTER I updated to the lastest Aether version (1.5.0). I am also on Minecraft 1.20.1.
Opening the game and title splash are completely fine, but when I go into singleplayer and click on my survival world, it starts loading and then says "Saving world" as though I quit out of it when it hasn't even loaded yet and then crashes and gives me a crash report.
Backporting Aether to the previous version (1.4.2) fixes the issue though as that was what I was playing on previously

### What You Expect To Happen

I expected to be able to load into the game and play in my world.

### What Actually Happened

Instead the game crashed upon trying to load my world due to some mouseclick event it seems from reading the crash report.

### Additional Details

Idk if this has anything to do with the mouseclick event which seems to have caused the crash (if im reading the crash report correctly), but i have the Deep Aether, Aether Redux, and Aether Lost Content in my modpack so I'm not sure if this might have anything to do with the crash since they all depend on the Aether as a dependency.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is a crash with Aether Redux that has to be fixed on their end.
