### ISSUE TITLE
Bug: mouseClicked event handler crash when loading existing world

### ISSUE THREAD

**Issue by AkariEnderwolf** [Gilded-Games/The-Aether#2305]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

43.3.0

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

uncertain, crash log only points to the Aether

### Crash Report (if applicable)

https://gist.github.com/AkariEnderwolf/65277ec6ae41a2a8ab5dbb52edaf9a52

### Steps to Reproduce

This happens every time i loaded in to an existing world
Steps:
1. Install latest version of The Aether
2. Boot up game
3. Attempt to load world

### What You Expect To Happen

World to load

### What Actually Happened

Game crashes before load % shows up

### Additional Details

Issue disappeared and world loaded fine after reverting to previous Aether mod version, 1.4.2
Issue seems to only be present on 1.5.0 version of Aether mod

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Caused by Aether Redux
