### ISSUE TITLE
Bug: Crash Upon Attempting to Generate World

### ISSUE THREAD

**Issue by pantman687** [Gilded-Games/The-Aether#2307]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

43.4.4

### The Aether Version

aether-1.19.2-1.5.0-forge

### Crash Report (if applicable)

https://gist.github.com/pantman687/b1de18822b06ca3d0b518bd0e2b1c718

### Steps to Reproduce

1.) Launch Game.
2.) Go to world generation screen.
3.) Click generate new world.
4.) Wait for loading screen.
5.) Game Crash.

### What You Expect To Happen

World Generation loading screen finishes and progresses to playable game world.

### What Actually Happened

Game Crashed.

### Additional Details

[Minecraft Create-ive New Lands 4.zip](https://github.com/user-attachments/files/17284216/Minecraft.Create-ive.New.Lands.4.zip)
Above is my personal CurseForge Modpack, if you want to test the issue on your end using my mod set up.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Cinex20** [comment]
Aether Redux is the culprit.
