### ISSUE TITLE
Bug: Crash on Startup; AETHER REDUX INCOMPATIBILITY

### ISSUE THREAD

**Issue by LenKagamine** [Gilded-Games/The-Aether#2308]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

47.3.7

### The Aether Version

1.5.0

### Crash Report (if applicable)

https://gist.github.com/LenKagamine/5cd1004f08d17162f7b5358111d2d963

### Steps to Reproduce

1. Load game
2. Crash

### What You Expect To Happen

The game loads normally

### What Actually Happened

The game crashes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Cinex20** [comment]
It's Aether Redux.
