### ISSUE TITLE
Bug: Game crashes when trying to create a new world

### ISSUE THREAD

**Issue by kakarotprime121** [Gilded-Games/The-Aether#2323]
### What Feature Types Apply to This Bug?

System

### Other Type

Singleplayer

### What Type of Bug Is This?

Crash

### Forge Version

47.3.0

### The Aether Version

1.20.1 - 1.5.0

### Client Log

https://gist.github.com/kakarotprime121/91be983d5db41c08749d9101a0d727a0

### Crash Report (if applicable)

https://gist.github.com/kakarotprime121/541844d8a70d9c1177c9e8c81d52b5fb

### Steps to Reproduce

1. I opened up the launcher.
2. I started the game and landed to the title screen.
3. As I try to create a new survival world, the game instantly crashes and immediately sends me back to the launcher.

### What You Expect To Happen

When I installed the Aether mod onto my custom modpack, I initially thought that the game would still run normally as I clicked my mouse at the singleplayer button to create a survival world.

### What Actually Happened

The game instantly crashed as I immediately pressed the singleplayer button in an attempt to create a survival world, which sent me back to the launcher and gave me an error message saying "The game crashed whilst mouseclicked event handler".

### Additional Details

```The game crashed whilst mouseclicked event handler Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered```
According to the crash report, I suspsect that the Aether's error is the one causing the crash when I try to create a new world on singleplayer mode.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by darksonic300** [comment]
Are you running Redux? If so that's the issue. No fix at the moment so either downgrade Aether's version or remove Redux entirely.

**Comment by kakarotprime121** [comment]
Well yeah. I should immediately remove Redux so that the game would run normally as expected.
