### ISSUE TITLE
Minecraft 1.19.2 Aether Version 1.5.0 on forge doesn't work LAN multiplayer

### ISSUE THREAD

**Issue by Klauros** [Gilded-Games/The-Aether#2327]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Multiplayer

### What Type of Bug Is This?

Crash

### Forge Version

43.4.0

### The Aether Version

1.5.0

### Steps to Reproduce

1. Open Minecraft with (just) the most recent version of the Aether mod for Minecraft 1.19.2
2. Create a world
3. Open to LAN multiplayer
4. Try to join the multiplayer game from another computer with just the aether mod

### What You Expect To Happen

I expected the second computer to join the game in multiplayer.

### What Actually Happened

There is some kind of java null exception, and the second computer fails the connection

### Additional Details

Multiplayer works for version 1.4.2 of the Aether mod (the previous version for Minecraft 1.19.2 forge)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Another player mentioned this to me but hadn't opened a ticket, so I'll attach this log here from them for when I get around to fixing this: https://gist.githubusercontent.com/BadmoonRising5/338ed42089d5f208d6fbe42e825f726f/raw/1b63b3f9a8a017f1600d8b2eb86c2cb9a5420033/Shortest%2520Server%2520Log%25201.19.2%2520A1.5.0.log

**Comment by bconlon1** [comment]
Also that the issue is somehow from here https://github.com/The-Aether-Team/The-Aether/blob/1.19.2-develop/src/main/java/com/aetherteam/aether/recipe/serializer/AetherCookingSerializer.java#L76
