### ISSUE TITLE
Bug: minecraft 1.19.4 crashing

### ISSUE THREAD

**Issue by nico104651** [Gilded-Games/The-Aether#2334]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

14.23.5.2859

### The Aether Version

1.5.3.2

### Client Log

https://gist.github.com/nico104651/6e0983a23d94ef792e4779607ec4198d

### Crash Report (if applicable)

https://gist.github.com/nico104651/46042d41fec0363a3b1d6b0d1d641094

### Steps to Reproduce

1. i start minecraft
2. minecraft crashes
3.

### What You Expect To Happen

minecraft start loading all mods and i can play on my favorite survival

### What Actually Happened

minecraft crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is a crash for 1.12 not 1.19, but you can solve it by changing the Aether's dimension ID in the configs to something higher than 4 until it fixes the issue.

**Comment by nico104651** [comment]
where i find the Aether dimension ID

Il giorno dom 3 nov 2024 alle ore 19:45 bconlon ***@***.***>
ha scritto:
