### ISSUE TITLE
More of a crash than a bug 

### ISSUE THREAD

**Issue by QuasarMoon** [Gilded-Games/The-Aether#2342]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Crash

### What Type of Bug Is This?

Crash

### Forge Version

47.3.12

### The Aether Version

1.51

### Is This Bug a Conflict With Another Mod?

unkown

### Crash Report (if applicable)

https://gist.github.com/QuasarMoon/386ef7ebef3f517845ef034095274b28

### Steps to Reproduce

World load in 

### What You Expect To Happen

Load into the world like normal

### What Actually Happened

It crashed 

### Additional Details

The previous version seemed to be non registered 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Update your version of Aether Redux
