### ISSUE TITLE
Bug: Crash when opening a world

### ISSUE THREAD

**Issue by KooKooGH** [Gilded-Games/The-Aether#2343]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Entering a save

### What Type of Bug Is This?

Crash

### Forge Version

47.3.11

### The Aether Version

1.5.1

### Client Log

https://gist.github.com/KooKooGH/c3ebab9476b885294ad5b74630e9aca0

### Crash Report (if applicable)

https://gist.github.com/KooKooGH/b19c44015afc964f0ddfcf41d8cc3fad

### Steps to Reproduce

Every time I try to enter my world.
1. Launch MC
2. Open a world
3. Crash

### What You Expect To Happen

To be let into my world to play the game

### What Actually Happened

I crashed and this has happened over 15 times each time I try to enter my world

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Update your version of Aether Redux

**Comment by KooKooGH** [comment]
crashed again https://gist.github.com/KooKooGH/58aeceff81a0ef4de40bb8b67d9a07a1

**Comment by bconlon1** [comment]
You seem to still be on Aether Redux 2.0.17, the latest version is 2.0.18 which fixed this specific crash.

**Comment by KooKooGH** [comment]
aa it worked, thank you!
