### ISSUE TITLE
Bug: Fabric Version Doesn't Include Datapacks

### ISSUE THREAD

**Issue by GraysBlock** [Gilded-Games/The-Aether#2344]
### What Feature Types Apply to This Bug?

Item, World-Gen, Other (Please Describe)

### Other Type

Datapacks

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

Fabric Loader 0.16.9

### The Aether Version

1.5.1-beta.1

### Steps to Reproduce

Step 1. Create a new world.
Step 2. Go to "More" and select "Data Packs"
Step 3. Note how there are no datapacks in the "Available" section.
![fabric_datapack_list](https://github.com/user-attachments/assets/cd217ae3-6a70-466e-9575-e46a170559d3)

### What You Expect To Happen

The Fabric version should include two built-in datapacks for Aether; "Aether Temporary Freezing" and "Aether Ruined Portals".

### What Actually Happened

This version does NOT include those two built-in packs.

### Additional Details

This seems to be a bug specifically for the Fabric version, as I tested the NeoForge version and it works perfectly as expected.
![neoforge_datapack_list](https://github.com/user-attachments/assets/17504b64-ac3c-406f-92d3-712655b3fa3c)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Seems like a simple fix as I believe that I need to adjust data pack injection event
