### ISSUE TITLE
Bug minor : Aether Advancement jingle don't play with Advancement Plaque mod installed

### ISSUE THREAD

**Issue by SkyRunner55** [Gilded-Games/The-Aether#2345]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Compatibility

### Forge Version

Neoforge 21.1.77

### The Aether Version

1.21.1 1.5.1

### Is This Bug a Conflict With Another Mod?

Advancement Plaques

### Steps to Reproduce

Get any Aether achivements with Advancement Plaque installed

### What You Expect To Happen

Earing the aether achivements jingle instead of Advancement Plaque jingle (including default, bronze, silver, gold dungeon jingle)

### What Actually Happened

Well i was killing some boss & doing some random achivements and i noticed that the sound that play is the from the aether but from advanced plaques or vanilla (for epic achivements)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [x] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by SkyRunner55** [comment]
Also off topic but its also a bug but i don't want to do two bug report in a row,
the sounds when entering the aether portal to go to the aether is not playing 

in the 1.21.1 neoforge  1.5.1 version

**Comment by bconlon1** [comment]
Seems our sound code doesn't play since Advancement Plaques overrides the normal advancement toast with its own. I'll have to think about how would be best to add compatibility here.

**Comment by bconlon1** [comment]
AdvancementPlaques will be adding some compat for this on their own soon.

**Comment by bconlon1** [comment]
https://www.curseforge.com/minecraft/mc-mods/advancement-plaques/files/5905995
