### ISSUE TITLE
Bug: <title>The Aether vs Small Ships Incompatibility (And MayBe Other Mods)

### ISSUE THREAD

**Issue by Horizoll** [Gilded-Games/The-Aether#2346]
### What Feature Types Apply to This Bug?

System, World-Gen

### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.21.1-1.5.1-beta.1

### Is This Bug a Conflict With Another Mod?

Small Ships 1.21.1 2.0.0 b1.5

### Crash Report (if applicable)

<script src="https://gist.github.com/Horizoll/3a37d8ad8af5f498d72b5822ede12cd3.js"></script>

### Steps to Reproduce

1.Download and Instal Minecraft 1.21.1
2.Download and Install Both The Aether and Small Ships (Download and Install Dependency Mods)
3.(Optional) Download Other Mods
4..Try to Launch
5. Get Launch Error Crash

### What You Expect To Happen

I Expect Game to Start!

### What Actually Happened

The Game Didnt Start

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Can you send the log file as the report dose not have a valid link

**Comment by bconlon1** [comment]
Idk why our template does this for some people, but you can grab this https://gist.github.com/Horizoll/3a37d8ad8af5f498d72b5822ede12cd3 out of the broken link and it works.

**Comment by Dragon-Seeker** [comment]
Ah good to know
 
Also: `Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: smallships:aether:skyroot_cog`

Unknown what exactly is going wrong due to the mods ARR nature which makes debugging this a bit difficult

**Comment by bconlon1** [comment]
My guess is they should be using `ResourceLocation.parse()` where they aren't for something.

**Comment by Dragon-Seeker** [comment]
Possibly but where is `skyroot_cog` coming from exactly?

**Comment by bconlon1** [comment]
I wonder if they're trying to generate a cog block automatically with the `aether:skyroot` wood type or something? Either that or they're trying to just generate a cog block inside the Aether's namespace but idk what they'd be checking to determine to do so, 
so yeah without the source code who knows.

**Comment by bconlon1** [comment]
https://github.com/talhanation/wiki/issues/1 I think my wood type theory could be correct.

**Comment by bconlon1** [comment]
Issue has been relayed to Small Ships' end on their Discord.
