### ISSUE TITLE
Bug: Crash on multplayer

### ISSUE THREAD

**Issue by iochin** [Gilded-Games/The-Aether#2347]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

multiplayer

### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.5-1.21.1

### The Aether Version

The Aether - 1.21.1-1.5.1-beta.1-fabric

### Is This Bug a Conflict With Another Mod?

no

### Client Log

https://gist.github.com/iochin/09fc667d38db560690f8d980b2eec8ae

### Crash Report (if applicable)

https://gist.github.com/iochin/09fc667d38db560690f8d980b2eec8ae

### Steps to Reproduce

open to lan
try to conect

### What You Expect To Happen

conect

### What Actually Happened

crash D:

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Should be fixed with beta.2... I hope
