### ISSUE TITLE
Bug: aether dungeons do not lock/unlock correctly using friends and foes fabric

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2354]
### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.2-fabric

### Is This Bug a Conflict With Another Mod?

Friends and Foes "friendsandfoes-fabric-mc1.21.1-3.0.5

### Steps to Reproduce

from the looks of it this always happens to every dungeon in the mod when these mods are loaded together

1 load aether and friends and foes together with dependancys
2 enter the aether and search for a dungeon
3 kill the dungeon boss

### What You Expect To Happen

what was expected to happen was the dungeons to lock and unlock correctly upon starting the boss fight and ending it

### What Actually Happened

what happened instead was that the dungeons did not lock correctly meaning you could leave during the fight and they also did not unlock correctly which means there would be unbreakable blocks you cannot remove aswell as being unable to open the stone chest as it also does not open the chest room up

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by AnukWarrior** [comment]
made a report over on the friends and foes github

https://github.com/Faboslav/friends-and-foes/issues/290

**Comment by bconlon1** [comment]
Bug is notably Fabric only and not NeoForge.

**Comment by Faboslav** [comment]
Because Forge/NeoForge already does have common solution for the structure entity processing, for fabric there is or was a PR, but that's currently it.

**Comment by Faboslav** [comment]
Also why is this already closed, dont we want to have some kind of solution?

**Comment by Dragon-Seeker** [comment]
Well it was close since the issue can only be resolved on your side with adjustment to your mixin to follow yungs API mixin
I believe

**Comment by bconlon1** [comment]
Yeah I closed the issue since it's not on our end.
