### ISSUE TITLE
Bug: crash after getting stung by aechor plant

### ISSUE THREAD

**Issue by singlen12** [Gilded-Games/The-Aether#2355]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.21.1-1.5.1-beta.1

### Client Log

https://gist.github.com/singlen12/0e21b20e03782dfd8a735485143cb316

### Crash Report (if applicable)

https://gist.github.com/singlen12/d7f2c47da85db57c8883e3ff0478938f

### Steps to Reproduce

Get attacked by aechor plant.

### What You Expect To Happen

I thought I would be attacked by the enemy and receive damage and a status effect.

### What Actually Happened

When the aechor plant attacked me, I was hurt, received a status effect for a few frames, and immediately crashed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Should be fixed with beta.2
