### ISSUE TITLE
Bug: lithium causes slider to have weird collision when active

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2357]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.2-fabric

### Is This Bug a Conflict With Another Mod?

Lithium "lithium-fabric-0.14.0-snapshot+mc1.21.1-build.88"

### Steps to Reproduce

as soon as the slider is in the active state the weird collision is always happening

1 run aether with lithium on fabric
2 find a slider and hit it with a pickaxe
3 walk into the slider

### What You Expect To Happen

to be able to walk through the slider like its not solid

### What Actually Happened

the slider has odd collision simular to that of boats being weird and causing rubber banding when attempting to walk into a active slider

### Additional Details

video clip example with only aether lithium and dependancys on fabric

https://github.com/user-attachments/assets/e5b8a560-d51a-40ef-90f5-26403d432bcd

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Confirming that this also happens on NeoForge with Lithium as well.

**Comment by bconlon1** [comment]
Seems to be related to this issue https://github.com/CaffeineMC/lithium-fabric/issues/578 since the given workaround solves this issue too, so a fix will be released soon on Lithium's end. If that release doesn't fix this issue then it can be reopened.
