### ISSUE TITLE
Bug: going into minecrafts options while inebriation debuff is active causes game to crash

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2358]
### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.2-fabric

### Client Log

https://gist.github.com/AnukWarrior/2e75fcfd8128bf5936eb7e7281010a43

### Crash Report (if applicable)

https://gist.github.com/AnukWarrior/fc857963d343b4a005f370ac1a1871d9

### Steps to Reproduce

asumeing any source of intoxication can do this it can be rather common
1 obtain inebriation debuff from cockatrice for example
2 open options menu

### What You Expect To Happen

be able to open the minecraft options menu and change my settings as i want

### What Actually Happened

minecraft insantly shuts down as soon as you press the options button

### Additional Details

video example

https://github.com/user-attachments/assets/6706f4d5-41fb-45c7-a613-13ae3700e9f7

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Ah comes down to deferred holders needing to be unpacked, simple fix
