### ISSUE TITLE
Bug: Aerogel not transparent on Fabric

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#2359]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Annoyance

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta-2

### Is This Bug a Conflict With Another Mod?

No

### Client Log

https://gist.github.com/ZolaKluke/e060f79485f539c98bbb8bc8f32defbd

### Steps to Reproduce

Look at aerogel blocks

### What You Expect To Happen

The blocks to be transparent

### What Actually Happened

Blocks can't be seen through

### Additional Details

![image](https://github.com/user-attachments/assets/79f93d93-9140-4b44-a5ba-78cd699a9c5d)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
A quick fix to put the blocks within translucent blocks render layer
