### ISSUE TITLE
Bug: When used with Traveler’s Backpack, I can no longer wear or remove the backpack.

### ISSUE THREAD

**Issue by kuretoshi** [Gilded-Games/The-Aether#2361]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Compatibility

### Mod Loader

NeoForge

### Mod Loader Version

21.1.76

### The Aether Version

1.5.1-beta1

### Is This Bug a Conflict With Another Mod?

Traveler's Backpack 1.21.1-10.1.3

### Steps to Reproduce

After installing both mods, the issue occurs when equipping or removing the backpack in both Creative and Survival modes.

### What You Expect To Happen

With the backpack in hand, pressing Left Shift + Right Click allows you to equip it. In the backpack inventory screen, clicking the button on the bottom left lets you remove it. This is the expected behavior.

### What Actually Happened

There is no response when performing the specified actions.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Cannot reproduce; equipping and unequipping seems to work fine with just The Aether and Traveller's Backpack installed. Could you get a video and try to narrow down if the issue is caused by any other mods?

**Comment by kuretoshi** [comment]
Here is a video showing how it behaves in my environment.
I'll also send the logs.
https://github.com/user-attachments/assets/b273057f-54c8-432b-823c-1ca76867e0e8
[latest.log](https://github.com/user-attachments/files/17760159/latest.log)

**Comment by Dragon-Seeker** [comment]
@kuretoshi Travelers backpack has builtin support for Accessories allowing for the equipping of backpacks within the back slot so I believe based on config value that its disabled when accessories integration is enabled
![javaw_SDpI77TohM](https://github.com/user-attachments/assets/e4cb1a8c-b505-4275-981c-63a1ec2e9320)

**Comment by kuretoshi** [comment]
@Dragon-Seeker I checked my settings, and they were not disabled.
![2024-11-18_15 34 58](https://github.com/user-attachments/assets/11f00dc6-25a2-483b-bdd3-2c0d4a1ce617)

**Comment by Dragon-Seeker** [comment]
Did you confirm if Accessories Integration was enabled as such implicitly disables the function as stated within the config

**Comment by kuretoshi** [comment]
@Dragon-Seeker Accessories Integration was enabled.
![image](https://github.com/user-attachments/assets/a0916969-44d3-434b-aad4-c894f0d24d21)

**Comment by Dragon-Seeker** [comment]
Try to disable accessories integration and retest functionality

**Comment by kuretoshi** [comment]
Disabling the setting resolved the issue. Thank you!
