### ISSUE TITLE
Bug: 1.21.1 neoforge version doesn't start

### ISSUE THREAD

**Issue by uhloin** [Gilded-Games/The-Aether#2362]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Compatibility

### Mod Loader

NeoForge

### Mod Loader Version

21.1.68

### The Aether Version

1.5.1-beta.1

### Steps to Reproduce

1. Copy aether-1.21.1-1.5.1-beta.1-neoforge.jar to mod folder
2. (optional) Copy "owo-lib-neoforge-0.12.15-beta.9+1.21.jar" to mod folder
3. Run minecraft

Get in the log:

[14:47:59.405] [main/ERROR] [loading.moddiscovery.locators.JarInJarDependencyLocator/]: Failed to load mod file META-INF\jarjar\nitrogen_internals-1.21.1-1.1.20-neoforge.jar from aether-1.21.1-1.5.1-beta.1-neoforge.jar 

Also see exception dump below

### Additional Details

[stderr.txt](https://github.com/user-attachments/files/17715367/stderr.txt)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Can you try redownloading the mod? There _was_ a briefly released beta version that was taken down that had a problem where Nitrogen wasn't loading and that looks like this issue.

**Comment by uhloin** [comment]
![image](https://github.com/user-attachments/assets/49373729-f816-4b22-8bb8-440b3c3af655)

**Comment by uhloin** [comment]
May be later I'll try update NeoForge
In any case "owo" mod should be specified as required dependency on the curseforge

**Comment by bconlon1** [comment]
It is
![image](https://github.com/user-attachments/assets/9900eba5-e7f6-47a7-b7f5-3b1a2f380fd5)

**Comment by bconlon1** [comment]
Also your NeoForge is out of date.

**Comment by bconlon1** [comment]
Oh, it seems despite specifying the required dependencies in the files it doesn't apply to default relations, annoying. I'll update that as well.

Edit: Done.

**Comment by uhloin** [comment]
![image](https://github.com/user-attachments/assets/a9d3ee03-926a-4bb8-902c-b5334a87bc04)

**Comment by uhloin** [comment]
Attempt to load a world created in NeoForge 21.1.68

![image](https://github.com/user-attachments/assets/d707a4a3-2603-4c4e-85ca-be1ec125493e)

**Comment by Dragon-Seeker** [comment]
Can you send the log file for the given instance?

**Comment by uhloin** [comment]
If I remove

mods/aether-1.21.1-1.5.1-beta.1-neoforge.jar
mods/owo-lib-neoforge-0.12.15-beta.9+1.21.jar

then no problems with loading

**Comment by bconlon1** [comment]
![image](https://github.com/user-attachments/assets/7386af42-ddbc-4f44-a702-ae8fc399799b)
I've updated the dependencies on the page's settings hours ago, I have no idea how CurseForge hasn't updated them on the front end yet.

**Comment by bconlon1** [comment]
> If I remove
> 
> mods/aether-1.21.1-1.5.1-beta.1-neoforge.jar mods/owo-lib-neoforge-0.12.15-beta.9+1.21.jar
> 
> then no problems with loading

Then we need the log.

**Comment by uhloin** [comment]
[log.txt](https://github.com/user-attachments/files/17726220/log.txt)

**Comment by bconlon1** [comment]
Ah, there will be another beta release soon to fix this issue.

**Comment by uhloin** [comment]
thank you :)

**Comment by bconlon1** [comment]
https://www.curseforge.com/minecraft/mc-mods/aether/files/5899060 here it is now

**Comment by uhloin** [comment]
Yes
aether-1.21.1-1.5.1-beta.2-neoforge.jar 
- is OK. 

Old world is loaded and I was able to enter Aether dimension.

Although, when I tried to step back then I was moved to new different portal in the Overworld. It's still works.
