### ISSUE TITLE
Bug: Shield cannot resist damage

### ISSUE THREAD

**Issue by syjrgdt** [Gilded-Games/The-Aether#2363]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

Fabric-0.16.9-1.21.1

### The Aether Version

1.5.1-beta2

### Steps to Reproduce

1.Create a new world
2./give @s minecraft:shield
3.Summon a creeper
4./gamemode survival
5.Raise your shield

https://github.com/user-attachments/assets/95d73290-63dd-4070-b168-a6dc8c45dbfe

### What You Expect To Happen

Shield can resist explosion damage

### What Actually Happened

Shield cannot resist explosion damage

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Ah yes the event for such was implemented incorrectly, will fix such
