### ISSUE TITLE
Bug: Farmer's Delight Refabricated prevents bosses from spawning.

### ISSUE THREAD

**Issue by ForestMinecraft** [Gilded-Games/The-Aether#2364]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.21.1-1.5.1-beta.2-fabric

### Is This Bug a Conflict With Another Mod?

It is a conflict with Farmer's Delight Refabricated.

### Steps to Reproduce

Install Farmer's Delight Refabricated and find any dungeon and go to the boss room.

### What You Expect To Happen

The boss should spawn.

### What Actually Happened

The boss didn't spawn.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Is this with the Aether only as in not within a modpack?

**Comment by ForestMinecraft** [comment]
Just tested it by itself, the bosses spawn. I will see if I can figure out what mod is preventing them from spawning.

**Comment by ForestMinecraft** [comment]
Farmer's Delight Refabricated was preventing the bosses from spawning.

**Comment by Dragon-Seeker** [comment]
> Farmer's Delight Refabricated was preventing the bosses from spawning.

): another incompat with such as fog rendering is know to be broken. Most likely another porting lib incompat

**Comment by greenmg2003** [comment]
Canconfirm, Farmer's Delight did prevent it
