### ISSUE TITLE
Enhancement: Aerogel Blocks' model rendering

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#237]
- This covers Aerogel Stairs, Slabs, and Walls.
- The goal is to try to make it so these blocks render certain interior parts as invisible when next to other aerogel blocks, so rendering is seamless (similar to how when looking at a glass block you can't see the sides of glass blocks placed next to it).
- This was worked on but never fully implemented.

**Comment by bconlon1** [comment]
Related Issues:
- #75

**Comment by muzikbike** [comment]
Would it be possible to assign special block states to aerogel-related blocks that changes their models to use face planes made up of smaller texture planes which are partially culled depending on neighbouring blocks? For example, a slab next to aerogel would cause the face of the aerogel block to be made up of two rectangles, with which one is culled depending on the block half the slab occupies.
