### ISSUE TITLE
Bug: Game crash while starting with mod Tips

### ISSUE THREAD

**Issue by NumberSir** [Gilded-Games/The-Aether#2372]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

compatibility

### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta.3

### Is This Bug a Conflict With Another Mod?

modid: tipsmod; version: 21.1.2

### Client Log

https://gist.github.com/NumberSir/a26f1ba39a04d0636d3e65715446e41b

### Crash Report (if applicable)

https://gist.github.com/NumberSir/441005aea8f170232cb66dd8caa442e8

### Steps to Reproduce

install 
- [The Aether - 1.21.1-1.5.1-beta.3-fabric](https://modrinth.com/mod/aether/version/1.21.1-1.5.1-beta.3-fabric)
- [oωo - 0.12.15](https://modrinth.com/mod/owo-lib/version/0.12.15+1.21)
- [Bookshelf-fabric-1.21.1-21.1.13](https://modrinth.com/mod/bookshelf-lib/version/21.1.13)
- [PrickleMC-fabric-1.21.1-21.1.6](https://modrinth.com/mod/prickle/version/21.1.6)
- [Tips-fabric-1.21.1-21.1.2](https://modrinth.com/mod/tips/version/21.1.2)

then start the game

### What You Expect To Happen

game starts well

### What Actually Happened

game crashed

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
My current theory is that our code for reloading the Tips compatibility resource pack according to a config here https://github.com/The-Aether-Team/The-Aether/blob/ef6706245a4feb7e75ec0feb3efc964470dabf1c/src/main/java/com/aetherteam/aether/client/AetherClient.java#L139 and here https://github.com/The-Aether-Team/The-Aether/blob/ef6706245a4feb7e75ec0feb3efc964470dabf1c/src/main/java/com/aetherteam/aether/client/AetherClient.java#L200 has to be moved to a later point in client loading or something. This also seems to happen only on Fabric which is interesting. However on both loaders it seems our Tips compatibility is also out of date which will have to be fixed.
