### ISSUE TITLE
Bug: White Text on the "Book of Lore"

### ISSUE THREAD

**Issue by Andres14noob** [Gilded-Games/The-Aether#2373]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Design

### Mod Loader

Fabric

### Mod Loader Version

0.16.7-1.21.1

### The Aether Version

The Aether - 1.21.1-1.5.1-beta.3-fabric

### Is This Bug a Conflict With Another Mod?

I don't Think so 

### Steps to Reproduce

Book of lore
1. Make a Portal to the aether
2. Get the book
3. put an aether item in the book

### What You Expect To Happen

When i used the book of lore i thought the text would be black to be redable

### What Actually Happened

the text was just white and it was almost unredable because it was white and the book background was white too

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Cannot reproduce, may need more info.
