### ISSUE TITLE
Bug: <title>Odd custom Aether main menu dysfunction

### ISSUE THREAD

**Issue by JohnGoten** [Gilded-Games/The-Aether#2377]
### What Feature Types Apply to This Bug?

Gui, Other (Please Describe)

### Other Type

Cumulus Aether Main Menu

### What Type of Bug Is This?

Compatibility

### Mod Loader

NeoForge

### Mod Loader Version

21.1.77

### The Aether Version

1.5.1-beta.2

### Is This Bug a Conflict With Another Mod?

Curios Compat Layer for Accessories 9.0.12+1.21.1 | FancyMenu 3.2.2 + Konkrete 1.9.9 + Melody 1.0.10 | Seamless Loading Screen 2.2.1+1.21

### Client Log

https://gist.github.com/JohnGoten/07f2b928d4a2a146fd99fedd2b2bb8ee

### Steps to Reproduce

Install the mod list as shown in the client log (latest.log directly from Prism)
Enable either of the mods which cause a conflict between it and The Aether I
Switch to the Aether themed main menu using the button up top

### What You Expect To Happen

A visual change from the 1.21.1 default main menu to that of the Aether I's alongside its moved button layout

### What Actually Happened

The main menu remains the same visually and functionally as that of the vanilla 1.21.1 game

### Additional Details

Here's the "odd" part of my investigation as just a casual end user:
In an isolated instance with NeoForge 21.1.77 as well as The Aether I, Curios Compat Layer, FancyMenu and Seamless Loading Screen the bug in question does not appear to occur at all.
I am fully aware that with more time on my hands I could possibly manage to figure out more culprits to this matter, it was requested of me to report this on the tracker for now. Not to mention that I do lack the truly technical understanding of what is exactly happening here.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Some pending Cumulus reworks should fix this.
