### ISSUE TITLE
Bug: <title>crash on startup

### ISSUE THREAD

**Issue by heyoux** [Gilded-Games/The-Aether#2378]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

startup crash

### What Type of Bug Is This?

Crash

### Mod Loader

Neoforge

### Mod Loader Version

21.1.177

### The Aether Version

1.5.1-beta.3

### Client Log

https://gist.github.com/heyoux/000a7b936b79fa69d0dd0d24a317ee6c

### Crash Report (if applicable)

https://gist.github.com/heyoux/4b9e28ae60df238e71f2af0bdc427ea7

### Steps to Reproduce

Game crashes when launching

### What You Expect To Happen

Game launches

### What Actually Happened

Game crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by SHXRKIEgg** [comment]
I have this same issue but it was the Champions Unofficial mod causing it for me because disabling it made me able to launch the modpack but I dont see that this person has that mod so it could be another conflict

**Comment by Dragon-Seeker** [comment]
Duplicate issue of https://github.com/The-Aether-Team/The-Aether/issues/2346

**Comment by bconlon1** [comment]
Small Ships' crash creates other seemingly unrelated crashes like this one.
