### ISSUE TITLE
Feature Request: <title>1.21.3(fabric)

### ISSUE THREAD

**Issue by ghost** [Gilded-Games/The-Aether#2380]
### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

1.21.3 support on fabric loader.

### Why Should It Be in the Mod?

Cuz yes.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
not yet

**Comment by ghost** [comment]
> not yet

why??????

**Comment by Dragon-Seeker** [comment]
Reasons:
- Neoforge 1.21.3 has not even started
- Accessories is ported to 1.21.3 but unreleased trying to polish some changes to owo and deal with problems with the aether fabric port
