### ISSUE TITLE
Bug: New portals being created when traversing worlds

### ISSUE THREAD

**Issue by Rimplestilt** [Gilded-Games/The-Aether#2381]
### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Neoforge

### Mod Loader Version

21.1.72

### The Aether Version

1.5.1-beta.3

### Steps to Reproduce

New portals were being created when going through an  aether portal.

### What You Expect To Happen

Shouldn't duplicate.

### What Actually Happened

It duplicated

### Additional Details

I am using the Nether portal fix in my modpack, I'm not sure why this could possibly break the aether portal, but perhaps? 
I'm making this report because comments are disabled in curseforgr, and because the portals spawned and ruined my house lol.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is an issue sometimes caused by performance mods if they mess with portal position checks. One known performance mod that currently does this in 1.21.1 is BadOptimizations, but if you don't have that you might have to narrow down what other performance mod is causing it.

**Comment by Chaoschaps** [comment]
If you have Lithium installed you have to set `mixin.ai.poi` to `false` something in there is interfering with the portals (it isn't `mixin.ai.poi.fast_portals` as changing this setting doesn't fix the issue).

**Comment by Rimplestilt** [comment]
> If you have Lithium installed you have to set `mixin.ai.poi` to `false` something in there is interfering with the portals (it isn't `mixin.ai.poi.fast_portals` as changing this setting doesn't fix the issue).

thank you! I am using Lithium, so that could be a likely cause. I'll try that soon
