### ISSUE TITLE
Aether is crashing my client after adding Advent of Ascension Mod

### ISSUE THREAD

**Issue by btd6player27** [Gilded-Games/The-Aether#2384]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Issue with Cumulus

### What Type of Bug Is This?

Crash

### Mod Loader

NeoForge

### Mod Loader Version

21.1.72  for minecraft 1.21.1

### The Aether Version

1.5.1 beta 3 

### Is This Bug a Conflict With Another Mod?

Advent of Ascension

### Crash Report (if applicable)

https://gist.github.com/btd6player27/4cf6a95781e7bcbc957092665935d8b8

### Steps to Reproduce

Game is working without advent of ascension, can get into aether everythings fine all worlds dimensions good. I add advent of ascension to my modpack, now i get this crash report. I talked to devs of that mod, they say all the issues are related to aether code and advent of ascension is working properly.  

### What You Expect To Happen

install mods, game works 

### What Actually Happened

install mod, game crashes 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
I need a full client log here, since this may be caused by a conflict with another mod I know of.

**Comment by btd6player27** [comment]
https://gist.github.com/btd6player27/f4e481aed84af9693b9577a15377e5e4

when i had the aether working i did not have cumulus menus mod installed, i only added that after i added AoA and got the error because i thought missing cumulus latest version was the issue

**Comment by bconlon1** [comment]
Could you try the build of Aether from this message: https://github.com/The-Aether-Team/Cumulus/issues/22#issuecomment-2484037851? I've yet to release it but it might either result in a fix or a more clear log with the issue.

**Comment by btd6player27** [comment]
should i try it with or without cumulus

**Comment by bconlon1** [comment]
Either works, the version you downloaded is packaged in that build of Aether so I don't think it matters.

**Comment by btd6player27** [comment]
ok done, heres new logs: https://gist.github.com/btd6player27/64804a0343c543161f8ee9b7b53e19eb

**Comment by bconlon1** [comment]
Could you try removing UnionLib from your mods list?

**Comment by bconlon1** [comment]
And if it crashes again provide the client log.

**Comment by btd6player27** [comment]
everythings working now. thats strange, i couldve sworn i needed unionlib for something else. guess not

**Comment by btd6player27** [comment]
let me just see if i can get into both dimensions

**Comment by btd6player27** [comment]
everything is working, only one small thing, the aether portals are weird. I can never take the same one twice it just keeps making duplicate portals all over the place

**Comment by bconlon1** [comment]
Likely an issue with a performance mod such as BadOptimizations, you'd have to check the mods for a conflict.

**Comment by btd6player27** [comment]
it was lithium.... why does it do that ?

**Comment by bconlon1** [comment]
Interesting, report it to their issue tracker so they know to look into it: https://github.com/CaffeineMC/lithium-fabric/issues
