### ISSUE TITLE
Bug: Error occurred when connecting to the multiplayer server.

### ISSUE THREAD

**Issue by kuretoshi** [Gilded-Games/The-Aether#2385]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Compatibility

### Mod Loader

NeoForge

### Mod Loader Version

21.1.80

### The Aether Version

1.21.1-1.5.1-beta.3

### Is This Bug a Conflict With Another Mod?

neoforwarding-1.2.1-1.21.X-NeoForge

### Client Log

https://gist.github.com/kuretoshi/9bbfb9b49fc1702b42d9ec0bd59fdc5a

### Steps to Reproduce

It occurred when connecting to a multiplayer server.
The environment includes the mentioned mod, and the connection is made via VelocityMC.
The Velocity version used is "velocity-3.4.0-SNAPSHOT-450".

### What You Expect To Happen

Able to connect without issues.

### What Actually Happened

An error occurred as shown in the logs and on the screen.
https://gist.github.com/kuretoshi/fddc11130bbedc62ffa63b2d209e2a3c
![image](https://github.com/user-attachments/assets/9c92c739-de3d-41a2-99ab-b0f074428802)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Seems like an incompatibility with Forgified Fabric API and [NeoForwarding](https://modrinth.com/mod/neoforwarding)
