### ISSUE TITLE
Bug: Mimic rendering with Embeddium

### ISSUE THREAD

**Issue by zeroneon** [Gilded-Games/The-Aether#2386]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### The Aether Version

1.5.1

### Is This Bug a Conflict With Another Mod?

Embeddium 0.3.31/Oculus 1.7.0

### Client Log

https://gist.github.com/zeroneon/8ad20651a2bf364b2570e0f3e43b5a04

### Crash Report (if applicable)

https://gist.github.com/zeroneon/a84827d4a01149cf9ddfd3fada447f53

### Steps to Reproduce

1. go to first dungeon
2. be amazed

### What You Expect To Happen

No crash

### What Actually Happened

crash

### Additional Details

I just updated Embeddium and The Aether. Previous versions worked fine.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Your Lootr version is likely outdated and incompatible, please update it to the latest version.
