### ISSUE TITLE
(minor audio bug) 1.21.1, no sound when entering the aether portal

### ISSUE THREAD

**Issue by SkyRunner55** [Gilded-Games/The-Aether#2387]
### What Type of Bug Is This?

Audio

### Mod Loader

Neoforge

### Mod Loader Version

21.1.80

### The Aether Version

1.21.1 1.5.1beta.3

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

Enther a aether Portal

### What You Expect To Happen

Earing the sound when entering the portal (like the nether)

### What Actually Happened

Nothing sadly

### Additional Details

https://github.com/user-attachments/assets/ab637659-d85d-4076-9ad7-22289f0ba84b

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Cannot reproduce, can you provide more info like mods list and logs?

**Comment by bconlon1** [comment]
Actually wait nevermind.

**Comment by bconlon1** [comment]
Seems unrelated to #2352, the sound can be played but it isn't being played by portals, so it must be some code issue I have to look into.
