### ISSUE TITLE
Feature Request: Config option to sync overworld and aether time

### ISSUE THREAD

**Issue by rinOfTheStars** [Gilded-Games/The-Aether#2388]
### What Feature Types Apply to This Request?

Config, System

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A config option that, when enabled, causes the day/night cycle in the aether to correspond with the day/night cycle in the overworld once eternal day is banished (whether that be through killing a Sun Spirit for the first time or having eternal day disabled in the config as well). 

### Why Should It Be in the Mod?

For modpacks using Immersive Portal's dimension stacking feature, having a synchronized day/night cycle would help improve the illusion of seamlessness when looking up or down between dimensions, as demonstrated in these screenshots: 
![2024-11-23_19 32 53](https://github.com/user-attachments/assets/bf24d91c-a76c-407c-8622-567d921a45b3)
![2024-11-23_19 34 09](https://github.com/user-attachments/assets/82d50bbd-16ae-4276-8446-dd88bfee5423)
Depending how complicated of a feature this is, and how much time and physical capacity I have to dedicate to such a thing, I might be able to make a PR for this feature myself, hopefully?  

### Does This Feature Improve Compatibility With Another Mod?

Immersive Portals

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Yeah unfortunately this is not something I have been able to figure out, I'd be willing to accept a PR but I myself can't figure out a good way to handle this seamlessly due to how Minecraft handles level data and time between dimensions and the methods used for setting such.

**Comment by rinOfTheStars** [comment]
If I can figure out a good way to do it I'll make a PR, then.

**Comment by bconlon1** [comment]
Thought of a potential solution that I'll have to try.
