### ISSUE TITLE
Valkyrie Hoe has no right-click function

### ISSUE THREAD

**Issue by Endroid26** [Gilded-Games/The-Aether#2390]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta.4

### Client Log

https://gist.github.com/Endroid26/c1921b8bafbeb064897f65c471229076

### Steps to Reproduce

Use a Valkyrie Hoe on Dirt or Aether Dirt.

### What You Expect To Happen

The Valkyrie Hoe tills the dirt, similar to vanilla hoes.

### What Actually Happened

Nothing happens.

### Additional Details

The tilling does work with all other Aether hoes. The Valkyrie Hoe is the only exception.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
See the problem as code to perform the Hoeing action was not properly ported so nothing would happen, will fix for the next update
