### ISSUE TITLE
Freezer block fails to output frozen items

### ISSUE THREAD

**Issue by Endroid26** [Gilded-Games/The-Aether#2391]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta.4

### Client Log

https://gist.github.com/Endroid26/c1921b8bafbeb064897f65c471229076

### Steps to Reproduce

Input an Iron (or Gold) ring or pendant into the Freezer with Icestone as fuel.

### What You Expect To Happen

The Freezer outputs an Ice Ring or Pendant.

### What Actually Happened

The Freezer outputs the same item in the freezing slot.

### Additional Details

XP is still given after collecting the output, but the item itself does not change at all.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Can confirm this issue and such exists for Neoforge as well
