### ISSUE TITLE
Bug: when i put a glove in an armor stand, i cant get it back, even if i break the armor stand

### ISSUE THREAD

**Issue by idk387** [Gilded-Games/The-Aether#2392]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

fabric

### Mod Loader Version

what

### The Aether Version

1.21.1.-1.5.1-beta.4

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

1- put a glove in a armor stand
2- cant get the glove
3- breaks the armor stand so the glove drops
4- doesnt drop and i lose the glove

### What You Expect To Happen

i wish i could pick it up

### What Actually Happened

cant pick the glove up

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Tried to reproduce such an issue but could not as testing within dev such dose did not occur.
