### ISSUE TITLE
Config T and W in main menu

### ISSUE THREAD

**Issue by KaozSpartan** [Gilded-Games/The-Aether#2393]
### What Feature Types Apply to This Request?

Config, Other (Please Describe)

### Other Type

Fix

### Is This an Enhancement to a Preexisting Feature?

- [x] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Hey there, I know this wont be priority but would it be possible to config to be able to disable the T and W in the main menu or adjust its placement? It essentially breaks mods like Legacy4J and I'd love to be able to disable it. When trying to return, youre locked into only viewing the languages.

![Desktop Screenshot 2024 11 24 - 10 42 28 42](https://github.com/user-attachments/assets/d2a1dff1-d15a-426d-acbe-cb14373b351d)
![Desktop Screenshot 2024 11 24 - 10 42 24 91](https://github.com/user-attachments/assets/4a6083a2-af2c-48da-9f54-82dbe4fbc258)

### Why Should It Be in the Mod?

This overall is small and yes could be avoided but it'd would be a lot easier than giving a disclaimer to anyone who uses both these popular mods.

### Does This Feature Improve Compatibility With Another Mod?

yes

### Please Read and Confirm the Following

- [x] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
These options already exist in the mod's client config.
