### ISSUE TITLE
Feature Request: Tag Blue Berries as #forge:berries

### ISSUE THREAD

**Issue by Qwerty97475** [Gilded-Games/The-Aether#2395]
### What Feature Types Apply to This Request?

Item, System

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Tag Blue Berries as #forge:berries, as it helps with inter-mod integration using the forge system

### Why Should It Be in the Mod?

It makes sense

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Qwerty97475** [comment]
In addition, Blue Berr[ies] should also be tagged as #forge:berries

**Comment by bconlon1** [comment]
Do you mean the #c:berry tag? https://github.com/The-Aether-Team/The-Aether/blob/1.21.1-develop/src/generated/resources/data/c/tags/item/foods/berry.json

**Comment by Qwerty97475** [comment]
I’m currently on 1.20.1 Forge, where there aren’t C: tags. Unless 1.20.1 isn’t supported anymore, shouldn’t this be backported?

**Comment by bconlon1** [comment]
Ah, probably won't be backporting it with how minor of an issue it is and since it can be fixed with datapacks.
