### ISSUE TITLE
Bug: fire aspect does not cook meat dropped from aether animals if they are killed by the weapon with fire aspect

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2396]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Annoyance

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.4-fabric

### Steps to Reproduce

pretty freaquent considering a crit can one hit most of the animals
1 get a weapon with fire aspect
2 insta kill a aether animal with said weapon

### What You Expect To Happen

what was expected was for the meat the aether animal can drop to be cooked with fire aspect

### What Actually Happened

the meat drops as raw unless you specificly let the fire get the killing blow

### Additional Details

https://github.com/user-attachments/assets/0d12706d-671e-42b5-9207-28e6a76d6dab

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
@bconlon1 I can replicate this on Neoforge. Best way to replicate such is using the Pig Slayer with Fire Enchant
