### ISSUE TITLE
Bug: ambrosium torches drop regular minecraft torches if placed on the side of a block

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2397]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Annoyance

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.4-fabric

### Steps to Reproduce

very freaquent a player on my server was finding it rather anoying
1 place a ambrosium torch on the side of a wall
2 break the torch

### What You Expect To Happen

what was expected was for a ambrosium torch to drop

### What Actually Happened

instead a regular minecraft torch drops which cannot be placed in the aether

### Additional Details

https://github.com/user-attachments/assets/893dcf28-7c70-4279-8748-8f7cf00f8a10

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Yep, I have a fix within dev that will get updated sometime coming up
