### ISSUE TITLE
Bug: valk lance can be enchanted with incorrect enchantments at the enchanting table

### ISSUE THREAD

**Issue by AnukWarrior** [Gilded-Games/The-Aether#2398]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

aether-1.21.1-1.5.1-beta.4-fabric

### Steps to Reproduce

very freaquent
1 obtain a valk lance
2 enchant the lance at a enchanting table

### What You Expect To Happen

what was expected was for the lance to get the correct enchantments it can accpect

### What Actually Happened

instead what happens is the lance can get junk enchantments like protection resperation infinity and so on

### Additional Details

https://github.com/user-attachments/assets/4cfc4ac4-90e2-4326-806e-16a07845ea19

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
.... that is quite weird ngl wonder If I mess up the enchantment checking code or something
