### ISSUE TITLE
Feature Request: Update ring recipes

### ISSUE THREAD

**Issue by MuteTiefling** [Gilded-Games/The-Aether#2402]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Change Iron and Gold Ring recipes to be less likely to conflict with other mods.

I'd propose the following:

![image](https://github.com/user-attachments/assets/15fb2c31-8351-4855-a82b-82a5ec2bfc75)

### Why Should It Be in the Mod?

The Iron and Gold Ring recipes conflict with long standing 'default' gear recipes for many mods. I'd like to suggest that they be changed to be less likely to conflict

### Does This Feature Improve Compatibility With Another Mod?

yes! Many

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This is fixable with data-packs that change the recipes for modpacks to deal with mod conflicts.

**Comment by MuteTiefling** [comment]
I know, and I plan to. This one just feels so likely to conflict that it'd probably be beneficial for it to change in the mod.

**Comment by bconlon1** [comment]
The recipe is probably gonna be kept the same considering that's how its been for so long and even alongside these kinds of mods and its not actually been that common of an issue.

**Comment by Dragon-Seeker** [comment]
@MuteTiefling You can also use a mod like [Polymorph](https://modrinth.com/mod/polymorph) that would help with multiple conflicting crafting recipes

**Comment by MuteTiefling** [comment]
Yep. That's how I detected this in the first place. I run a conflict report every now and then to ensure things aren't getting out of hand
