### ISSUE TITLE
Bug: Crash on serveru startup on modpack.

### ISSUE THREAD

**Issue by Akinesis** [Gilded-Games/The-Aether#2407]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

The Aether - Fabric - 1.21.1-1.5.1-beta.5

### Is This Bug a Conflict With Another Mod?

UselessReptile - 0.8.3-1.21.1

### Crash Report (if applicable)

https://gist.github.com/Akinesis/be87aaca3e81458dff1b2c92614ffad7

### Steps to Reproduce

Start the server with Aether and Useless Reptile mod instaled.
Crash occure on startup.

### What You Expect To Happen

The server should launch without crash.

### What Actually Happened

Crash with Mixins of Useless Reptile.
The serveur works fine without The Aether?

### Additional Details

I've run a serveur with large modpack.
When added The Aether mod, a crash on Useless Reptile occure.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is a conflict that's due to Axiom and has to be brought up to them and fixed on their end.
