### ISSUE TITLE
Bug: <title> Portal Dublication upon entering 

### ISSUE THREAD

**Issue by evan0336** [Gilded-Games/The-Aether#2408]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

NeoForge

### Mod Loader Version

1.5.1

### The Aether Version

1.21.1

### Steps to Reproduce

Anytime a aether portal is entered

### What You Expect To Happen

One portal to spawn when originally entered. Should not move in either aether or overworld when entering portal or spawn addional portals 

### What Actually Happened

when portal entered 1-3 portals spawn in either aether or overworld. Spawn of portal changes each time changing dimensions. Will change location of portal each time entered. 

### Additional Details

I have the twilight forest mod, distant horizons, sodium, and lithium, dunno if these would effect. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Dragon-Seeker** [comment]
Can you send a log as this might be related to an issue with lithium and one of its POI optimization.

**Comment by bconlon1** [comment]
This would be a lithium bug yeah, there's a way to turn off its POI portal optimizations in the config. https://github.com/CaffeineMC/lithium-fabric/blob/develop/lithium-fabric-mixin-config.md
