### ISSUE TITLE
Feature Request: EveryCompat support

### ISSUE THREAD

**Issue by Gamemassa** [Gilded-Games/The-Aether#2410]
### What Feature Types Apply to This Request?

Block

### Other Type

Maybe Art as well, not really sure.

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Not sure if this is something that would be added from your end or [EveryCompat](https://modrinth.com/mod/every-compat) team's end, but EveryCompat currently does not appear to be able to see the custom wood types from Aether.

### Why Should It Be in the Mod?

It would be cool to be able to craft variants of both vanilla wood items and wood items from other mods (fences/walls/furniture/etc.) using Aether wood types.

### Does This Feature Improve Compatibility With Another Mod?

EveryCompat

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
You would have to ask the EveryCompat devs, I'm not sure what they would be requiring for finding wood types that we don't have.

**Comment by Gamemassa** [comment]
> You would have to ask the EveryCompat devs, I'm not sure what they would be requiring for finding wood types that we don't have.

They have this written on their Modrinth page:

![image](https://github.com/user-attachments/assets/6447afc7-417b-4813-af3f-5696a2f8546b)

TBH I'm not 100% how that API thing works, but hopefully that helps.


- **Edit**: not sure why it didn't work the first time, but apparently EveryCompat _is_ seeing Skyroot from your mod. Apologies for the confusion. (Though it's not seeing Golden Oak, but not sure if that's intentional).

**Comment by bconlon1** [comment]
Hmm, I'm guessing the Golden Oak isn't working because it doesn't have a wood type. I'd have to see if there's any examples of EveryCompat working with logs without planks since that would be the case  here.

**Comment by Gamemassa** [comment]
Oh, does Golden Oak just give regular Oak planks normally?

**Comment by bconlon1** [comment]
It gives Skyroot (despite the name), the only unique block for Golden Oak is basically the log and wood block.

**Comment by Gamemassa** [comment]
Oh that's fine then. If Golden Oak is just Skyroot with different bark then I think technically EveryCompat is finding it (though I think there are a handful of objects that are actually just crafted using raw logs, so I will check those later this morning).
