### ISSUE TITLE
Bug: Aether Possibly Causing Crash

### ISSUE THREAD

**Issue by Gamemassa** [Gilded-Games/The-Aether#2411]
### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta5

### Client Log

https://mclo.gs/lCffeXG

### Crash Report (if applicable)

https://mclo.gs/8EjOGmW

### Steps to Reproduce

Launch the game.

### What You Expect To Happen

Successful launch

### What Actually Happened

Crash to Desktop

### Additional Details

Not 100% sure if Aether is _causing_ this crash, but it happened when I added Aether to my custom modpack and when I removed Aether, I'm able to load just fine.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This appears to be a crash from the `blockmeter` mod.

**Comment by Gamemassa** [comment]
> This appears to be a crash from the `blockmeter` mod.

Weird. I'll pass it along to them. Thanks!
