### ISSUE TITLE
Another version Request: 1.21 fabric version maybe?

### ISSUE THREAD

**Issue by GodReza** [Gilded-Games/The-Aether#2417]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

version 1.21 fabric

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

maybe a 1.21 fabric version, that would be so much needed for someone like me who has tons of mods in this version, is it in progress or not yet? please reply

### Why Should It Be in the Mod?

that would be so good and im sure many players are waiting for that

### Please Read and Confirm the Following

- [ ] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [ ] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
There is already a a 1.21 Fabric version on both CurseForge and Modrinth, but it is currently in beta.

**Comment by GodReza** [comment]
i saw only 1.21.1 , does that work with 1.21 ?
