### ISSUE TITLE
Bug: Not sure if its a bug or incompatibility...

### ISSUE THREAD

**Issue by agorath863** [Gilded-Games/The-Aether#2418]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### The Aether Version

1.5.1

### Is This Bug a Conflict With Another Mod?

No Clue Honestly...

### Crash Report (if applicable)

https://mclo.gs/pW1HxbG

### Steps to Reproduce

after changing out pams harvestcraft for croptopia, and adding the silent gems mod, I opened my game. It loaded to the main menu and when I select singleplayer it just says "preparing for world creation" then just cuts to "saving world" and then crashes with the crash report linked.

### What You Expect To Happen

well after doing a little digging, I tried deleting all my saves and renaming the saves folder to no avail. I expect my game to open and for me to create a world.

### What Actually Happened

it crashed?

### Additional Details

I'm being honest when I say this, I cannot confirm most of the selection boxes below. I am using Optifine, but it was not causing issues before now. I'm really not sure if others have reported something similar or not. I'm not on the latest version of Minecraft but the most recent update of forge for 1.20.1.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Do you have the world preview system enabled for viewing your latest save?

**Comment by agorath863** [comment]
I don't even know. like I said I've deleted all of my saves. how would I find that?

**Comment by bconlon1** [comment]
If you go to the Aether's client config in the configs folder there should be an option "Enables world preview", what is it set to?

**Comment by agorath863** [comment]
it is set to "false", does it need to be true?

**Comment by bconlon1** [comment]
Hmm, if it's false that should be correct. Could you try looking in a client config file with the name Cumulus, there should be an option to disable the menu system which may stop the crash from occurring.

**Comment by agorath863** [comment]
it'll be the "enablemenuapi" option correct?

**Comment by bconlon1** [comment]
Should be, I think

**Comment by agorath863** [comment]
that unfortunately did not work heres the crash report.
https://mclo.gs/1nx7oJv

**Comment by agorath863** [comment]
well, I figured it out. it was another mod entirely that was causing the issue. my apologies, though this issue was not obvious.

**Comment by bconlon1** [comment]
No worries, what mod was conflicting?

**Comment by agorath863** [comment]
The Extended Silence Mod. I don't think it was An Incompatibility with your mod though as when I uninstalled your mod my game still crashed :( . it was just an addition to the Silent Gems Mod so its not super necessary. But it was an issue with that mod and probably something like Biomes O Plenty, that affects world making.
