### ISSUE TITLE
Crash after launching

### ISSUE THREAD

**Issue by IACTU** [Gilded-Games/The-Aether#2420]
### What Feature Types Apply to This Bug?

Config

### What Type of Bug Is This?

Crash

### Mod Loader

Neoforge

### Mod Loader Version

21.1.82

### The Aether Version

1.21.1-1.5.1-beta.4-neoforge

### Client Log

https://gist.github.com/IACTU/2886c428ffda0a05a3160689d315a770

### Crash Report (if applicable)

https://gist.github.com/IACTU/763f8133a8874f021ab364c746cec033

### Steps to Reproduce

Launch the game

### What You Expect To Happen

Game to launch to main menu

### What Actually Happened

Game crashes near the end of the loading screen

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Incompatibility between Tesseract and Modern Industrialization
