### ISSUE TITLE
Bug: Crash on server startup

### ISSUE THREAD

**Issue by xFrah** [Gilded-Games/The-Aether#2423]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta.5-fabric.jar

### Client Log

https://gist.github.com/xFrah/c50b1d7c2d50042d896ae2cf679017e8

### Steps to Reproduce

1. Run the server
2. Crash

### What You Expect To Happen

Not crash

### What Actually Happened

It crashed

### Additional Details

I guess this is a compatibility issue, but I can't pinpoint the incompatibility.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This is an axiom incompatibility due to an embedded version of mixinconstraints that doesn't work with the latest version of mixinextras that Aether uses; you'll have to bring this up to the axiom devs.

**Comment by xFrah** [comment]
Thank you so much!!!! I didn't even want to use Axiom.
