### ISSUE TITLE
Bug: Crash with some Addons

### ISSUE THREAD

**Issue by Yoshiman5551** [Gilded-Games/The-Aether#2426]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Mod Loader

NeoForge (or I guess Forge, as NeoForge 1.20.1 is basically Forge)

### Mod Loader Version

Minecraft 1.20.1 (Neo)Forge 47.1.106

### The Aether Version

1.5.1

### Is This Bug a Conflict With Another Mod?

Possibly, modlist here: https://gist.github.com/Yoshiman5551/8ed6c587c910c6dafde0b59f96ee248d

### Client Log

https://gist.github.com/Yoshiman5551/c7d1c27c4d20da9d85e4170487a2258e

### Crash Report (if applicable)

https://gist.github.com/Yoshiman5551/352ccc51de0ecff3be4ebfc7b1c9bc33

### Steps to Reproduce

Step 1. Open game
Step 2. Press Singleplayer
Step 3. Crash :(

### What You Expect To Happen

World creation screen opened

### What Actually Happened

Crash

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [x] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
I think you're using outdated addon versions

**Comment by Yoshiman5551** [comment]
Okay.

**Comment by Yoshiman5551** [comment]
Figured it out, it's this issue with Ancient Aether:
https://github.com/Builderdog841/Ancient-Aether/pull/209
https://github.com/Builderdog841/Ancient-Aether/issues/208
https://github.com/Builderdog841/Ancient-Aether/issues/207
https://github.com/Builderdog841/Ancient-Aether/issues/206
https://github.com/Builderdog841/Ancient-Aether/issues/205

**Comment by bconlon1** [comment]
Ah I'd assumed it'd been fixed since I hadn't been asked about the issue in awhile.

**Comment by Yoshiman5551** [comment]
Alright, I guess I'll have to do without AA until it gets fixed.
