### ISSUE TITLE
Bug: <Stacking Hell's Gate Pig Man Tower Pig Man Generation Bug>

### ISSUE THREAD

**Issue by 1-weibai-1** [Gilded-Games/The-Aether#2438]
### What Feature Types Apply to This Bug?

Entity

### Other Type

Zombie Pig Spirit Generation Problem

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

NeoForge

### Mod Loader Version

1.21.1-21.1.73

### The Aether Version

aether-1.21.1-1.5.1-beta.3-neoforge.jar

### Is This Bug a Conflict With Another Mod?

Suspected to be related to the jewelry section and exotic accessories

### Steps to Reproduce

`ZIP REMOVED`

### What You Expect To Happen

`ZIP REMOVED`

### What Actually Happened

`ZIP REMOVED`

### Additional Details

`ZIP REMOVED`

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
This issue needs more information and proper logs.
