### ISSUE TITLE
Bug: TNT explosion doesn't lit on other TNT.

### ISSUE THREAD

**Issue by odxpoo** [Gilded-Games/The-Aether#2446]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1-beta.5

### Steps to Reproduce

It happens every single time
1. Place two TNTs next to eachother in a blast radius of each other.
2. Lit one TNT for it to explode.
3. The second TNT block will get destroyed instead of lit up.

### What You Expect To Happen

The second TNT should lit up and explode.

### What Actually Happened

The unlit TNT block is destroyed.

### Additional Details

This happens with Aether and dependencies:
https://github.com/user-attachments/assets/085197c7-65a3-4622-8278-88650d14ba74

This is with owolib + fabric:
https://github.com/user-attachments/assets/83a28ae6-d190-40d3-b049-7ea89181aab3

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
Do you have any other mods installed?

**Comment by odxpoo** [comment]
No just what's required to run aether nothing else.
