### ISSUE TITLE
Bug: World Toggle/“World Preview” button rendered the entire game unplayable

### ISSUE THREAD

**Issue by 6xolotl** [Gilded-Games/The-Aether#2448]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

World Preview

### What Type of Bug Is This?

Crash

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.5.1 beta 5

### Is This Bug a Conflict With Another Mod?

Not to my knowledge

### Client Log

https://gist.github.com/6xolotl/bd49ddbefbf223848104f7baa46689d7

### Crash Report (if applicable)

https://gist.github.com/6xolotl/59d7752baa63ed2f25f3e36112261f7d

### Steps to Reproduce

1. Click world toggle button. Game will crash.
2. Attempt to reopen game.
3. Game crashes again during world preview loading sequence. Repeat forever.

### What You Expect To Happen

To be taken to the menu screen as normal.

### What Actually Happened

It took ages to load and then crashed while loading the preview.

### Additional Details

Honestly, I don’t intend to use the feature anyway, I clicked the button out of curiosity. I just want to know how to turn off World Toggle through the game files, because it’s not in the config and I literally can’t access even the main menu. When you see this, please direct me to whatever file I need to edit/delete in order to disable the world preview so I can continue building my project in the meantime while this bug is fixed.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
You can find it in the configs folder under cumulus-client

**Comment by 6xolotl** [comment]
> You can find it in the configs folder under cumulus-client

You are a blessing, thank you!!!

**Comment by bconlon1** [comment]
I've pushed a possible solution, if you're able to help test this version: https://output.circle-artifacts.com/output/job/fff722e2-fcb5-4ba6-bf0d-ecdab54c6c3c/artifacts/0/~/project/fabric/build/libs/cumulus_menus-1.21.1-2.0.0-fabric.jar. I haven't been able to run into this issue in my own testing. You just need to put this version of Cumulus in the mods folder and I think it should override the version packaged with Aether just fine.
