### ISSUE TITLE
Bug: java.lang.NoSuchMethodError: 'boolean noobanidus.mods.lootr.config.ConfigManager.isOldTextures()'

### ISSUE THREAD

**Issue by Suyuimo** [Gilded-Games/The-Aether#2464]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Game is Crashing

### What Type of Bug Is This?

Crash

### Mod Loader

NeoForge

### Mod Loader Version

47.2.32

### The Aether Version

1.20.1-1.5.1

### Client Log

https://gist.github.com/Suyuimo/6b00ff8e676701b6d86b2ccddf8e8ef9

### Crash Report (if applicable)

https://gist.github.com/Suyuimo/6b00ff8e676701b6d86b2ccddf8e8ef9

### Steps to Reproduce

Every time if I try to join a Server

### What You Expect To Happen

Don't crash :)

### What Actually Happened

Minecraft is Crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
I don't see Aether in your logs, but this is probably an issue with Lootr needing to be updated to the latest version.
