### ISSUE TITLE
Useless Reptile incompatibility

### ISSUE THREAD

**Issue by Kiblast975** [Gilded-Games/The-Aether#2465]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Idk honestly

### What Type of Bug Is This?

Compatibility

### Mod Loader

Fabric

### Mod Loader Version

16.9

### The Aether Version

1.5.1

### Is This Bug a Conflict With Another Mod?

Useless Reptile 0.9.0

### Client Log

https://gist.github.com/Kiblast975/240c4985f51951466e9613803d625fdc

### Crash Report (if applicable)

https://gist.github.com/Kiblast975/240c4985f51951466e9613803d625fdc

### Steps to Reproduce

1. I put the mod in the folder
2. I click start in the game launcher.

### What You Expect To Happen

I expected game to work, but it didn't.

### What Actually Happened

The game crashed at the startup.

### Additional Details

Um, here is a crash link mclo.gs, bacause I'm not really sure if my link to github crash report will work:
https://mclo.gs/KSrJqDh

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
These logs do not have enough info for me to work with, I need the full crash log also displaying the mods list.
