### ISSUE TITLE
Bug: Sun Spirit isn't taking enough damage from ice balls

### ISSUE THREAD

**Issue by TheRedCreeper29** [Gilded-Games/The-Aether#2467]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Annoyance

### Mod Loader

Fabric

### Mod Loader Version

0.16.9

### The Aether Version

1.21.1-1.5.1-beta.5-fabric

### Client Log

https://gist.github.com/TheRedCreeper29/6122c5ae5724d8b8a27f6d179a9a72dc#file-gistfile1-txt

### Steps to Reproduce

Go to the gold dungeon, summon the boss, and hit it with a ice ball.

### What You Expect To Happen

More damage is taken, as seen in videos of this mod.

### What Actually Happened

It took little damage.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by bconlon1** [comment]
You have to attack the Sun Spirit with a weapon now too after he's weakened by an ice crystal.
