### ISSUE TITLE
Feature Request: 1.20.1 Fabric Port

### ISSUE THREAD

**Issue by theboee** [Gilded-Games/The-Aether#2468]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Version Port

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

1.20.1 is a very popular version to mod on java edition. A port of the existing fabric mod to this version would be nice.

### Why Should It Be in the Mod?

A port of the existing fabric mod to this version would be nice.

### Does This Feature Improve Compatibility With Another Mod?

Lots of mods are based solely on 1.20.1

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Please don't open tickets just for version requests. We're thinking about it but no promises.
