### ISSUE TITLE
Enhancement: Use mineable tags to determine what tools will work best on which blocks, instead of doing it through code.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#252]

**Comment by Drullkus** [comment]
Examples

<https://github.com/TeamTwilight/twilightforest/blob/f5f2febe6135e11dce19f2a7aa5b088f48762237/src/main/java/twilightforest/data/BlockTagGenerator.java#L469-L625>

<https://github.com/quek04/The-Undergarden/blob/0b81a58733f5e780410c3b4ebf97f61338479fb1/src/main/java/quek/undergarden/data/UGBlockTags.java#L109-L286>
