### ISSUE TITLE
Bug: Cockatrices jump into the void

### ISSUE THREAD

**Issue by reetamb** [Gilded-Games/The-Aether#26]
i wish i was joking but i just watched two of them do it

**Comment by bconlon1** [comment]
I should make a general AI task to use for all aether ground mobs that just makes sure they navigate away from the edge of islands similar to how animals avoid water.

**Comment by bconlon1** [comment]
Appears to be an issue of flying mobs overshooting their targeted block due to slowfall, so when targeting a block on the edge of islands they'll just fly off and not know what to do.

**Comment by bconlon1** [comment]
I don't remember if the new AI to avoid this was added to Cockatrices yet, but if not, it should fix this.
