### ISSUE TITLE
Bug: Dimensions have a static seed at the moment.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#270]
This is a Minecraft issue that may need to be fixed either through a Mixin or just not using the json system (which we might be doing in 1.18 anyways). Either that or maybe https://github.com/MinecraftForge/MinecraftForge/pull/7955 will finally be pulled by the time we have to worry about this.

**Comment by bconlon1** [comment]
This has finally been fixed by Forge, but I'm going to keep this issue open until we have the new generator implemented.

**Comment by bconlon1** [comment]
Turns out this is also going to be fixed by 1.19, although not sure if that'll be necessary to keep track of depending on our implementation of how we use the world seed.

**Comment by MagmaSlime123** [comment]
This would help datapacks greatly if so.
