### ISSUE TITLE
Feature: CraftTweaker compatibility.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#288]
- [x] Reimplement CraftTweaker in gradle to the 1.19 branch.
- [x] Removing and adding custom fuels.

**Comment by emifloofy** [comment]
Why CraftTweaker? Most people use KubeJS for custom content on modern versions. Is there any specific reason to still opt in for CraftTweaker?

**Comment by bconlon1** [comment]
We previously had support for CraftTweaker in older versions, so we just need to reimplement the code. You can request KubeJS support in a separate ticket if its needed.
