### ISSUE TITLE
Enhancement: Swet (polishing)

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#294]
- [x] Animation seems to be a bit rough.
- [x] Swet movement seems a bit fast when the player is captured, may need further testing to see if it needs tweaking.
- [x] See if changes/usage of MountableEntity can be avoided (may be unavoidable).
- [x] Is it a good idea to split Swet variants into separate entities for rendering?

**Comment by Jaryt** [comment]
Swet functionality should prioritize damaging the player by jumping off of cliffs. (potentially) However, if the swet sees a void, it may spit the player out at the void
