### ISSUE TITLE
Chore: Porting entity models

### ISSUE THREAD

**Issue by Jaryt** [Gilded-Games/The-Aether#296]
Remaining:
CrystalModel
FlyingCowWingModel
MoaModel (blocked)
OldAerwhaleModel
OldZephyrModel
PhygWingModel
SheepuffWoolModel

**Comment by Burning-Cactus** [comment]
I fixed the CrystalModel.

**Comment by Jaryt** [comment]
Porting WingModel's and SheepuffWool

**Comment by Jaryt** [comment]
Wing + Sheep wool is complete. Doing classic models
