### ISSUE TITLE
Bug: Aether Woods don't have a visible rotation

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#325]
![logs](https://user-images.githubusercontent.com/81527321/147848712-2c6fa601-6f48-4812-ac17-0a7ebf78c96b.png)
)

**Comment by Builderdog841** [comment]
The strange part is that the debug stick can change the rotation but they look the same

**Comment by bconlon1** [comment]
Probably an issue with the blockstate datagen, or something.
