### ISSUE TITLE
Bug: Strange Cloud Fog behavior

### ISSUE THREAD

**Issue by Drullkus** [Gilded-Games/The-Aether#333]
![image](https://user-images.githubusercontent.com/5010174/147866582-5a03ccc3-42cc-4e7a-a74e-0be4972ff9a7.png)

When quickly changing your player's moment delta, it seems like the fog will arbitrarily jump around on the top surface of the clouds.

It's probably something with the renderer. I'll get to the bottom of it

**Comment by bconlon1** [comment]
Seems to still be an issue; this only happens noticeable at very low render distances.

**Comment by bconlon1** [comment]
This just seems to be a vanilla bug, I don't know if there's much we can do about it.
