### ISSUE TITLE
refactor: Convert Holiday Trees to Tree Placer Types

### ISSUE THREAD

**Issue by Drullkus** [Gilded-Games/The-Aether#334]
**(Note: Crystal Trees have had this changed, Holiday Trees are in progress but not finished. -bconlon)**
- Foliage Placer needs to be finished.
- Present placement needs to be added.
- Snow placement needs to be added.

The disk below the Crystal Tree can also be separated into a discrete feature to be placed with the tree feature.

![image](https://user-images.githubusercontent.com/5010174/147867847-dc8d0202-ffc4-491a-97bf-487f95f66f4d.png)

![image](https://user-images.githubusercontent.com/5010174/147867901-0d410be2-1398-4aef-99b0-578661ea4d4e.png)

**Comment by bconlon1** [comment]
Partially fixed (but not closed) by #500.
