### ISSUE TITLE
Aether Dimension not generating on a superflat world

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#345]
The portal insta breaks whenever you try to light it up, using the portal frame item does not work as well
It also gives me this weird error in my logs
![image](https://user-images.githubusercontent.com/75763838/148005777-be6596f0-d9d5-4055-9d04-70a71b12b9b5.png)

**Comment by Drullkus** [comment]
Issue is related to being below Y0
