### ISSUE TITLE
Bug: Summoning fire minions crashes the game

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#346]
I used /summon aether:fire_minion and the game immediately crashed.

Log: https://paste.ee/p/aEUx2

Video: https://youtu.be/PSHhOZQ2VW8

**Comment by ZolaKluke** [comment]
Now that I think about it this might be related to https://github.com/Gilded-Games/The-Aether/issues/215

**Comment by bconlon1** [comment]
The Fire Minion has no registered renderer, that's probably causing this.
