### ISSUE TITLE
Bug: Moas and Cockatrices aren't rendered properly

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#364]
![2022-01-08_22 09 23](https://user-images.githubusercontent.com/79194869/148660064-e45dc8f3-2c87-4923-a6bc-1df2ebec9607.png)

**Comment by Mr-Aerod** [comment]
Their retrices are also a bit off.

**Comment by bconlon1** [comment]
Duplicate of #251.
