### ISSUE TITLE
Bug: Game crashes when causing any form of block update on a server

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#369]
### What Feature Types Apply to This Bug?

Server

### What Type of Bug Is This?

Crash

### Forge Version

39.0.10

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/ZolaKluke/8b4da85d73d6c32cfeed41ae0dcdb336

### Crash Report (if applicable)

https://gist.github.com/ZolaKluke/112bdfc3b720fa576cc87e2d2e5d596f

### Steps to Reproduce

1. Log into any Minecraft server
2. Punch a leaf block

### What You Expect To Happen

The game to not crash

### What Actually Happened

The game crashed

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ZolaKluke** [comment]
Forgot to add a video if needed
https://youtu.be/38uG2sYYC5s

**Comment by ZolaKluke** [comment]
Okay so right clicking a door also crashes, might be related to block updates actually

**Comment by bconlon1** [comment]
Seems unreproduceable with the latest versions.

**Comment by ZolaKluke** [comment]
Still reproduceable with the latest version for me
(this one)
![image](https://user-images.githubusercontent.com/6497775/149750758-bafd063d-fa17-492a-8ed8-6075e4a567ee.png)

**Comment by ZolaKluke** [comment]
It's happening for me on a paperspigot server if that is important and also these plugins if it helps because when it happens there is no error in the server console either.
![image](https://user-images.githubusercontent.com/6497775/149751488-de969887-f659-4bf2-8ca0-09829f55d1f9.png)

**Comment by Burning-Cactus** [comment]
This happens you have the mod installed on the client when it's not on the server. The server doesn't have all of the tags that the mod uses. I'm not sure how you managed to connect to a server with the mod installed, since normally you would be booted from the server.

![image](https://user-images.githubusercontent.com/23108473/157760489-5e0dbcb8-e7d3-4b24-b39c-1587d4785d9a.png)

**Comment by bconlon1** [comment]
@ZolaKluke can you verify whether you had the mod on the server with any server-side logs?

**Comment by ZolaKluke** [comment]
> @ZolaKluke can you verify whether you had the mod on the server with any server-side logs?

Mod is definitely not on the server as it ran paperspigot at the time, it now runs purpur and I'll see if I can replicate it again (3rd time now lol) and send my client logs

**Comment by ZolaKluke** [comment]
Yep still able to replicate this with the latest commit of the mod at this time https://github.com/Gilded-Games/The-Aether/commit/4dff7775ca2043f5ab1614e72b49505026ce53c9

Edit: Also never got a screen talking about tags like @Burning-Cactus it just let me straight into the server

Client logs:
Crash: [crash-2022-03-11_18.48.31-client.txt](https://github.com/Gilded-Games/The-Aether/files/8230073/crash-2022-03-11_18.48.31-client.txt)
Log: [latest.log](https://github.com/Gilded-Games/The-Aether/files/8230075/latest.log)
