### ISSUE TITLE
Enhancement: Replace vanilla chests with skyroot chests

### ISSUE THREAD

**Issue by Jaryt** [Gilded-Games/The-Aether#373]
### What Feature Types Apply to This Request?

Block

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Upgrade vanilla wooden chests to skyroot chest

### Why Should It Be in the Mod?

The vanilla chest texture looks very out of place in the Aether color pallet

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Not going to be adding Skyroot Chests since they'd be inconsistent with both vanilla's handling of chests and also our handling of utility block crafting.
