### ISSUE TITLE
Feature: Art Refresh

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#386]
- [x] Items
- [x] Blocks
- [x] Entities
- [x] GUI Elements
- [x] Armor/Accessories
- [ ] Effects
- [x] Vignettes?
- [x] Programmer Art versions of any new content that only has the new art (- bconlon).
- [x] Final Polishing

**Comment by bconlon1** [comment]
Related Issues:
- #54 
- #236

**Comment by bconlon1** [comment]
Suggestion: Animation for the portal item, if we go with making the portal actually have the animated water texture?

**Comment by OzPayn** [comment]
> Suggestion: Animation for the portal item, if we go with making the portal actually have the animated water texture?

Yeah if we add animation to the portal block itself then I think it'd make sense to have the item be animated too.
