### ISSUE TITLE
Enhancement: Aether Grass colorable through Biome Colors

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#388]
- Potential implementations include either separating the non tintable and tintable aether grass into two separate blocks, or making the current aether grass only tint within the aether dimension and otherwise use the texture or a default tint color instead.

**Comment by Drullkus** [comment]
[Reference impl of custom grass pattern behavior from TF](https://github.com/TeamTwilight/twilightforest/blob/1.18.x/src/main/java/twilightforest/world/components/BiomeGrassColors.java) may be needed in the future, but for now we can just do [static biome colors](https://github.com/Gilded-Games/The-Aether/blob/342a961a84d54b721d20014b48a500b298e7d476/src/main/java/com/gildedgames/aether/core/data/provider/AetherBiomeProvider.java#L24)

**Comment by bconlon1** [comment]
Likely not going to implement this.
