### ISSUE TITLE
Feature Request: Stripped Golden Oak Log

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#389]
### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Add Stripped Golden Oak Log block.

### Why Should It Be in the Mod?

Vanilla Minecraft compatibility.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This was previously in before stripping golden oak was given special behavior, i.e the block existed but got removed.

**Comment by Jaryt** [comment]
Also, please use the feature type drop down!
