### ISSUE TITLE
Textures for 1.14+

### ISSUE THREAD

**Issue by MysteryKey** [Gilded-Games/The-Aether#39]
As you probably already know, in update 1.14 of Minecraft, the textures of the game had a major update. Whereas the textures used by the Aether mod are still based on the textures prior to 1.14. Because this mod is for 1.16 (which obviously uses the newer textures), I thought it would be a good idea to update the textures to blend in a bit more. Here's an example:

Snowy aether grass block:
![aether_grass_block_snow_64x64](https://user-images.githubusercontent.com/74663307/109422757-dc3dd700-79d4-11eb-94c3-7cceff35886e.png)

New snowy regular grass block:
![grass_block_snow_64x64](https://user-images.githubusercontent.com/74663307/109422762-dfd15e00-79d4-11eb-8617-8b51a12d3012.png)

New snowy aether grass block:
![aether_grass_snow_64x64](https://user-images.githubusercontent.com/74663307/109422765-e364e500-79d4-11eb-8d12-8f65271b382a.png)

**Comment by quek04** [comment]
this is going to be worked on once the initial porting is complete, I think... so

**Comment by MysteryKey** [comment]
> 
> 
> this is going to be worked on once the initial porting is complete, I think... so

Alright, thanks for letting me know. I wasn't aware beforehand, sorry.
