### ISSUE TITLE
Bug: Can't place skyroot sapling on Aether grass/dirt blocks

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#401]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.36

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Get a skyroot sapling
2. Try placing it on Aether dirt/grass block

### What You Expect To Happen

Being able to place the sapling

### What Actually Happened

Nothing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
This seems to apply to flowers as well, might be a tag issue due to the switch to vanilla's dirt tag.

**Comment by bconlon1** [comment]
Fixed in the latest commit.
