### ISSUE TITLE
Bug: Items disappear when put in a Book of Lore on server

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#402]
### Forge Version

39.0.36

### The Aether 1 Version

1.0.0

### Steps to Reproduce

Start a server using the latest build of the aether for 1.18 available to this date

Spawn a book of lore

Put the book of lore in the Slot where it tells you the functionality of the item you placed on it

Enjoy

### What You Expect To Happen

The book not disintegrate and give me the "loreception" advancement

### What Actually Happened

The book disappears 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by KotuMF** [comment]
I can confirm that the Book of Lore is still bugged, but instead of deleting the Book of Lore, it deletes the items placed in it.
