### ISSUE TITLE
Bug: Breaking grass with fist drops grass item

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#403]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.36

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/ZolaKluke/b74fdf94f00307925fd1392758a6c407

### Steps to Reproduce

1. Go into survival
2. Break a piece of grass

### What You Expect To Happen

To get seeds or nothing

### What Actually Happened

Got a grass item instead

### Additional Details

https://youtu.be/M7CDzi6IG5E

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Hopefully will be fixed once we move to a global loot modifier for grass instead of the json override I made for the grass loot table.

Relevant Issue: #269.
