### ISSUE TITLE
Chore: Check if ambrosium torch output is the correct amount.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#405]

**Comment by ZolaKluke** [comment]
I looked into this and the 2 original versions I have make 2 torches in the recipe

Beta 1.7.3, mod version 1.02
![image](https://user-images.githubusercontent.com/6497775/150452715-1582a915-addc-469c-b26a-076d9080ea09.png)
1.2.5, mod version 1.9 pre release 3
![image](https://user-images.githubusercontent.com/6497775/150452904-bb037dcd-d779-4b29-83d4-2fc6275fa58a.png)

**Comment by Builderdog841** [comment]
It was like that in older legacy versions but changed because it was to annoying as far as I know.

**Comment by ZolaKluke** [comment]
Makes sense and plus I think the majority of people would prefer the 4 instead of 2 recipe since that fits better with vanilla

**Comment by bconlon1** [comment]
Sticking with 4 Ambrosium Torches for vanilla consistency.
