### ISSUE TITLE
Bug: Skyroot axes don't double block drops

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#409]
### What Feature Types Apply to This Bug?

Block, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/kodadacod/a0ebcc81293d2ddbc5d7e517a0b7e84f

### Steps to Reproduce

1. Obtain a Skyroot Axe
2. Find a Skyroot Log (with the doubledrops tag)
3. Break the log with the Skyroot Axe

### What You Expect To Happen

The Skyroot Log would drop 2 Logs

### What Actually Happened

The Skyroot Log dropped one Log

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kodadacod** [comment]
This extends to Shovels and Pickaxes as well.

**Comment by bconlon1** [comment]
Appears to be due to Aether blocks not having the double drops state when generated.

**Comment by Drullkus** [comment]
> Appears to be due to Aether blocks not having the double drops state when generated.

That’ll have to be me to fix then

**Comment by bconlon1** [comment]
Seems that the loot function for double drops is also commented out so that is also an issue here, although that loot function may be removed at some point.
