### ISSUE TITLE
Bug: tall grass cuts off skyroot leaves

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#41]
tall grass cuts off skyroot leaves
![2021-02-28_13 17 16](https://user-images.githubusercontent.com/75763838/109434009-089f2680-79c8-11eb-9dfd-890b25f05e59.png)

**Comment by bconlon1** [comment]
Might be a generation order issue.

**Comment by bconlon1** [comment]
status/blocked until we reimplement grass. See: #499.

**Comment by bconlon1** [comment]
No longer reproduceable.
