### ISSUE TITLE
Bug: Blocks mined with a Holystone Pickaxe drop ambrosium whether or not they are placed by a player or not

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#410]
### What Feature Types Apply to This Bug?

Block, Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/kodadacod/a7a7a45f2020d5f679d204271995fe06

### Steps to Reproduce

1. Place down Polystone
2. Obtain a Holystone Pickaxe
3. Mine the Holystone with a Holystone Pickaxe

### What You Expect To Happen

The Holystone doesn't drop Ambrosium

### What Actually Happened

The Holystone dropped Ambrosium.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ZolaKluke** [comment]
Can confirm this also happens with the holystone axe and more than likely affects the holystone shovel as well

**Comment by MagmaSlime123** [comment]
And maybe other tools

**Comment by kodadacod** [comment]
Seems as though this works as intended.
