### ISSUE TITLE
Bug: Killing a hostile aether mob doesn't grant the Monster Hunter advancement

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#412]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Kill any hostile Aether mob

### What You Expect To Happen

Be granted the Monster Hunter advancement

### What Actually Happened

I was not granted the Monster Hunter advancement

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might have to grant this manually unless there's some way to add to the entities the advancement is triggered by.

**Comment by bconlon1** [comment]
Doesn't seem feasible without causing compatibility issues for mods that might do the same thing. This kind of thing seems like something Forge would have to add support for.
