### ISSUE TITLE
Bug: Enchanter gui is broken, does not function

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#417]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Place down an enchanter
2. Interact with the enchanter

### What You Expect To Happen

A normal gui for the enchanter would appear, and it would allow me to enchant items

### What Actually Happened

A glitched enchanter gui appears, and I cannot enchant any items

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Extends to the Freezer as well probably.
