### ISSUE TITLE
Feature: Skyroot Boats

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#420]
### What Feature Types Apply to This Request?

Entity, Item

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A Skyroot boat that is crafted and looks like skyroot wood

### Why Should It Be in the Mod?

For vanilla parity with other wood types

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Mr-Aerod** [comment]
You'll also need to do the Skyroot Chest boats once the 1.19 port starts, as they were added in 1.19.
