### ISSUE TITLE
Bug: Hellfire Stone Slabs have incorrect hardness value

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#421]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Annoyance

### Forge Version

39.0.43

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Mine a Hellfire stone block
2. Mine a Hellfire stone slab
3. Observe that the Hellfire stone slab takes longer to mine than the Hellfire stone block

### What You Expect To Happen

The Hellfire stone slab and Hellfire stone block take the same amount of time to mine

### What Actually Happened

The Hellfire stone slab takes longer than the Hellfire stone block to mine

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Slab values are correct, but the properties of the dungeon bricks themselves need adjusting.
