### ISSUE TITLE
Bug: Overlay opacity glitch

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#422]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/ZolaKluke/903504ab715c7664e6ce26f1aab1ca7e

### Steps to Reproduce

1. Equip a repulsion shield
2. Get shot at by cockatrices a lot
3. Repulsion shield overlay will glitch after a lot of shots

### What You Expect To Happen

The overlay to react normally no matter how many shots

### What Actually Happened

Overlay glitched and couldn't see anything until relogging onto the ANTS server

### Additional Details

![image](https://user-images.githubusercontent.com/6497775/149859944-00adba31-c3f0-40ac-848e-48d2df977616.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Can confirm this can happen but it seems incredibly hard to reproduce.

**Comment by bconlon1** [comment]
I made some fixes to overlays in #501's branch, I'm going to hope that fixes this issue, but if it arises again then this issue can be reopened.

**Comment by bconlon1** [comment]
This issue (or at least a similar) one has been encountered with supposedly reproduceable steps: Holding tab for the player list during or after having an overlay inflicted on the player. Images of the issue look slightly different though, and the original issue has been able to occur in singleplayer, but perhaps finding the cause of that one will also have a more trusted fix for the other overlay issue this report was made for.
