### ISSUE TITLE
Bug: When disconnecting from a server while in the Aether it shows the "Descending from the Aether" text

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#424]
### What Feature Types Apply to This Bug?

Server

### What Type of Bug Is This?

Annoyance

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Join a server and enter the Aether
2. Log off from the server while in the Aether

### What You Expect To Happen

Not to show descending from the Aether text

### What Actually Happened

Shows the text

### Additional Details

![image](https://user-images.githubusercontent.com/6497775/149873993-8990583a-7762-479a-8b9e-d15c631cea41.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might be abme to have a second boolean to control whether this text renders or not; it can be only true when the dimension travel event is run through and gets turned false on world load event (assuming the world load event is called by the client after entering a dimension)
