### ISSUE TITLE
Bug: Quicksoil replaces Aether Dirt and Holystone when generating

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#425]
### What Feature Types Apply to This Bug?

Block, World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.43

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Find a patch of Quicksoil
2. Start mining it
3. Observe how it extends into the island instead of stopping when it hits Aether Dirt/Holystone

### What You Expect To Happen

The patch of Quicksoil would stop when it reaches the island.

### What Actually Happened

The patch of Quicksoil overrode the blocks and generated into the island.

### Additional Details

This most likely replaces Ores as well.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
DiskFeature doesn't seem to check if a block is air which is probably the cause of this.

**Comment by bconlon1** [comment]
There should probably be some other adjustments made to the quicksoil shelves first like making sure they don't spawn in weird positions in the middle terrain where they'd look weird if all the parts that intersect with terrain got cut off.
