### ISSUE TITLE
Chore: Use Item.interactLivingEntity(ItemStack, Player, LivingEntity, InteractionHand) instead of EntityInteractSpecific event

### ISSUE THREAD

**Issue by Burning-Cactus** [Gilded-Games/The-Aether#441]

**Comment by bconlon1** [comment]
Specifically: https://github.com/Gilded-Games/The-Aether/blob/d6aeaee5fb9065b4e020b0fcb896d8bd96de7250/src/main/java/com/gildedgames/aether/common/event/listeners/EntityListener.java#L34

**Comment by bconlon1** [comment]
Minecraft's bucket item util code acts strangely in interactLivingEntity, I am going to keep the interaction code as an event.
