### ISSUE TITLE
Skyroot Boats

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#449]
### What Feature Types Apply to This Request?

Entity, Item

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Please add Skyroot boats, they’d bee cool to swim with.

### Why Should It Be in the Mod?

Why not, it’d be a cool addition.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by kodadacod** [comment]
This is a duplicate of #420

**Comment by Mr-Aerod** [comment]
I see, closing it…
