### ISSUE TITLE
Bug: You can't strip skyroot logs

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#453]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.9

### The Aether 1 Version

1.18

### Steps to Reproduce

right click a skyroot log with an axe

### What You Expect To Happen

To get stripped skyroot logs

### What Actually Happened

it did nothing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Related to #413.
