### ISSUE TITLE
Feature Request: Beta fog shader

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#456]
Fog renderer that recreates how the Aether's fog looked in the original mod. Not sure how doable this is.
- Fog at a distance.
- Fog during the rain.

I think the main thing that made the beta fog was it had more distance to it, it faded out more while modern fog is more abrupt.

We might be able to also use the Forge fog render event to change the distance of fog without having to construct anything from the ground up.

**Comment by bconlon1** [comment]
Fog render event broke so until it's fixed by Forge this is reopened (https://github.com/MinecraftForge/MinecraftForge/issues/8762).

**Comment by Jonathing** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/8825
