### ISSUE TITLE
Chore: Implement documentation comments for maintenance purposes.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#463]
Purposes
- Explanations of what code does.
- ~~Explanations of what mixins do and where they are placed.~~
- Explanations of math and what it's intended to do.
- Explanations of where code is vanilla copy.

Details
- Code explanation.
- Class explanations can be put in place of methods for small classes where necessary, like packets.

**Comment by bconlon1** [comment]
~~Will likely dedicate time to this after the package organization/cleanup.~~

**Comment by raptor494** [comment]
~~putting this here before i forget: code in AerogelStairsBlock#hidesNeighborFace is based off of code in Block#shouldRenderFace~~
