### ISSUE TITLE
Bug: Tips cycle extremely fast when validating data packs

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#474]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

UI

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

39.0.88

### The Aether 1 Version

1.18.1-v1.0.0

### Steps to Reproduce

Apply a data pack to a world which is being created, such as the data pack from #473

### What You Expect To Happen

Hints would either display and change at the normal rate, or not display at all.

### What Actually Happened

The hints instead change rapidly.

### Additional Details

Discovered while testing #473

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might need to have a static string value for the current pro tip to display and have a timer tick down for a simple boolean for when to switch it to a new tip. Maybe it should only switch to a new one when the world actually loads, so that a new one will be viewed next time that happens.

**Comment by bconlon1** [comment]
The tips can be added back to the chunk loading preview screen as well if they're made to only reset after the player has loaded the world.

**Comment by bconlon1** [comment]
Considering how tips are handled, it may be easier to store and switch an index of the line the text belongs to, instead of trying to store the text itself.
