### ISSUE TITLE
Feature Request: ultracold dimension_type option, or possibly a dimension tag?

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#475]
### What Feature Types Apply to This Request?

World-Gen

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The vanilla dimension_type specification allows for the "ultrawarm" setting to be specified. If set to true, this prevents water from being placed in the dimension, causes wet sponges to be placed as dry sponges, increases lava's flow rate and distance, and changes stalactite dripping behaviour.

The Aether dimension has a similar attribute, in that it forbids lava from being placed in much the same way as the Nether forbids water from being placed. In this case, placed lava immediately becomes aerogel.

The problem with this implementation is that due to it being hardcoded, any custom data pack dimensions cannot make use of this feature, and it remains Aether-exclusive.

To make this available for other dimensions to use in data packs, either of the following could apply:
- dimension_type files would also accept an "ultracold" boolean. This would be false by default (and could also be completely left out of the file, which would set it to false for compatibility's sake). If set to on, lava would immediately become aerogel.
- If this is infeasible, it may be possible to achieve this via tags instead - a tag could be created for dimensions such that any dimensions in it will have all placed lava freeze into aerogel.

### Why Should It Be in the Mod?

Compatibility's sake and functional consistency. For example, a modpack which contains the Aether may also include a new custom dimension with an associated data pack which could make use of this freezing functionality.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Might also tie banning items to `#ultracold` as suggested in #57.

**Comment by bconlon1** [comment]
It turns out this issue is actually unfixable at the moment, see: #531. This issue will remain closed though and will be linked from that issue for future reference.
