### ISSUE TITLE
Feature Request: Rename berry bushes to be more specific

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#478]
### What Feature Types Apply to This Request?

Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Currently, the berry item is titled "Blue Berry", but the bush it comes from is just the generic "Berry Bush". It'd be better to have this be named something along the lines of "Blue Berry Bush".
![2022-03-05_01 38 43](https://user-images.githubusercontent.com/52297970/156863934-d741ecc4-6e56-4ef5-a9db-0a0a39eb1003.png)
![2022-03-05_01 38 44](https://user-images.githubusercontent.com/52297970/156863935-113e5c34-3ca1-4500-9277-869fcb957727.png)

### Why Should It Be in the Mod?

Vanilla's berries are named "Sweet Berries", and their associated bush is titled "Sweet Berry Bush" rather than just a generic "Berry Bush", so the Aether should probably follow suit.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We are keeping the names of stuff the same as they were in the original mod.
