### ISSUE TITLE
Hammer of Notch projectiles can sometimes get stuck in the void when they are in unloaded chunks

### ISSUE THREAD

**Issue by ghost** [Gilded-Games/The-Aether#49]
![image](https://user-images.githubusercontent.com/51373236/109435069-5ccdf900-7a10-11eb-85bc-b298a0b7f4dc.png)

**Comment by bconlon1** [comment]
this is probably fixed considering the overworld teleport exists now, and also hammer projectiles have a limited life time so they won't stay there forever.
