### ISSUE TITLE
General Whirlwind Jank

### ISSUE THREAD

**Issue by Coach-mdl** [Gilded-Games/The-Aether#491]
Whirlwinds seems to only spawn at above y150 on top of gold dungeons. They also do not seem to drop random items. Have yet to see an Evil whirlwind but I don't know if they've been implemented properly yet.

**Comment by bconlon1** [comment]
Resolved; spawning is not yet balanced properly and the item dropping happens in survival when targeting the player (because whirlwinds can't target the player in creative).
