### ISSUE TITLE
Bug: Planting large spruce trees in the Aether generates normal podzol below them.

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#496]
### What Feature Types Apply to This Bug?

Block, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

 39.0.9

### The Aether 1 Version

1.0.0

### Steps to Reproduce

This happens when you place four spruce saplings next to each other and bone meal them: four podzol blocks generate below the tree. This could either be fixed by adding a special Aether podzol variant, or simply disabling the podzol to generate.

### What You Expect To Happen

Mentioned above.

### What Actually Happened

![Snímek obrazovky 2022-03-17 113727](https://user-images.githubusercontent.com/79194869/158791621-d06d9d36-3a4f-443a-86fc-86b04ffae915.jpg)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Weird that it only spawns right beneath the tree, wonder if the podzol placement is after the tree spawns and converts the area under it to Aether Dirt, which might be in a tag that the tree checks to replace with podzol.

**Comment by bconlon1** [comment]
Can't seem to reproduce this specific behavior but can confirm podzol replaces Aether Dirt and Aether Grass.
