### ISSUE TITLE
Bug: projectiles fly up after bouncing on blue aerclouds

### ISSUE THREAD

**Issue by Npcfanatic21** [Gilded-Games/The-Aether#515]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

40.0.31

### The Aether 1 Version

1.18.2

### Steps to Reproduce

1. bounce on aercloud
2. use lightning knife/hammer of notch to throw projectile

### What You Expect To Happen

projectiles not fly up?

### What Actually Happened

projectiles fly up

### Additional Details

short video showing what happens
https://vimeo.com/692126388

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Determined to be in line with vanilla physics; this is just how projectiles work.
