### ISSUE TITLE
Bug: Skyroot trees generating on Crystal tree islands

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#519]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

 40.0.19

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Generate a new world
2. Load it and try to find one.

### What You Expect To Happen

I don't expect Skyroot trees being able to generate on Crystal tree islands.

### What Actually Happened

Guess what

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
As suggested by Drullkus, the bounds/limits or whatever of the Skyroot Trees that determine the room they need to generate probably need to be adjusted, assuming the Skyroot Trees are generating after the Crystal Tree is placed down and not before.

**Comment by bconlon1** [comment]
Might just need to push the feature to `TOP_LAYER_MODIFICATION` and see if theres a way to force the tree to generate through the PlacedFeature so if something obstructs the island's generation like an aercloud it should not generate at all, instead of just blocking the tree's generation on the island.
