### ISSUE TITLE
Bug: Quicksoil smelts into vanilla glass rather than quicksoil glass

### ISSUE THREAD

**Issue by Ultrasquid9** [Gilded-Games/The-Aether#534]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Recipe

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

40.0.36

### The Aether 1 Version

1.0.0

### Is This Bug a Conflict With Another Mod?

probably related to recipe tags

### Steps to Reproduce

put quicksoil in furnace. take glass out of furnace. 

### What You Expect To Happen

put quicksoil in furnace. take quicksoil glass out of furnace. 

### What Actually Happened

vanilla glass. 

### Additional Details

may be related to tags. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Likely an issue from us tagging quicksoil as sand, probably just need to remove it being tagged as sand.
