### ISSUE TITLE
Enhancement: Unique ore patterns

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#54]
Might be resolved like #39 was. But currently the ore textures are all the same, so it might be advisable to change the patterns to all be different for non-programmer art (maybe get this in early for 1.16).

**Comment by ghost** [comment]
Yeah, this would count as a duplicate of #39 but I'm currently working a texture pack which is meant to replicate Jappa's art style for the Aether. I can't promise it'll be out anytime soon but you can hopefully expect it sometime in the future

**Comment by bconlon1** [comment]
Has been fulfilled in the retextures.
