### ISSUE TITLE
Bug: Aether ores and altar recipes don't give exp.

### ISSUE THREAD

**Issue by Static45** [Gilded-Games/The-Aether#545]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

40.0.32

### The Aether 1 Version

1.0.0 (Aether 1.18.2 latest commit as of 8/April)

### Steps to Reproduce

1: Ore exp issue:
 Use any kind of pickaxe to mine ambrosium and zanite.
2: Altar exp issue:
 Try to enchant something at an altar.

### What You Expect To Happen

1: Zanite and ambrosium should drop exp orbs as well.
2: Altars together with the enchanted items it should also drops exp orbs.

### What Actually Happened

For both situations no exp is given.

### Additional Details

Skyroot pick doesn't affect the exp issue on ambrosium.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Our ore xp code is commented out for some reason, and altar/freezer xp yields were something i didnt think of but would probably be good to implement.
