### ISSUE TITLE
Feature Request: Custom Recipe book icons for Altar (and Freezer)

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#555]
### What Feature Types Apply to This Request?

Art, Block, Other (Please Describe)

### Other Type

GUI

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Vanilla Recipe book feature only exists for Crafting table and Furnace. When you enter the Recipe book UI while focusing on them, you see there is a button in the UI, which toggles the option of showing only craftable / all items in the recipe book.
![recipe_book](https://user-images.githubusercontent.com/79194869/163422928-2e9f1614-e592-4708-900e-3d4ee406f358.png)
This button has two variants: one with the crafting table, which you can find in the crafting table UI and one with the furnace - which you can find either in normal furnace, blast furnace, or smoker.
Now, Aether mod has recently added Recipe book support for the Altar, and the Freezer which both use the Furnace icon button.
I'm wondering if you could make a custom button with custom Aether block displayed on it for atleast the Altar (if we consider the Freezer as another furnace block.), or both of them.
In case I didn't describe it clearly (which I hope I did), I made an example of how could it look like for the Altar:
![recipe_book-export](https://user-images.githubusercontent.com/79194869/163423733-cb6fdca3-cabe-439e-baca-5a15b1f5f2e1.png)

### Why Should It Be in the Mod?

Vanilla parity.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Seems easily doable if we override initFilterButtonTextures() in our RecipeBookComponent classes.

**Comment by bconlon1** [comment]
Probably actually not going to be doing this considering the closeness the Altar and Freezer have to the Furnace; the furnace icon still applies best with the recipe book for these blocks.
