### ISSUE TITLE
Enhancement: Allow data pack dimension_type files to select item tags for blocking item usage

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#57]
Currently the Aether has #aether:banned_in_aether to stop torches and fire from being placed in the Aether, but this appears to be hardcoded. It would be preferable if any dimension could specify a set of disallowed items through the dimension_type json file, by selecting any item tag much like vanilla allows the selection of block tags for infiniburn.

If left unspecified, no items will be disallowed for any dimensions using that dimension_type.

**Comment by bconlon1** [comment]
We're not adding capabilities for other dimensions, this is a mod for a single dimension.

**Comment by bconlon1** [comment]
This is now possibly able to be easily done using the new tag capabilities of 1.18.2.

**Comment by bconlon1** [comment]
May include dimension tags as an option/recipe field when item banning is converted to the recipe format.

**Comment by bconlon1** [comment]
It turns out this issue is actually unfixable at the moment, see: #531. This issue will remain closed though and will be linked from that issue for future reference.
