### ISSUE TITLE
Bug: Overworld acts as if it is Eternal Daylight every time when loading it.

### ISSUE THREAD

**Issue by ghost** [Gilded-Games/The-Aether#583]
### What Feature Types Apply to This Bug?

Performance, Other (Please Describe)

### Other Type

Behavior Glitch

### What Type of Bug Is This?

Annoyance

### Forge Version

40.1.0

### The Aether 1 Version

1.0.0 (Bleeding Edge)

### Steps to Reproduce

Loading any world on Singleplayer immediately causes this issue.
In a multiplayer server, the day and night cycle works, the time command too, but enemy mobs don't spawn, as the Overworld still acts like it has Eternal Sunlight.

### What You Expect To Happen

The Overworld is supposed to have a normal day and night cycle with the ability for enemy mobs to spawn and the time command to work without issue.
The Aether is supposed to have Eternal Daylight until the Sun Spirit is defeated, but I am aware that the dungeon is not implemented yet.

### What Actually Happened

The Overworld has eternal sunlight and no time commands work.

In Multiplayer, the day and night cycle works normally, as do the time commands when used, but no mobs spawn whatsoever, as the Overworld still thinks it's eternal daytime.

-> https://media.discordapp.net/attachments/569973116621684786/969665008550166558/unknown.png?width=1609&height=905

### Additional Details

Jumping into the Aether and going back fixes the issue in Singleplayer, as the day and night cycle fixes itself then for some reason.
This happens every time a world is loaded, not just one time, so the fix mentioned above is only temporary every time.

In a multiplayer server, jumping into the Aether and back into the Overworld fixes the mob spawns temporarily.
But as soon as the server shuts down and is restarted, the issue appears again, so, like in Singleplayer, the fix is temporary.

https://media.discordapp.net/attachments/569973116621684786/969665225609609267/unknown.png?width=1609&height=905

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might have to look into making sure Eternal Day is only registered to the Aether which may require trying to tweak tag syncing again. Don't know why it's still occurring in other dimensions when the capability should never be running anything outside the Aether.

**Comment by bconlon1** [comment]
Wonder if its possible to simply make the capability not return itself when pulled from a world if the world isnt under the eternal day tag through conditional checks. That way the capability is null outside of the aether dimension even if its registered to all dimensions.
