### ISSUE TITLE
Bug: Only two of the Aether Discs show up when you search for "music disc" in the inventory.

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#584]
### What Feature Types Apply to This Bug?

Item, System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

 40.0.44

### The Aether 1 Version

1.0.0

### Steps to Reproduce

Search for "music disc" in the Search items tab.

### What You Expect To Happen

Legacy and Welcoming skies discs show up.

### What Actually Happened

Legacy and Welcoming skies discs didn't show up.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
What "Search items" tab are you talking about?

**Comment by Mr-Aerod** [comment]
This one:
![Snímek obrazovky 2022-05-01 171757](https://user-images.githubusercontent.com/79194869/166152511-e77ce04a-5f23-4956-9ed6-88ae22830177.jpg)

**Comment by bconlon1** [comment]
This is because these discs do not have Music Disc in the name, although I'm not sure if we should perhaps change the naming because of this for consistency.
