### ISSUE TITLE
Bug: Aether is generating as a void with bedrock and clouds above bedrock

### ISSUE THREAD

**Issue by Kasia1403** [Gilded-Games/The-Aether#595]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

14.23.5.2860

### The Aether 1 Version

1.5.3.2 ( Aether Legacy )

### Is This Bug a Conflict With Another Mod?

I don't know, but probably yes

### Steps to Reproduce

1.Enter the portal
2.Wait until world loads
3.Bug

### What You Expect To Happen

Aether Legacy loads without bugs

### What Actually Happened

Aether world generates as a void with bedrock at the bottom and clouds above bedrock

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
This is the tracker for the port, not 1.12. Also if you're going to report a bug you need logs. Although right now the 1.12 tracker is archived from letting reports in because we're likely not going back to fixing it after the port exists. Determine what mod conflict is occurring and you can likely fix this on your own.

**Comment by Kasia1403** [comment]
Do You know maybe if it could be OTG ?

**Comment by Kasia1403** [comment]
Eh, it seems that it is not OTG. But if it is JEID I will be very unhappy, because I need JEID, because without JEID in my modpack it says "id range exceeded".

**Comment by Kasia1403** [comment]
I give You screenshot of my bug. Maybe it will help.

![2022-05-14_16 08 49](https://user-images.githubusercontent.com/54236098/168437066-9b20ce80-8d7a-48f7-af45-90977f74d7c0.png)

**Comment by bconlon1** [comment]
Our Discord may be able to help, it looks like you're using a lot of mods so I wouldn't have any idea of the issue.

**Comment by Kasia1403** [comment]
It is also not JEID.

**Comment by Kasia1403** [comment]
Wait, it's generating ! This bedrock may be from Better Bedrock, Flat Bedrock or Quark mod.
