### ISSUE TITLE
Bug:  Can't open Accsesory Screen on Servers

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#602]
### What Feature Types Apply to This Bug?

Server

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

40.0.36

### The Aether 1 Version

1.18.2-1.0.0

### Steps to Reproduce

Go on a server
Try to open the acsessory screen

### What You Expect To Happen

To open the acsessory screen

### What Actually Happened

nothing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Cannot reproduce so this was also probably happening from the version mismatch on ANTS.
