### ISSUE TITLE
Bug: Not compatible with Kiwi

### ISSUE THREAD

**Issue by Dr-WeiAL** [Gilded-Games/The-Aether#610]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

game crashes

### What Type of Bug Is This?

Crash

### Forge Version

40.1.20

### The Aether 1 Version

1.18.2 1.0.0

### Is This Bug a Conflict With Another Mod?

Kiwi-1.18.2-forge-6.1.0

### Client Log

[latest.log](https://github.com/Gilded-Games/The-Aether/files/8701803/latest.log)

### Crash Report (if applicable)

[crash-2022-05-16_20.42.40-client.txt](https://github.com/Gilded-Games/The-Aether/files/8700228/crash-2022-05-16_20.42.40-client.txt)

### Steps to Reproduce

Put them together to start the game

### What You Expect To Happen

fix

### What Actually Happened

crashes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
I can't see Aether or any other mods in this log for the matter, and the Forge version doesn't match the one you gave in this issue report. Are you sure you provided the correct log?

**Comment by Dr-WeiAL** [comment]
> I can't see Aether or any other mods in this log for the matter, and the Forge version doesn't match the one you gave in this issue report. Are you sure you provided the correct log?

sorry i thought crash would be enough, already added

**Comment by bconlon1** [comment]
It has been suggested our Mixin Config may be causing issues, we'll have to look into it further.

**Comment by Dr-WeiAL** [comment]
Okay so have you identified the problem?

**Comment by bconlon1** [comment]
No. Issue could also be that we need to update or mixins to 0.8.5, who knows.

**Comment by Dr-WeiAL** [comment]
Ok, I got it, I will try it again if there is a new build in the future

**Comment by Dr-WeiAL** [comment]
I tried build1512 and it is already compatible with Kiwi

**Comment by bconlon1** [comment]
Yes that is a build that has the fix implemented, please be aware though that branch is not finished and I am still resolving other bugs with it; you should usually stick to builds from the main 1.18 branch for _relative_ stability.
