### ISSUE TITLE
Bug: Infinite flight with valkyrie armor

### ISSUE THREAD

**Issue by Leopotion3** [Gilded-Games/The-Aether#640]
### What Feature Types Apply to This Bug?

Item, Other (Please Describe)

### Other Type

Armor

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

14.23.5.2860

### The Aether 1 Version

1.5.3.2

### Steps to Reproduce

Always
1. Equip full Valkyrie armor and use the flight mechanic
2. Wait until the flight duration ends and you start falling
3. Log out of the server or world
4. Log back in, spamming the jump key and you will reset the flight timer

Here is a video i recorded of the bug in action on the OATS server
https://user-images.githubusercontent.com/93087290/170465836-c7f61e7f-b6bc-445b-b345-8dcfd0e0137c.mp4

### What You Expect To Happen

To not reset the flight timer

### What Actually Happened

Flight timer got reset

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
We're not accepting 1.12 bugs on this tracker.
