### ISSUE TITLE
Bug: Cockatrices reuse the moa sound event

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#65]
They should probably get their own so it's less confusing when subtitle strings are added:
![2021-03-05_22 24 08](https://user-images.githubusercontent.com/52297970/110180463-b748ca00-7e01-11eb-95ec-dc57272e32de.png)

**Comment by bconlon1** [comment]
This will be fixed whenever I reorganize the sounds.json file.

**Comment by bconlon1** [comment]
Duplicate of #261.
