### ISSUE TITLE
Bug: Music system bugs.

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#656]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

40.1.31

### The Aether 1 Version

1.0.0

### Client Log

https://gist.github.com/ZolaKluke/23baa189b129b4ad551ce9d7918f0df8

### Steps to Reproduce

1. Load up the main menu with the world preview enabled
2. Wait for the main menu music to play
3. Quick load into your world and the music will continue to play

### What You Expect To Happen

The main menu music to stop playing

### What Actually Happened

The main menu music continued to play

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
In-world music might also be playing on the main menu.

**Comment by bconlon1** [comment]
Music manager doesn't work with world preview atm.

**Comment by bconlon1** [comment]
Seems overworld music still has the chance of playing in the Aether as well on world load.
