### ISSUE TITLE
Bug: Skyroot Boats are uncraftable

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#671]
### Forge Version

40.1.25

### The Aether 1 Version

1.18

### Steps to Reproduce

Try to craft Skyroot Boats

### What You Expect To Happen

To get Skyroot Boats

### What Actually Happened

nothing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Builderdog841** [comment]
Just realized that you can't craft anything with skyroot planks

**Comment by Builderdog841** [comment]
Ok now it suddenly works. weird

**Comment by bconlon1** [comment]
Reopening because I want to look into this.
