### ISSUE TITLE
(Strange movement) Combining this mod and the Mo' Bends mod leads to some funky results...

### ISSUE THREAD

**Issue by MCAlexisYT** [Gilded-Games/The-Aether#679]
What is expected to happen: "Wearing gloves from the aether mod with Mo' Bends enabled will follow the bending arms"
What actually happens: "Gloves only follow vanilla movement"

How to replicate this:
1. Download the Aether and Mo' Bends mod
2. Create a new world in creative
3. Get the gloves out
4. Once you get to the survival inventory, click the Aether cloud button.
5. Shift-click the gloves
6. Move around (make sure that custom player animations are enabled by pressing G, then pressing "settings" and scrolling all the way down to the bottom. If and only if it is "OFF", click on it. It should be on by then)

**Comment by bconlon1** [comment]
Mo' Bends is not on 1.18+ so this is not an issue with the ported version of the mod, which this repo is for. This is assumedly for the 1.12 version. These animation issues are hard or impossible to fix unless the mod that causes the issue has the necessary hooks to allow for fixing it.

**Comment by Burning-Cactus** [comment]
Mo' Bends isn't out past 1.12. This is the repository for the 1.18+ rewrite of the Aether.
