### ISSUE TITLE
Feature Request: Forgotten Rose Texture

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#681]
### What Feature Types Apply to This Request?

Art

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The new white flower texture would make more sense if it looked like the Forgotten Rose from the Aether II: Highlands instead of the White Rose, since they are a flower that is unique to the Forgotten Highlands biome.

Aether II:
![2022-06-18_11 17 55](https://user-images.githubusercontent.com/60141811/174446648-6d0b23b7-72af-4428-8a7a-a0a073cd361f.png)
Aether I:
![2022-06-18_11 49 37](https://user-images.githubusercontent.com/60141811/174446659-0d600054-8537-414d-92d2-6071b1018ca7.png)

### Why Should It Be in the Mod?

It should be in the mod to make the Aether and Aether II connect slightly better, and to make the Forgotten Highlands biome seem even more like it actually _is_ the original Aether biome.

### Does This Feature Improve Compatibility With Another Mod?

The Aether II: Highlands (sort of)

### Please Read and Confirm the Following

- [x] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by OzPayn** [comment]
The new Aether 1 design is likely to also be used in Aether II going forward. So there will be parity between the two mods but once they're on the same version (1.19+)
Therefore we won't be changing the new white flower texture to match the 1.12 Aether II version.
