### ISSUE TITLE
Feature Request: On Pro Tips

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Gilded-Games/The-Aether#683]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Loading Screen Tips

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

You should run experiments to verify that the loading screen tips provided by the mod are still correct in modern versions of Minecraft.

### Why Should It Be in the Mod?

It would be unfair to give the Player incorrect tips.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This was already done.
