### ISSUE TITLE
Feature Request: New Pro Tip

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Gilded-Games/The-Aether#684]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Loading Screen Tips

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

a tip that warns not to use a Gravitite Sword when a Swet is on your head

### Why Should It Be in the Mod?

This is obvious in hindsight, but it is not at all so in foresight. It is not extremely important, but it fits the theme you seem to have with tips of minor but still helpful things, and it could be a lifesaver in hardcore. Obviously, if the Gravitite Sword will not apply its effect on ridden entities, feel free to ignore this.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We're not adding more tips.
