### ISSUE TITLE
Bug: Incubator GUI is missing its texture/uses the missing texture.

### ISSUE THREAD

**Issue by Static45** [Gilded-Games/The-Aether#694]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Gui

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

41.0.62

### The Aether 1 Version

1.0

### Steps to Reproduce

Open an incubator 

### What You Expect To Happen

It should render properly.

### What Actually Happened

The gui uses the missing texture.

### Additional Details

No optifine is in use, and me and melonvision confirmed this issue. It isnt an error from my end.
![2022-06-30_08 24 37](https://user-images.githubusercontent.com/100433950/176686983-7b916f15-aab7-4acb-a55d-4c416ab299eb.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Cannot reproduce, need more information to reproduce.

**Comment by bconlon1** [comment]
Please list any additional mods that may have been included when running into this bug.

**Comment by bconlon1** [comment]
Determined to be an issue specifically with the feat/repository-cleanup branch.
