### ISSUE TITLE
Bug: Icestone turns the water into ice only if the player near.

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#696]
### What Feature Types Apply to This Bug?

Block, System

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

41.0.62

### The Aether 1 Version

1.0

### Steps to Reproduce

Place down an icestone in the water. Wait for it to generate the ice around.
For the second part, find an icestone in a water lake generated by Minecraft. It turns the water into ice only when the player is nearby.

### What You Expect To Happen

Not what happened.

### What Actually Happened

![2022-06-30_15 57 05](https://user-images.githubusercontent.com/79194869/176695960-b3d2e53d-72ad-4cac-87e1-fb32eb005104.png)
+ The Icestone placed down in the terrain when generating the world turns the water into ice again, only if the player is near it

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Forgot to look into the part where the icestone only works when the player is near.

**Comment by bconlon1** [comment]
This just seems like vanilla behavior to me, blocks spawned in the world don't update or update things around them until the player is close enough.
