### ISSUE TITLE
Bug: Sun spirit's hitbox is lowered down than it should be, can be killed by using a weapon, and the red overlay when player hits the spirit is appearing causing it to look weird.

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#697]
### What Feature Types Apply to This Bug?

Entity, System

### Forge Version

41.0.62

### The Aether 1 Version

1.0

### Steps to Reproduce

Summon and hit a Sun Spirit and see.

### What You Expect To Happen

Not what happened.

### What Actually Happened

![2022-06-30_16 02 50](https://user-images.githubusercontent.com/79194869/176697283-8e7118de-4cb9-4297-ae6f-4ef78bdb15fb.png)
![2022-06-30_16 02 56](https://user-images.githubusercontent.com/79194869/176697289-1619ea1c-7fc7-4041-9d94-e3bfded34e49.png)
As you can see, the hitbox is not in the place where it should be, and when you hit the spirit, the red entity overlay still appears and when it's mixed with the blue spirit texture, it does look weird.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Burning-Cactus** [comment]
The sun spirit is not implemented yet, so I'm closing this for now.
