### ISSUE TITLE
Bug: Sun altar GUI is missing a black outline in some places

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#698]
### Forge Version

41.0.62

### The Aether 1 Version

1.0

### Steps to Reproduce

Place down a Sun Altar.
Open the GUI.

### What You Expect To Happen

Not what happened.

### What Actually Happened

![Snímek obrazovky 2022-06-30 160534](https://user-images.githubusercontent.com/79194869/176698154-95dc1709-fcac-47a3-9b8d-8d095b253192.jpg)
As you can see, the texture gets.. stretched probably?... causing the black outline not appear on the bottom and right side.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Might have an incorrect size for the gui in some way which could be causing this.

**Comment by bconlon1** [comment]
Fix: Need to increase the xSize from 175 to 176 and the ySize from 78 to 79 for the Sun Altar screen blit.
