### ISSUE TITLE
Bug: Moa dismount only works when you jump.

### ISSUE THREAD

**Issue by SilverFlakes** [Gilded-Games/The-Aether#699]
### What Feature Types Apply to This Bug?

Entity

### Forge Version

41.0.61

### The Aether 1 Version

1.0.0

### Steps to Reproduce

Every time you ride a moa you can not dismount until you jump.
1. Get a rideable moa.
2. Mount it and Sneak, you can't get off.
3. Jump and hold Sneak, when you land you might get off.

### What You Expect To Happen

You should freely be able to get off the moa.

### What Actually Happened

You can't dismount a moa without jumping and some times it doesn't work.

### Additional Details

![2022-06-30_22 02 29](https://user-images.githubusercontent.com/67766513/176809003-c0981c64-ccb6-4c73-8b28-7e264e824f0c.png)

Picture of hurtbox being lowered due to sneaking while on moa.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
There are a couple other things broken with moas and all our mounts it seems, such as quicker falling when crouching. 1.19 must've changed something with unmounting in some way that's broken our code.

**Comment by bconlon1** [comment]
Our MountableAnimal class seems to have an issue where it does not properly set isOnGround on the server, causing various desyncs leading to bugs such as this.
