### ISSUE TITLE
Bug: Agility cape underwater is inconsistent

### ISSUE THREAD

**Issue by SilverFlakes** [Gilded-Games/The-Aether#702]
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

41.0.61

### The Aether 1 Version

1.0.0

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

When you swim in water and sneak while on a block the agility cape will let you fall off and climb blocks.
1. Go underwater with the Agility cape
2. Sneak and go to the edge of the block, you should fall off.
3. Next instead of falling off a block sneak while swimming to climb a block.

### What You Expect To Happen

The cape should let sneaking mechanics work underwater.

### What Actually Happened

Sneaking mechanics and cape functions are inconsistent while underwater.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
This is weird considering the ability should be disabled when crouching and thus not be doing anything. Maybe the check isn't working properly when the player is in the swimming state.

**Comment by bconlon1** [comment]
Fix: Need to change the isCrouching() checks for the Agility Cape to isShiftKeyDown().
