### ISSUE TITLE
Feature Request: Fabric Support

### ISSUE THREAD

**Issue by zurgeg** [Gilded-Games/The-Aether#703]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Mod Itself

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Fabric support would be nice to have.

### Why Should It Be in the Mod?

A lot of people use Fabric, for many reasons, so it would be nice to have this.

### Does This Feature Improve Compatibility With Another Mod?

It improves compatibility with mods that are only on Fabric ;)

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
This isn't really a feature request, We are not developing a Fabric port at this moment, it may happen in the future, but we are focused on Forge at the moment.

**Comment by Aethyus** [comment]
A Fabric mod has appeared, called "Paradise Lost", a mod that takes the concept of the Aether, hence its former name "Aether Reborn", but it is a Fabric only mod. The link: https://www.curseforge.com/minecraft/mc-mods/paradise-lost

**Comment by bconlon1** [comment]
Please do not point to Paradise Lost as Aether on Fabric. We are both trying to move away from this comparison. They are separate mods that will have separate content, they don't really fulfill the same things.

**Comment by StockiesLad** [comment]
> Please do not point to Paradise Lost as Aether on Fabric. We are both trying to move away from this comparison. They are separate mods that will have separate content, they don't really fulfill the same things.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
