### ISSUE TITLE
Feature Request: Aerbunnies Drop Rabbit Hide.

### ISSUE THREAD

**Issue by PraseodymiumSpike** [Gilded-Games/The-Aether#704]
### What Feature Types Apply to This Request?

Entity, Item

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Aerbunnies should drop Rabbit Hide.

### Why Should It Be in the Mod?

It would make it easier to obtain Bundles once they are added.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
We're not gonna be adding to mob drops like this. Bundles don't even have a known planned recipe so your reasoning is not particularly valid anyways.
