### ISSUE TITLE
Bug: Small chance of overworld music playing in the aether after loading the world.

### ISSUE THREAD

**Issue by SilverFlakes** [Gilded-Games/The-Aether#708]
### What Feature Types Apply to This Bug?

Audio

### Forge Version

41.0.61

### The Aether 1 Version

1.0.0

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

This should rarely happen.
1. Go into the aether and then save and quit.
2. When you rejoin if the game decides to play music right away it will be from the overworld.
3. If music plays again after then aether music will play like normal.

### What You Expect To Happen

The Aether should only play its music.

### What Actually Happened

Overworld music played after loading.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Covered by #656.
