### ISSUE TITLE
Feature Request: Ambrosium lanterns, and possibly ambrosium jack o'lanterns

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#71]
These obviously weren't part of the original Aether mod, but for the sake of parity/consistency (for much the same reasons stripped skyroot logs were added) and giving builders more diverse options adding these is something I'd recommend. Would be crafted in the normal way with substitution where required.

Here's a terrible mockup texture I made for them:
![2021-03-12_15 13 41](https://user-images.githubusercontent.com/52297970/110959757-ef8e6200-8345-11eb-98bc-5c9c915a6b13.png)
![lantern](https://user-images.githubusercontent.com/52297970/110959776-f321e900-8345-11eb-981a-c7d30b810321.png)
![lantern](https://user-images.githubusercontent.com/52297970/110959792-f6b57000-8345-11eb-85dc-4cfa6095f100.png)

**Comment by muzikbike** [comment]
Additionally: ambrosium jack o'lanterns could make for an interesting addition.

**Comment by bconlon1** [comment]
Might just make this something that is added if you have Abnormals Core installed, considering they seem to consider lantern types vanilla consistency. With Autumnity maybe the jack o' lanterns thing could also be added.

**Comment by bconlon1** [comment]
May save content like this for addons potentially. Might be good to keep any actual new content for the sake of mod compatibility to a separate mod, but not sure yet.

**Comment by bconlon1** [comment]
Probably not gonna end up doing this. Addon creators will be free to make this kind of content after release.
