### ISSUE TITLE
Bug: Freezers can let buckets be in the fuel slot even though it serves no use.

### ISSUE THREAD

**Issue by SilverFlakes** [Gilded-Games/The-Aether#712]
### What Feature Types Apply to This Bug?

Block, System

### Forge Version

41.0.61

### The Aether 1 Version

1.0.0

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

1. Hover over the fuel slot in a freezer with a bucket and click. (Shift click won't work)
2. The bucket should be where icestone should go.

### What You Expect To Happen

Freezers should only let icestone in the fuel slot.

### What Actually Happened

I assume that a relic from furnace code lets buckets be in the fuel slot.

### Additional Details

![2022-07-05_22 58 13](https://user-images.githubusercontent.com/67766513/177459330-1e8a7348-8076-49b6-8a10-b87d00041fb2.png)

Screenshot.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SilverFlakes** [comment]
Same issue in alters, but not incubators.

**Comment by bconlon1** [comment]
Yeah this is leftover from the sponge drying mechanic the furnace has.
