### ISSUE TITLE
Feature Request: Smoother/Less choppy Aechor Plant Animation

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#726]
### What Feature Types Apply to This Request?

Entity

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The current Aechor Plant animation looks choppy, since it is only updated each tick.

Potentially helpful code from the Aether II (which has a smoother aechor plant animation):
[The Aether II - EntityAechorPlant::tickAnimation](https://github.com/Gilded-Games/The-Aether-II/blob/e838fc8746730ce425ed668281ca0d903fb0ab4f/src/main/java/com/gildedgames/aether/common/entities/monsters/EntityAechorPlant.java#L317-L338)
[The Aether II - RenderAechorPlant::preRenderCallback (sin calculation)](https://github.com/Gilded-Games/The-Aether-II/blob/e838fc8746730ce425ed668281ca0d903fb0ab4f/src/main/java/com/gildedgames/aether/client/renderer/entities/living/RenderAechorPlant.java#L39-L67)

### Why Should It Be in the Mod?

It should be in the mod to make the Aechor Plant's animation look better and less out of place, since every other mob animation in the Aether and Minecraft is smooth.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Probably caused by the Aechor Plant's animation code being handled in the regular entity tick, not the client tick.

**Comment by OzPayn** [comment]
Yeah this would be nice to have fixed thanks for the report

**Comment by bconlon1** [comment]
If you happen to find more animations that could use fixing make sure to report.

**Comment by Zepalesque** [comment]
Ok!

**Comment by Zepalesque** [comment]
I found some more some more choppy animations:
- Zephyr puffing up before attacking
- Aerbunny body growing, shrinking and rotating (all affected) when hopping
- Aerwhale up and down rotation
- Sheepuff wool puffing up after eating (I have not seen this one in-game, but it seems to have the same issue in the code)
