### ISSUE TITLE
Feature Request: More choppy animation fixes

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#727]
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Rendering/Animations

### Is This an Enhancement to a Preexisting Feature?

- [X] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Continuation of #726 

Here are some more choppy animations I found:
- Zephyr puffing up before attacking
- Aerbunny hopping animation (rotation and scaling)
- Aerwhale up and down rotation
- Sheepuff wool puffing up (I have not seen this one in-game, but it seems to have the same issue in the code)
- Sheepuff head rotation when looking up and down (This also affects vanilla sheep)

### Why Should It Be in the Mod?

To improve consistency with vanilla animations, which are all smooth

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Sheepuff animation uses Sheep animation, and for some reason the Sheep's head animation is just like that it seems.

**Comment by bconlon1** [comment]
Also the Sheepuff wool is not animated similar to how wool growing on Sheep isn't, so that is working as intended.
