### ISSUE TITLE
aether:skyroot_planks is not a member of #minecraft:planks

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#73]
All other plank types from vanilla are, seems this was left out for some reason

![2021-03-12_15 57 47](https://user-images.githubusercontent.com/52297970/110965196-e1434480-834b-11eb-807a-8d03ff5794bb.png)
![2021-03-12_15 57 48](https://user-images.githubusercontent.com/52297970/110965201-e1dbdb00-834b-11eb-87e7-1531bd024728.png)

**Comment by bconlon1** [comment]
intended to avoid recipe conflicts.

**Comment by muzikbike** [comment]
the block tag and item tag are distinct, though?
