### ISSUE TITLE
Enhancement: Allow berry bushes to be placed in flower pots

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#74]
This is the only non-full-cube (sorta) plant type that can't be placed in pots (all flowers and saplings can). Allowing them to be added to pots would give just that bit more capability for customization. May require a dedicated texture, though, as having the full stem render in the pot might look a bit clunky - I might make such a texture once aether textures are revamped for 1.14+.

![2021-03-12_15 28 17](https://user-images.githubusercontent.com/52297970/110966016-befdf680-834c-11eb-843c-43e48543f487.png)
![2021-03-12_15 28 18](https://user-images.githubusercontent.com/52297970/110966020-c02f2380-834c-11eb-968c-dfed789e50e2.png)

Perhaps a bit out of place for vanilla, but quark allows sweet berry bushes to be placed in pots, so maybe this could be only allowed if quark is present. At the same time, I don't see much point in making the presence of other mods necessary for stuff like this, so it could be a default feature.

**Comment by bconlon1** [comment]
Probably only gonna make this a Quark compatibility feature.

**Comment by bconlon1** [comment]
This could be done when we switch to 1.18 for consistency with Azalea Bushes, but I'm not sure yet. It'll be something we'll have to consider.

**Comment by MagmaSlime123** [comment]
And Legacy's saplings/flowers.

**Comment by bconlon1** [comment]
> And Legacy's saplings/flowers.

"This is the only non-full-cube (sorta) plant type that can't be placed in pots (all flowers and saplings can)" what you're suggesting is already added.

**Comment by MagmaSlime123** [comment]
Ah.
