### ISSUE TITLE
Bug: Aerogel wall faces cull against blocks they really shouldn't

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#75]
Related to issue #69.
![2021-03-12_16 07 31](https://user-images.githubusercontent.com/52297970/110966617-5b27fd80-834d-11eb-9fe3-87d6a25ee07a.png)
![2021-03-12_16 07 42](https://user-images.githubusercontent.com/52297970/110966619-5bc09400-834d-11eb-99d4-2b89de5282ee.png)
![2021-03-12_16 07 53](https://user-images.githubusercontent.com/52297970/110966620-5c592a80-834d-11eb-9556-a1eb17ee78c5.png)

**Comment by bconlon1** [comment]
Still trying to figure this out but for now its been shelved as it was taking too long to solve, will return to this at a later date.
