### ISSUE TITLE
Aether subtitle string translations are missing

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#77]
Should be an easy fix since the translations just need to be added to sounds.json, honestly I might even just do this one later.

![2021-03-12_16 18 20](https://user-images.githubusercontent.com/52297970/110967925-d50cb680-834e-11eb-892c-0dec6d45d38a.png)

**Comment by bconlon1** [comment]
This will be fixed whenever I reorganize the sounds.json file.
