### ISSUE TITLE
Certain explosion types allow for fire to exist in the Aether

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#78]
Fire is denied from being placed by most normal means, but explosions which create fire (bed/respawn anchor/ghast) still create fire.

![2021-03-12_16 25 25](https://user-images.githubusercontent.com/52297970/110969162-45680780-8350-11eb-976c-cff881f2e6e1.png)
![2021-03-12_16 25 35](https://user-images.githubusercontent.com/52297970/110969165-46993480-8350-11eb-8102-e5cb49b5ffad.png)
![2021-03-12_16 26 07](https://user-images.githubusercontent.com/52297970/110969168-4731cb00-8350-11eb-93e2-5eb72eacdbdf.png)

In 1.12.2, ghast fireballs still create fire, so this may be intended or just a really weird edge case.

**Comment by bconlon1** [comment]
Just gonna consider this as intended since technically fire has always been allowed in the Aether in some form and we cant completely cancel it out or else it'd have some issues with the Sun Spirit boss fight.
