### ISSUE TITLE
Feature Request: Add ruined tower

### ISSUE THREAD

**Issue by mmmmmmmmmmmmmmmmaly** [Gilded-Games/The-Aether#782]
### What Feature Types Apply to This Request?

World-Gen

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A ruined tower of past players that escaped to the aether and tried to survive but after a while they had fallen and left there base to get destroyed

### Why Should It Be in the Mod?

Because it will add more structure's and make it seem like someone was there before you

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
![2022-08-28_18 08 27](https://user-images.githubusercontent.com/68011857/187096661-4c4edfab-8f92-40e3-93c4-36a702930a58.png)
![2022-08-28_18 08 36](https://user-images.githubusercontent.com/68011857/187096665-a5e0a59d-59a4-4910-a008-85f560a82480.png)
![2022-08-28_18 08 38](https://user-images.githubusercontent.com/68011857/187096670-ad2c7252-c5a7-4ad5-a180-e51fd531d70b.png)
![2022-08-28_18 08 39](https://user-images.githubusercontent.com/68011857/187096674-d6a51ed1-a9fb-4b06-8de4-caadac99d23e.png)
![2022-08-28_18 08 46](https://user-images.githubusercontent.com/68011857/187096675-b7adb0f7-89ab-4b79-9f78-435899e1d1aa.png)
![2022-08-28_18 10 12](https://user-images.githubusercontent.com/68011857/187096677-341a6a0d-d980-4146-8935-ba232e323c45.png)

**Comment by bconlon1** [comment]
This is not a feature from the original Aether mod, and does not improve parity between The Aether and Minecraft or other mods in any way.

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
sorry

**Comment by Burning-Cactus** [comment]
If you're willing to learn some technical stuff, you could accomplish adding your own naturally generating structures to the Aether through a data pack. 😉
