### ISSUE TITLE
Bug: Aether Portal Item cannot replace replaceable blocks (other than air)

### ISSUE THREAD

**Issue by Zepalesque** [Gilded-Games/The-Aether#785]
### What Feature Types Apply to This Bug?

Block, System

### What Type of Bug Is This?

Annoyance

### Forge Version

43.0.19

### The Aether 1 Version

1032436

### Steps to Reproduce

1. Open a world
2. Find some (tall) grass
3. Try to place an Aether portal next to the grass, by using the portal item

### What You Expect To Happen

The portal would be placed, and replace the grass.

### What Actually Happened

The portal could not be placed

### Additional Details

https://user-images.githubusercontent.com/60141811/187246001-4341ba75-bc3f-4cba-94c3-9f6ef8e240c5.mp4

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Have already made note of this in #311.
