### ISSUE TITLE
Falling below y=-1 causes the sky to go much darker

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#79]
This is probably due to the weird remaining void fog code. This does affect the overworld but obviously isn't likely to be encountered there, but in the aether's case the effects are obvious.

This is (at least according to my testing of data pack dimensions in 1.17) tied to the minimum y value of a given world rather than hardcoded to be at or around y=0.
![2021-03-12_16 33 55](https://user-images.githubusercontent.com/52297970/110970045-42b9e200-8351-11eb-8da3-2c90f2ed99aa.png)
![2021-03-12_16 33 57](https://user-images.githubusercontent.com/52297970/110970050-43527880-8351-11eb-8725-d8ba25d6247a.png)

**Comment by Ultrasquid9** [comment]
once falling between dimensions is implemented, this probably won't be seen very much, as you won't be able to go far below Y=0
