### ISSUE TITLE
Bug: Dungeons have issues with removing blocks and features on generation

### ISSUE THREAD

**Issue by ZolaKluke** [Gilded-Games/The-Aether#790]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.3

### The Aether 1 Version

0.0.1

### Steps to Reproduce

Find a gold dungeon and walk inside

### What You Expect To Happen

The interior to be completely clear of blocks that don't belong there

### What Actually Happened

There were leaf blocks and aercloud blocks inside some

### Additional Details

World seed: 7665172736639170702

![image](https://user-images.githubusercontent.com/6497775/187348020-a7ed48da-6a68-4316-8bb2-49fe5944d393.png)
![image](https://user-images.githubusercontent.com/6497775/187348065-2ffa2872-1702-4b5b-9684-f3cadad5cca9.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
There's a similar issue with Bronze Dungeons although it might be slightly different, since aerclouds have been seen to spawn in the slider's room.

**Comment by bconlon1** [comment]
Solution to this is making sure certain features make sure to check whether or not they are about to generate inside a structure's bounds, so that they will not generate somewhere a structure has been placed. Example: https://github.com/TelepathicGrunt/RepurposedStructures/blob/latest-released-Quilt/src/main/java/com/telepathicgrunt/repurposedstructures/mixin/features/NoLakesInStructuresMixin.java

**Comment by bconlon1** [comment]
Might be doable with a placement filter that can be applied to features.
