### ISSUE TITLE
Bug: World Preview bugs with overlays and other things

### ISSUE THREAD

**Issue by OzPayn** [Gilded-Games/The-Aether#792]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.3

### The Aether 1 Version

0.0.1

### Steps to Reproduce

1. Use Life Shard
2. Enable Silver Hearts in the Config
3. Exit World
4. Enable World Preview in the Main Menu
[Example](https://i.imgur.com/puV3EkJ.png)

### What You Expect To Happen

All HUD elements should not be visible during the world preview

### What Actually Happened

The Silver Heart overlay for the extra hearts obtained by the Life Shards remains visible.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Wonder if this means any other overlays are visible as well, I'll need to check this.

**Comment by bconlon1** [comment]
Supposedly all overlays except the hammer of notch one and the repulsion shield one can appear in the world preview; these overlays likely need an additional check to not appear when GUIs are turned off, or we can cancel the overlay event with the world preview, can't remember if we do that already.

**Comment by bconlon1** [comment]
Also apparently mounts cause the world preview to not rotate which I guess is not surprising.
