### ISSUE TITLE
Bug: Certain in-world sounds are stereo instead of mono

### ISSUE THREAD

**Issue by KingPhygieBoo** [Gilded-Games/The-Aether#793]
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.3

### The Aether 1 Version

0.0.1

### Steps to Reproduce

- Trigger any applicable stereo sound in-world (examples listed below). Weather this be through /playsound with an offset, or from original source.
- Look around, or move away from the sound's source while it's playing.

### What You Expect To Happen

The sound should be heard coming from the direction it came, at an applicable volume for whatever played it.

### What Actually Happened

The sound is always full volume, and doesn't appear to originate from any direction.

### Additional Details

This issue is new to 1.14+, after the sound system was rewritten. Only UI, ambience, or music files are typically in stereo (with the exception of records). Things that don't have a specific in-world origin.

**Affected Sounds (all in the `assets/aether/sounds/` directory):**
- entity/aerbunny/hurt
- entity/aerbunny/death
- entity/aerwhale/death
- entity/moa/say
- entity/zephyr/call
- entity/zephyr/shoot

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Directories of affected sounds (leaving here for reference):
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/aerbunny/hurt.ogg
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/aerbunny/death.ogg
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/aerwhale/death.ogg
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/moa/say.ogg
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/zephyr/call.ogg
https://github.com/Gilded-Games/The-Aether/blob/1.19/src/main/resources/assets/aether/sounds/entity/zephyr/shoot.ogg
