### ISSUE TITLE
Bug: Campfires can be placed in the Aether

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#80]
Other examples of open flames (torches, fire) are explicitly disallowed, however campfires are completely fine apparently.

While these could just be added to #banned_in_aether it might be better to have them be placed, but immediately extinguished as a result (with relighting obviously forbidden).

![2021-03-12_16 42 14](https://user-images.githubusercontent.com/52297970/110970916-236f8480-8352-11eb-9d8a-59578c143366.png)
![2021-03-12_16 42 15](https://user-images.githubusercontent.com/52297970/110970918-24081b00-8352-11eb-88dc-631b04476a27.png)

**Comment by muzikbike** [comment]
Perhaps ambrosium campfires could be added as an Aether-exclusive alternative?

**Comment by bconlon1** [comment]
Might be able to make a recipe system for certain block and blockstate conversions like this so there's not multiple systems floating around to handle different conversions of fire blocks and so its more scalable for addons.

**Comment by bconlon1** [comment]
May have to investigate potential design solutions to the fact this would make campfires overall unusable in the Aether which feels a bit weird of a design choice, but I don't think it'd warrant an entire new block like suggested earlier in this issue thread.

**Comment by bconlon1** [comment]
Might solve this with soul campfires and other soul fire blocks being allowed in the Aether.

**Comment by bconlon1** [comment]
This system is probably also going to have to be used to burn out candles in the Aether, and possibly Jack O' Lanterns but I don't remember if that was a thing in the original.
