### ISSUE TITLE
Ambrosium blocks

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#81]
Again, these weren't a part of the original aether mod. But in the current state of the game, with literally every other ore resource having a block form, the absence of it in ambrosium's case just sticks out way too much, so it's something I'd highly recommend for the sake of continuity (it's not taking anything more away from the classic feel as it is bringing the mod up to current vanilla standards). 9 ambrosium shards in, 1 block out, 1 block in, 9 shards back out. Given its equivalence to coal, it wouldn't be usable for beacons.

----

We could leave it at that, but it might be interesting to give said block a handful of exclusive mechanics. One I have in mind comes from the same train of thought as #71 - perhaps if lit on fire, an ambrosium block would result in yellow fire, which is to the ambrosium torch as soul fire is to the soul torch and normal fire is to the torch? This fire would be able to exist in the Aether unlike the other two, and would burn infinitely on top of the ambrosium block (blocks that result in yellow fire would be controllable via block tags, just like soul fire).

**Comment by reetamb** [comment]
i agree with the sake of continuity thing but for whatever reason that's not enough justification to add stuff so this will probably be featured in an official addon instead

**Comment by muzikbike** [comment]
As a solution to #80: ambrosium campfires could be implemented, which function fully in the Aether (both in being fire and cooking) unlike the other two.

**Comment by bconlon1** [comment]
Replacing this with #236.
