### ISSUE TITLE
Bug: Accsesories equiped through the accsesory screen get deleted

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#816]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.1

### The Aether 1 Version

0.0.1

### Steps to Reproduce

-Step 1 put an accsesory in an accsesory slot
-Step 2 See how it gets deleted

### What You Expect To Happen

To equip the accsesory

### What Actually Happened

It got deleted

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
I cannot reproduce this bug, could you please provide more information about this and provide a log that I can check. Also provide a video of this in action for more clarification.

**Comment by bconlon1** [comment]
Issue appears to be triggered both by either clicking with an item on a slot with that an item can't be inserted into, or clicking the display button with an item. After doing this, spamming the item on the correct slot seems to usually cause it to disappear after a couple clicks.

**Comment by bconlon1** [comment]
Issue also does not appear to be a desync as far as can be told as the item never returns to the player, it just gets deleted on both sides.
