### ISSUE TITLE
Bug: Modifying generic.max_health attribute to the player breaks life shard silver heart overlay.

### ISSUE THREAD

**Issue by Static45** [Gilded-Games/The-Aether#822]
### What Feature Types Apply to This Bug?

Gui

### What Type of Bug Is This?

Annoyance

### Forge Version

43.1.1

### The Aether 1 Version

1.0.0

### Steps to Reproduce

- Modify the player generic.max_health attribute in any way, either through mods like origins or using vanilla features like applying attributes to armor and then wearing that armor, or even the health boost potion effect
- consume life shards

### What You Expect To Happen

I expected the silver hearts to show up like how golden absorbtion hearts show up, dynamically adjusting for your actual red hearts count. You can notice what i mean by giving yourself absorbtion and then use health boost to increase this attribute.

### What Actually Happened

Instead, they are static, they dont change their location and apparently they are a clone of the newly added hearts, mirroring their damage status. 

### Additional Details

The issue can he noticed very easily when you mod your max health to values greater than 40, making you have three or more rows of red hearts or lower than 20, substracting from the first row. Im coming later with photos to better show this, but for now i have to do some homework :copium:

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Static45** [comment]
![2022-09-06_11 06 30](https://user-images.githubusercontent.com/100433950/188669723-0e253386-5ca6-4136-b473-228e24f306dc.png)
Another interesting behavior i noticed, increasing your health to very high numbers makes the health sprites lower down, and you end up seeing the red hearts hidden by the overlay. This issue can be seen starting when you end up having three or more rows of health, in this photo i have 22 hearts and you can see very closely the pixels misalignment.

**Comment by bconlon1** [comment]
This also ends up getting broken by absorption hearts.
