### ISSUE TITLE
Bug: Slider still needs better unstuck and navigation behavior.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#838]
The slider's ability to get unstuck from positions or climb vertical obstacles and navigate them still needs some work.

**Comment by bconlon1** [comment]
For related information on this see #795 and #787

**Comment by bconlon1** [comment]
Idea 1:
- Make yFirst and xFirst for Slider modifiable based on collision; if the Slider collides horizontally, it'll switch to yFirst if it collides with something horizontally, and when it stops, it'll switch back to xFirst to navigate vertical obstacles. This might also work the other way around for choosing horizontal collision if it hits something vertically, however that gets trickier to track as there are four horizontal directions to keep track of compared to two. Although the vertical might be slightly tricky in regards to that as well if the player is vertically lower but there is an obstacle in the Slider's horizontal and bottom paths.

**Comment by Alexmasonseals** [comment]
Slider should ignore non-solid blocks )like grass, flowers etc) or should break them without stopping
