### ISSUE TITLE
Bug: Incompatibility with Rubidium

### ISSUE THREAD

**Issue by Lolothepro** [Gilded-Games/The-Aether#843]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Crash when the player enters the world.

### What Type of Bug Is This?

Compatibility

### Forge Version

43.1.27

### The Aether 1 Version

0.0.1

### Is This Bug a Conflict With Another Mod?

Rubidium

### Client Log

https://gist.github.com/Lolothepro/35e3169bdb25fbaa3eaacfaec6342c5b

### Crash Report (if applicable)

https://gist.github.com/Lolothepro/65e1b491031f690e1b872a457275c938

### Steps to Reproduce

1.Load a world with Aether and Rubidium

### What You Expect To Happen

That the game does not crash.

### What Actually Happened

The game crashes when a player enters the world with Rubidium.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
While even if this is crashing with the Aether, this log points nowhere to us so there's nothing I think we can do. I would recommend reporting this to Rubidium instead.
