### ISSUE TITLE
Brandon

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#845]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

brandon

### What Type of Bug Is This?

Annoyance

### Forge Version

1.20

### The Aether 1 Version

1.21

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

ask brandon for a pvp match

### What You Expect To Happen

get challenged

### What Actually Happened

he never spoke to me again about it

### Additional Details

i am so mad about this can you please ban brandon from the community? it broke my heart :[

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
no
