### ISSUE TITLE
Valkyrie queen can be cheesed by her sitting in a boay

### ISSUE THREAD

**Issue by Alexmasonseals** [Gilded-Games/The-Aether#846]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.1.25

### The Aether 1 Version

0.0.1

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

spawn a valkyrie queen
push a boat onto her

### What You Expect To Happen

valkyrie not being able to use the boat

### What Actually Happened

valkyrie queen uses the boat

### Additional Details

![2022-10-10_13 40 35](https://user-images.githubusercontent.com/75763838/194950273-214c6bc4-c114-4ca5-a6be-b24fc26556f5.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Gonna just merge this into the code cleanup todo list.

**Comment by CDAGaming** [comment]
Shhh, it's a feature, shh just go into the light my child, shhhhhhhh it'll all be okay :)
