### ISSUE TITLE
Bug: Rendering dungeon block symbols in creative is inneficient

### ISSUE THREAD

**Issue by Burning-Cactus** [Gilded-Games/The-Aether#847]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Performance

### Forge Version

43.1.25

### The Aether Version

Indev

### Steps to Reproduce

Use the fill command to make a lot of blocks. As more blocks get marked, the performance will progressively get worse.

### What You Expect To Happen

To have decent FPS while building a silver dungeon

### What Actually Happened

I managed to get all the way down to 9 FPS on my building void world.

### Additional Details

![image](https://user-images.githubusercontent.com/23108473/196826727-8c9b88f7-97c9-4371-8853-7c6ce2ed264a.png)

This is just from spawning in a void superflat preset and converting the spawn platform to locked dungeon blocks.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Mentioned in #311.
