### ISSUE TITLE
Bug: Game is crashing when I die.

### ISSUE THREAD

**Issue by murao-kun** [Gilded-Games/The-Aether#853]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Crash

### Forge Version

43.1.47

### The Aether Version

1.0.1

### Crash Report (if applicable)

https://gist.github.com/murao-kun/7d7478668737ad9d1a76f1a940495154

### Steps to Reproduce

1. Create or load world.
2. Die in the overworld.

### What You Expect To Happen

Can't really say much, since there is no expected behavior other than just not to crash.

### What Actually Happened

Game crashing.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Use 1.19.2-0.1.0 not 1.19.2-0.0.1.
