### ISSUE TITLE
Skyroot Axes do not have double drops on entities

### ISSUE THREAD

**Issue by reetamb** [Gilded-Games/The-Aether#86]
Considering that axes are generally counted as a weapon these days it would probably be nice to fix this

**Comment by bconlon1** [comment]
A potential addition to this could just be making all equipment have the weapon/tool ability, so all tools get the double drops for entities to keep consistent.

**Comment by bconlon1** [comment]
Conclusion seems to be that since axe's still are primarily a tool and swords primarily a weapon that the abilities be kept separate.
