### ISSUE TITLE
Feature Request: Chiseled Skyroot Bookshelf

### ISSUE THREAD

**Issue by Mr-Aerod** [Gilded-Games/The-Aether#862]
### What Feature Types Apply to This Request?

Art, Block

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

Since 1.19.3 is adding Chiseled Bookshelves to the game, why not add an Aether variant too?

### Why Should It Be in the Mod?

We already have Skyroot Bookshelf in the mod, so it should be added for consistency. It will also be a really nice decorative block with some cool use.

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment]
Chiseled Bookshelf will be in 1.20. We can look into this feature when the time comes but atm it's a bit early to be opening this feature request.
