### ISSUE TITLE
weird sky rendering issue when using some shaders

### ISSUE THREAD

**Issue by trolls-incorporated** [Gilded-Games/The-Aether#92]
sildurs enhanced default shaders:
![2021-03-28_08 32 18](https://user-images.githubusercontent.com/80574284/112745467-8a22ae00-8fa0-11eb-81db-332b1b0f5385.png)
also sildurs enhanced default shaders, looking straight up:
![2021-03-28_08 32 36](https://user-images.githubusercontent.com/80574284/112745480-a6264f80-8fa0-11eb-8cc0-ff11b0998527.png)

**Comment by quek04** [comment]
we can't do anything about shaders
