### ISSUE TITLE
"flying is not enabled" when using golden parachute in survival

### ISSUE THREAD

**Issue by mkg20001** [Gilded-Games/The-Aether#99]
Reproduce:
- /execute in aether:aether run tp @s 0 100 0
- /give @s aether:golden_parachute
- jump off island
- use parachute
- wait 2s

branch 1.16 commit 367be79820e875c23ab55bc8f5911da0d6897cd9

**Comment by mkg20001** [comment]
Turns out this happens when falling too

- /effect give @s minecraft:health_boost 1000 255
- /effect give @s minecraft:regeneration 1000 255

And then before dying got "flying is not enabled"

**Comment by bconlon1** [comment]
I've seen no other reproduction of this issue so I doubt its an Aether issue.
